### ISSUE TITLE
Add biome/ecoregion to the data.frame by lookup to another dataset

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#133]
From tweet https://twitter.com/maxjfarrell/status/528229607393472512

I think we could do this by having dataset in the pkg (or pull it down on function call if too big) to add biome/ecoregion to the table as new columns by looking up by lat/long pair. 

Resources
- http://joewheatley.net/mapping-biomes/
- apparently can get shp files from http://www.worldwildlife.org/pages/conservation-science-data-and-tools

Do also for `spocc` I think

**Comment by afredstonhermann** [comment]
@sckott any chance it's now possible to query biomes/ecoregions through a rgbif call like `occ_search`? Or do you have another suggestion for how to do this? I'm using rgbif to validate range edges from a US-based marine dataset, and it would be a huge help to easily filter out records from across the ocean!

**Comment by sckott** [comment]
thx for the ping @afredstonhermann 

To clarify do you want to query GBIF or just filter data once already returned from GBIF?

GBIF doesn't return any data that would be helpful for biome/ecoregion that I know of

I think this kind of functionality would best live in another pkg, perhaps https://github.com/ropensci/scrubr  - i've opened an issue there https://github.com/ropensci/scrubr/issues/30
