### ISSUE TITLE
readme fixes

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#141]
These packages contain README.md files with invalid HTML output created
by pandoc 1.12.4.2 according to W3C-validator.

I attach the HTML errors and warnings found below, and will put copies
of the corresponding HTML files up at
<http://www.r-project.org/nosvn/pandoc>.

Please investigate the problems and fix as needed.

Afaics, many of the problems are caused by adding "raw" HTML elements in
the README.md files and not realizing that the default output format
"html" is XHTML 1 (and not HTML 5).  E.g., a raw <br> results in an

   end tag for "br" omitted, but OMITTAG NO was specified

error.

Best
-k

```
rgbif.html:
  Valid: FALSE (errors: 3, warnings: 2)
  Errors:
    line  col  message
      48   10  invalid comment declaration: found character "|" outside comment but inside comment declaration
     168   41  required attribute "alt" not specified
     180   98  required attribute "alt" not specified
  Warnings:
    line  col  message
      48    7  multiple comments in comment declaration
      48    9  S separator in comment declaration
```

**Comment by sckott** [comment]
Another reminder from Kurt Hornik to fix readme wc3 stuff  on 2015-01-30

**Comment by jarioksa** [comment]
Simplest solution would be to add README.md to .Rbuildignore. Do you really need that within a packaged package?

**Comment by sckott** [comment]
readme's do show up on CRAN pkg pages though http://cran.r-project.org/web/packages/dplyr/README.html - which i think is useful

**Comment by sckott** [comment]
@jarioksa and these requests from CRAN to fix little things are the only way I can submit pkgs more often than the once per month rule they've imposed on me
