### ISSUE TITLE
 Invalid integer range Error in occ_search

### ISSUE THREAD

**Issue by dandaman** [ropensci/rgbif#143]
Hi,

I'm trying to get occurence data for ~1400 species. Already tried it as a whole or in chunks of 50 and 100.
I keep getting the following error:

head(keys)
[[1]]
[1] 2980842

[[2]]
[1] 2978604

[[3]]
[1] 3189866

[[4]]
[1] 2873771

[[5]]
[1] 3189694

[[6]]
[1] 3085014

length(keys)
[1] 1173

dat <- do.call(rbind.data.frame,lapply(seq(1,length(keys),50), function(x) occ_search(taxonKey=keys[x:ifelse(x+50>length(keys),length(keys),x+50)], return='data')))                                          
Error: Invalid integer range: list(2639736, 2642020, 2641748, 2642016, 2638863, 5272029, 5271343, 5271359, 2644996, 5937508, 2638421, 5270704, 5271044, 5271102, 5271164, 5271199, 5271044, 5270925, 2638382, 3235438, 5271039, 3235438, 5271034, 3235438, 3235438, 2652027, 5272770, 2646385, NULL, 5271822, 5272096, 2638392, 2638393, 5274608, 5274413, 5274637, 5274495, 5273813, 2649855, 2687908, 2687908, 4921619, 2638755, 2646637, 2646647, 2646629, 4375567, 2648388, 5286264, 2687987, 2687984)

The same error occurs also with chunk size 100 and in one single statement. Currently trying chunk size 10. 

Is this a bug or am I doing something wrong?

Best,
Daniel

**Comment by sckott** [comment]
what version of `rgbif` are you using?

**Comment by sckott** [comment]
@dandaman I'm trying that out now with the most up to do date version, and i don't get that error. but you could be using an older version. 

in addition, some keys will return no data as they just don't have any data, in which case you can remove those e.g., like 

```r
out[!grepl("no data found", out)]
```

if `out` is the output of the `lapply(..., occ_search)` call

**Comment by dandaman** [comment]
Thank you @sckott for your prompt response!

I'm using the "latest" version from CRAN:
R package version 0.7.7. http://CRAN.R-project.org/package=rgbi

But I think you might have a point: 
keys[sapply(keys,is.null))                                                                                                                                                                              
[[1]]
NULL

Keys was populated using this call (d[,2] is a vector of species/genus/family names):
keys <- sapply(unique(d[,2]), function(x) name_suggest(x)$key[1], USE.NAMES=FALSE)

There's one entry returned by name_suggest that's NULL. Maybe this is the one causing the problem.

I'm currently trying without it...

I'll keep you posted.

**Comment by sckott** [comment]
closing due to inactvity
