### ISSUE TITLE
doco error in occ_search?

### ISSUE THREAD

**Issue by raymondben** [ropensci/rgbif#145]
occ_search docs say "Note that in occ_search we do the paging internally for you, so there's no start parameeter"

But there *is* a start parameter, and it works:

> this=occ_search(taxonKey=1,limit=10)
> this$meta
$offset
[1] 0

$limit
[1] 10

$endOfRecords
[1] FALSE

$count
[1] 364656374

> this$data$key[1]
[1] 1055092337

vs.

> this=occ_search(taxonKey=1,limit=10,start=5)
> this$meta
$offset
[1] 5

$limit
[1] 10

$endOfRecords
[1] FALSE

$count
[1] 364656374

> this$data$key[1]
[1] 1055092167

**Comment by sckott** [comment]
thanks for the catch, i'll get that documentation fixed
