### ISSUE TITLE
List of subtaxonomy in a taxonomic level?

### ISSUE THREAD

**Issue by elgabbas** [ropensci/rgbif#153]
Hello,
I am wondering whether it is possible to use rgbif to extract a list of some taxonomical sub-levels within a particular taxonomic level? e.g. I need to have the list of the names of orders within a particular class within GBIF database. Is it doable in rgbif package without downloading the whole dataset and doing the subsetting manually?

Thanks,
Ahmed

**Comment by sckott** [comment]
hi @elgabbas - thanks for your question. 

To clarify, are you looking to get taxonomic name data only, or occurrence data of certain taxonomic groups?  If only names, we have another package `taxize` (https://github.com/ropensci/taxize) that is built for getting name information and has hooks for GBIF name data.

**Comment by sckott** [comment]
e.g., in `taxize`

```r
library("taxize")
out <- downstream("Magnoliopsida", db = "col", downto = "Order")
head(out$Magnoliopsida)
#>  childtaxa_id   childtaxa_name childtaxa_rank
#> 1     22043094     Amborellales          Order
#> 2     22034801          Apiales          Order
#> 3     22042834     Aquifoliales          Order
#> 4     22034799        Asterales          Order
#> 5     22042809 Austrobaileyales          Order
#> 6     22043075   Balanophorales          Order
```

**Comment by elgabbas** [comment]
Thanks a lot Sckott for your immediate reply,
This package seems to be really helpful, although it may be useful to allow the use of GBIF as 'db' in further versions.

Regards,
Ahmed

**Comment by sckott** [comment]
@elgabbas So does the taxize e.g. work for your use case? 

I may add gbif as an option to the `db` parameter in `downstream()`, but it may be too slow/or too hard to do to be useful

**Comment by elgabbas** [comment]
For now yes, it was helpful for my current task. Thanks a lot.

**Comment by sckott** [comment]
@elgabbas great!
