### ISSUE TITLE
installing package for Centos 7 

### ISSUE THREAD

**Issue by stevensotelo** [ropensci/rgbif#164]
Hi everyone

I am installing the package from here (Github) in a server with Centos 7, but I have a problem when I execute:
```
devtools::install_github("ropensci/rgbif")
```
It show the next error:
```
ERROR: dependency ‘V8’ is not available for package ‘rgbif’
* removing ‘/usr/lib64/R/library/rgbif’
Error: Command failed (1)
In addition: Warning message:
In utils::install.packages(pkgs, repos = repos, type = type, ...,  :
  installation of package ‘V8’ had non-zero exit status
```
I installed the package V8 in my server but it doesn't work

Thanks for your help

**Comment by stevensotelo** [comment]
I found the problem:
run in the command line:
```
sudo yum install  v8-devel
```

**Comment by sckott** [comment]
@stevensotelo Thanks for the report.  I'll see if there's something we can do so that users don't have to do an extra step to get V8

so installation worked after `sudo yum install  v8-devel` ?

**Comment by sckott** [comment]
@jeroenooms perhaps theres now way around centos users having to `yum install` v8 first?

**Comment by stevensotelo** [comment]
@sckott, Yes it did

**Comment by jeroenooms** [comment]
libv8 is a hard dependency for the v8 package. No way around that :-)

**Comment by jeroenooms** [comment]
@stevensotelo didn't the configure script warn you that you needed to install `v8-devel` ?

**Comment by sckott** [comment]
@jeroenooms okay, thx. I'll make a note in the docs for pkgs i use V8 in

**Comment by stevensotelo** [comment]
@jeroenooms it only did when I tried to install from cran, but when the installation is by github, it doesn't show
