### ISSUE TITLE
Add format:'SIMPLE_CSV' as an option to download functions

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#168]
from #154

**Comment by sckott** [comment]
let's not do this for now, if people ask for it we can add later

**Comment by doccowley** [comment]
Hello ... could I ask for the SIMPLE_CSV option ... it would be helpful ;-)

**Comment by sckott** [comment]
@doccowley i got an email notification that you said 

> Hello ... could I ask for the SIMPLE_CSV option ... it would be helpful ;-)

but now it's gone. did you delete it (and thus i'll just forget about it) or maybe you posted and github somehow lost it (in which case I'll make sure to consider it)
