### ISSUE TITLE
 package ‘gbif’ is not available (for R version 3.2.2)

### ISSUE THREAD

**Issue by coyotree** [ropensci/rgbif#177]
Ran into this problem today when I was trying to use gbif.

**Comment by sckott** [comment]
How did you try to install?  Try `install.packages("rgbif")`

**Comment by coyotree** [comment]
Whoops! Forgot the r before gbif. Sorry about that.

**Comment by sckott** [comment]
did it work?

**Comment by coyotree** [comment]
It sure did. Everything downloaded perfectly.

**Comment by sckott** [comment]
great :+1:
