### ISSUE TITLE
eventDate problem in GBIF API

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#181]
http://dev.gbif.org/issues/browse/POR-1508

see if need to change anything here, or note to users

**Comment by sckott** [comment]
don't think anything to do rightnow

**Comment by cgendreau** [comment]
Currently working on http://dev.gbif.org/issues/browse/POR-1508

**Comment by sckott** [comment]
thanks - shouldn't affect this client (and the python client I maintain), no date parsing that would be affected

**Comment by sckott** [comment]
I'll probably say something in docs/changelog to notify users of the change
