### ISSUE TITLE
Having trouble using occ_issues() to remove issues

### ISSUE THREAD

**Issue by coyotree** [ropensci/rgbif#188]
Hi,
I'm trying to run the following code to remove 'cucdmis' (and other) issues:

```r
#pull occurrence data with coordinates for Drimiopsis
Drimiopsis_occurence <- occ_search(scientificName = 'Drimiopsis',
                         hasCoordinate = TRUE,
                         limit = 1000,
                         return = 'data')

#trying to create new data frame with issues removed
test <- Drimiopsis_occurence %>% occ_issues(-cucdmis)
```

This doesn't remove the rows with the issue. Seemed pretty straight forward on the tutorial but I'm probably missing something simple. 

Thanks for your help! -Cody

I'm using R v. 3.2.2 and rgbif v. 0.8.9

**Comment by sckott** [comment]
Thanks for reporting what versions you're using :) Hope you don't mind I edited your post to highlight the code block. Having a look

**Comment by sckott** [comment]
Okay, should be fixed, reinstall like `devtools::install_github("ropensci/rgbif")`

let me know if it works.

**Comment by sckott** [comment]
@coyotree

**Comment by coyotree** [comment]
Interesting, now when I try to run the occ_search() function that I listed above I get the following error:
Error in as.vector(x, "character") : 
    cannot coerce type 'externalptr' to vector of type 'character'

**Comment by sckott** [comment]
Ahh, Looks like their servers are down..looking into it

**Comment by sckott** [comment]
This is pretty unusual that they are down :)

**Comment by sckott** [comment]
Okay, @coyotree try it again, should be working now

**Comment by coyotree** [comment]
I hope that one day I will be able to be a great programmer. 
It works amazingly now! Multiple issues were removed when ran again. Thank you!!

**Comment by sckott** [comment]
Glad it works - let me know of any other feedback on `occ_issues()` 

> I hope that one day I will be able to be a great programmer. 

:+1:  :rocket:
