### ISSUE TITLE
Params that can do single query vs. many

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#200]
Right now, there are some params that you can pass in many values to in a vector or list and internally we do a request for each value. However, for some params GBIF API allows setting the parameter > once, so e.g. can do http://api.gbif.org/v1/occurrence/search?datasetKey=50c9509d-22c7-4a22-a47d-8c48425ef4a7&datasetKey=7b5d6a48-f762-11e1-a439-00145eb45e9a 

But that returns results all combined into one result set, so no way to separate out results based on input values. Though surely some use cases don't care about separating out results to match the input values. 

One way to do it could be 
1. pass in values as a vector `foo  = c('a', 'b')`, and we do separate request for each value, translating to a request to http://api.gbif.org/v1/occurrence/search?foo=a and a request to http://api.gbif.org/v1/occurrence/search?foo=b
2. pass in values comma separated in a character string `foo = 'a,b'`, and we do a single request for both values, translating to http://api.gbif.org/v1/occurrence/search?foo=a&foo=b

Right now the 1st works, and 2nd errors

``` r
occ_data(datasetKey="50c9509d-22c7-4a22-a47d-8c48425ef4a7,7b5d6a48-f762-11e1-a439-00145eb45e9a", limit=20)
#> Error: Invalid UUID string: 50c9509d-22c7-4a22-a47d-8c48425ef4a7,7b5d6a48-f762-11e1-a439-00145eb45e9a 
```

could implement 2nd option, i don't think that would break any code

**Comment by sckott** [comment]
done, checked:

- [ ] dataset_metrics
- [ ] dataset_search
- [ ] dataset_suggest
- [ ] datasets
- [ ] installations
- [ ] name_backbone
- [ ] name_lookup
- [ ] name_suggest
- [ ] name_usage
- [ ] networks
- [ ] nodes
- [ ] occ_by
- [ ] occ_by_keys
- [ ] occ_count
- [ ] occ_data
- [ ] occ_download
- [ ] occ_download_cancel
- [ ] occ_download_cancel_staged
- [ ] occ_download_get
- [ ] occ_download_import
- [ ] occ_download_list
- [ ] occ_download_meta
- [ ] occ_facet
- [ ] occ_get
- [ ] occ_issues
- [ ] occ_issues_lookup
- [ ] occ_metadata
- [ ] occ_search
- [ ] occ_spellcheck

**Comment by PhillRob** [comment]
Just figured out `occ_count` accepts the first option you explained above for the ISO2c country code, but querys on after the other. Would be great to have this documented somewhere and be more flexible of what is parameter class is accepted (eg. list, vector,etc.)

**Comment by sckott** [comment]
@PhillRob what does 

> but querys on after the other.

mean?

I'm working on this now locally and will be updated here soon

**Comment by PhillRob** [comment]
I meant to make reference to you option 1 above. Where individual strings of a char. vector result in separate requests

> pass in values as a vector foo = c('a', 'b'), and we do separate request for each value, translating to a request to http://api.gbif.org/v1/occurrence/search?foo=a and a request to http://api.gbif.org/v1/occurrence/search?foo=b
