### ISSUE TITLE
ubuntu install problem

### ISSUE THREAD

**Issue by AlexPeap** [ropensci/rgbif#207]
Hi
I use xbuntu. I have the lasted version of R(3.2.4)  and RStudio 
when I tried to install the package i got this warning: 
"installation of package ‘rgbif’ had non-zero exit status"
I think that i need the rgibf lib.

¿where can i get it?

than you
the best

**Comment by sckott** [comment]
to be sure, is that __Ubuntu__ or __Xubuntu__ ?  Are other pkgs installing correctly?

**Comment by jarioksa** [comment]
I'm on Ubuntu and I have no problems in building and installing **rgbif**. I bet there is something more than just one line of `non-zero exit status`: what other error messages you got?

**Comment by AlexPeap** [comment]
it is Xubuntu. The other pkgs are intalling correctly.

In the pkg "rgal" i had to intall the "libgal" first. That is why i think i
need one kind of lib


thank you

2016-04-13 23:03 GMT-05:00 Scott Chamberlain <notifications@github.com>:

> to be sure, is that *Ubuntu* or *Xubuntu* ? Are other pkgs installing
> correctly?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rgbif/issues/207#issuecomment-209751309>
>



-- 
Alexander Peña-Peniche
Estudiante Doctorado
Lab. de Biogeografía y Análisis Espacial
INECOL A. C.
e-mail: alexander.pena@posgrado.ecologia.edu.mx
<luis.pena@posgrado.inecol.edu.mx>

**Comment by sckott** [comment]
yeah, `rgdal` is needed, here's some hint on how we install some linux deps https://github.com/ropensci/rgbif/blob/master/.travis.yml#L8

**Comment by sckott** [comment]
@AlexPeap did you try again to install?

**Comment by sckott** [comment]
closing, i assume this is sorted

**Comment by AlexPeap** [comment]
Hi
I am so sorry for did not answer before, but i was in the field trip, I'm
biologist. The problem was fixed re-installing R and RStudio, before to
todo that I install several lib in the ubuntu's terminal after this all
thing work nice and easy.

Thank you for your time

Alex

2016-04-28 3:49 GMT-05:00 Scott Chamberlain <notifications@github.com>:

> @AlexPeap <https://github.com/AlexPeap> did you try again to install?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rgbif/issues/207#issuecomment-215355805>
>



-- 
Alexander Peña-Peniche
Estudiante Doctorado
Lab. de Bioclimatología
INECOL A. C.
e-mail: alexander.pena@posgrado.ecologia.edu.mx
<luis.pena@posgrado.inecol.edu.mx>

**Comment by sckott** [comment]
glad it works now :)
