### ISSUE TITLE
Documentation: how to get a list of permitted regions

### ISSUE THREAD

**Issue by rossmounce** [ropensci/rgbif#212]
Trying to the follow the instructions given here in the documentation:
http://www.inside-r.org/packages/cran/rgbif/docs/gbifmap

I want to find out the list of permitted regions. It is suggested one runs:
```
sort(unique(map_data("world")$region))
```

I don't get the desired output. Am I misunderstanding the instruction?
```
library(maps)
library(mapdata)
library(rgbif)
sort(unique(map_data("world")$region)) 
Error in unique(map_data("world")$region) : 
  could not find function "map_data"
```

**Comment by sckott** [comment]
sorry, that's supposed to be `ggplot2`

**Comment by sckott** [comment]
okay, fixed the docs, try instead `sort(unique(ggplot2::map_data("world")$region))` or `sort(unique(ggplot2::map_data("state")$region))`

**Comment by sckott** [comment]
@rossmounce let me know if that works

p.s. i've put most mapping/vis effort into [mapr](https://github.com/ropensci/mapr) - if you are looking to do vis, that's a better place to go - though you probably are a viz ninja already

**Comment by sckott** [comment]
yes, both hard! programming is easier than stats for me

- closing, reopen if needed
