### ISSUE TITLE
associatedTaxa

### ISSUE THREAD

**Issue by qgroom** [ropensci/rgbif#223]
Not a bug, but a feature request perhaps.
I'd like to be able to extract the associatedTaxa field from occurrences.
For example, if I have a parasite I'm interested in how can I pull out all the host species mentioned in datasets?
Regards
Quentin

**Comment by sckott** [comment]
Thanks for your question. Can you give some example parasite names you'd be interested in.

**Comment by qgroom** [comment]
I'm interested in a wide variety of organism intereactions, I more interested if people are collecting the information, rather than the data itself.
Some examples of plant parasites I picked out as examples are...
Nuytsia floribunda
Cuscuta europaea
Arceuthobium oxycedri
Anthobolus filifolius
Viscum album
Balanophora fungosa
Orobanche uniflora
Orobanche minor
Monotropa hypopitys
Conopholis americana

Also good examples of animal parasites are...
Remora remora
Conopholis americana
Simenchelys parasitica
Dasypsyllus gallinulae
Pinnotheres pisum
Varroa destructor
Sacculina carcini
Clonorchis sinensis
Andricus quercuscalifornicus
Phytomyza ilicis

**Comment by sckott** [comment]
thanks for the examples

>  I more interested if people are collecting the information, rather than the data itself.

so you mainly want presence/absence of of the `associatedTaxa` field?  or any host information, regardless of field? because there appears to be host notes in other fields, e.g., `occurrenceRemarks` in this occurrence http://api.gbif.org/v1/occurrence/1211989229

**Comment by qgroom** [comment]
I need to see what is in it too, so that I can judge how useful it is.
Yes, it would be useful to see what it in occurrenceRemarks. I suppose there might also be data in  associatedOccurrences, associatedOrganisms & organismRemarks.

**Comment by sckott** [comment]
@qgroom This seems like a use case that'd be more useful applied across data sources, i'll get something up on github and ping you soon

**Comment by sckott** [comment]
@qgroom started something here https://github.com/ropenscilabs/hoasts to play around with ideas

**Comment by qgroom** [comment]
Great! I'm just leaving for two weeks holiday, but I'll take a look once I get back, sooner if we have internet.

**Comment by sckott** [comment]
sounds good

**Comment by sckott** [comment]
@qgroom closing this given `hoasts`, hope that's okay

**Comment by qgroom** [comment]
Sure! It is an interesting and important subject and I'll have to see if I
can work on it more.
Quentin



Dr. Quentin Groom
(Botany and Information Technology)

Botanic Garden Meise
Domein van Bouchout
B-1860 Meise
Belgium

ORCID: 0000-0002-0596-5376 <http://orcid.org/0000-0002-0596-5376>

Landline; +32 (0) 226 009 20 ext. 364
FAX:      +32 (0) 226 009 45

E-mail:     quentin.groom@plantentuinmeise.be
Skype name: qgroom
Website:    www.botanicgarden.be
