### ISSUE TITLE
Downloads 'killed'

### ISSUE THREAD

**Issue by maxhenschell** [ropensci/rgbif#245]
I am attempting to download occurance data for 75 species, with a  using occ_download. My first attempts were killed, so I contacted helpdesk@gbif.org. The response was to try fewer species, since the API can only handle ~100 species/parameters. I tried 10 species, with the same parameters, and the download was killed again. Helpdesk suggested posting here if that did not work. Not sure if this is a 'bug' or an error on my part, but I'd appreciate any guidance.

My last call:
`occ_download("taxonKey = 2475470", "taxonKey = 2480946", "taxonKey = 5229208", "taxonKey = 2481696", "taxonKey = 2490255", "taxonKey = 2495864", "taxonKey = 7341544", "taxonKey = 2477774", "taxonKey = 7341576", "taxonKey = 2477828",  "basisOfRecord = HUMAN_OBSERVATION", "basisOfRecord = OBSERVATION", "basisOfRecord = MACHINE_OBSERVATION","country = US", "hasCoordinate = TRUE", "hasGeospatialIssue = FALSE", "year = 1949,2011", "month = 3,8")`
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgbif_0.9.6      SDMTools_1.1-221 ggplot2_2.1.0   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6       whisker_0.3-2     xml2_1.1.0        magrittr_1.5      munsell_0.4.3     colorspace_1.2-6  lattice_0.20-33  
 [8] R6_2.1.3          stringr_1.1.0     httr_1.2.1        plyr_1.8.4        tools_3.3.1       grid_3.3.1        geoaxe_0.1.0     
[15] data.table_1.9.6  gtable_0.2.0      R.oo_1.21.0       rgeos_0.3-22      assertthat_0.1    tibble_1.2        R.utils_2.5.0    
[22] curl_1.2          sp_1.2-3          V8_1.2            stringi_1.1.1     oai_0.2.2         scales_0.4.0      R.methodsS3_1.7.1
[29] jsonlite_1.0      chron_2.3-47
```

**Comment by sckott** [comment]
thanks @maxhenschell I'll have a look

**Comment by sckott** [comment]
The default for combining the statements in your query is "AND" - so `"taxonKey = 2475470" AND  "taxonKey = 2480946"` and so on - But for the `taxonKey` values, I assume you really want "OR", correct?  when I do 

```r
res <- occ_download("taxonKey = 2475470", "taxonKey = 2480946", "taxonKey = 5229208", 
             "taxonKey = 2481696", "taxonKey = 2490255", "taxonKey = 2495864", 
             "taxonKey = 7341544", "taxonKey = 2477774", "taxonKey = 7341576", 
             "taxonKey = 2477828")
```

which is using the "AND" combinator, I get 0 results. 

But when I do 

```r
res <- occ_download("taxonKey = 2475470", "taxonKey = 2480946", "taxonKey = 5229208", 
             "taxonKey = 2481696", "taxonKey = 2490255", "taxonKey = 2495864", 
             "taxonKey = 7341544", "taxonKey = 2477774", "taxonKey = 7341576", 
             "taxonKey = 2477828", type = "or")
```

I get something like 160K - dont remember exact number - I assume this is the behavior you want, not the above where you get 0 results?

If so, then we need to use "or" operator, not "and"

And if that's the case, we can't really include your other query parameters because I would think they would need to be combined with the taxonkey params via "and". 

If that's the case, GBIF's API as far as I know can't support this right now, but I'll ask

**Comment by maxhenschell** [comment]
Yes, the second result sounds more like what I'd be looking for. It's unfortunate that the other parameters cannot be combined with the taxonkeys, but I could always clean up the data after it's downloaded. 

Thanks for looking into this.

**Comment by sckott** [comment]
the best solution I can think of right now is to do one query per taxonkey, like 

```r
occ_download("taxonKey = 2475470",  "basisOfRecord = HUMAN_OBSERVATION", "basisOfRecord = OBSERVATION", "basisOfRecord = MACHINE_OBSERVATION","country = US", "hasCoordinate = TRUE", "hasGeospatialIssue = FALSE", "year = 1949,2011", "month = 3,8")
```

and so on

but then again, i would think if you have > 1 of a parameter, like you do for basisOfRecord you'd need to haven an OR for those, cause each record can only be one type of basisOfRecord

I've asked on the mailing list, hope to get a response soon

**Comment by sckott** [comment]
@maxhenschell after reinstalling `devtools::install_github("ropensci/rgbif")`, try again

```r
keys <- c('2475470', '2480946', '5229208', '2481696', '2490255', '2495864', '7341544', '2477774', '7341576', '2477828')

res <- occ_download(
  paste("taxonKey =", paste(keys, collapse = ",")), 
  "basisOfRecord = HUMAN_OBSERVATION,OBSERVATION,MACHINE_OBSERVATION",
  "country = US", 
  "hasCoordinate = true", 
  "hasGeospatialIssue = false", 
  "year >= 1949",
  "year <= 2011", 
  "month >= 3",
  "month <= 8"
)
res
occ_download_meta(res)
(out <- occ_download_get(res) %>% occ_download_import())
```

**Comment by maxhenschell** [comment]
I ran the code suggested. The download started, though when I checked the download page on GBIF the year in the query was >=1949 and the month was >= March.

> QUERY
Taxon	...
Basis of record	Human Observation,Observation,Machine Observation
Country	United States
Georeferenced	true
Spatial issues	false
Year	>= 1949,
Month	>= March,

When I compare it to other downloads through the GBIF site for a single species with similar criteria, this seems to suggest (though I might be wrong) that the range is not being accepted (e.g. [1949,2011]). I tried 

`res <- occ_download(paste("taxonKey =", paste(keys[1:25], collapse = ",")), "basisOfRecord = HUMAN_OBSERVATION,OBSERVATION,MACHINE_OBSERVATION",  "country = US",  "hasCoordinate = true", "hasGeospatialIssue = false", "year = 1949,2011", "month = 3,8")`

But the query looks like it was only getting two years and two months, not the range:

> QUERY
Taxon	...
Basis of record	Human Observation,Observation,Machine Observation
Country	United States
Georeferenced	true
Spatial issues	false
Year	1949,2011
Month	March,August

I also tried a range in the year and month: 
`res <- occ_download( paste("taxonKey =", paste(keys, collapse = ",")),  "basisOfRecord = HUMAN_OBSERVATION,OBSERVATION,MACHINE_OBSERVATION", "country = US",  "hasCoordinate = true", "hasGeospatialIssue = false",  "year = 1949-2011",  "month = 3-8")`

but that threw an error:

> Error: Instantiation of [simple type, class org.gbif.api.model.occurrence.predicate.EqualsPredicate] value failed: Invalid integer range: 1949-2011 (through reference chain: org.gbif.api.model.occurrence.predicate.EqualsPredicate["value"])

It seems (for me) the best course as yet is to download all of the data for my species of interest, then clean that. The suggestion to iterate through each species (I used a loop...) resulted in an HTTP 420 error...

Thanks again for keeping after this. A complex query functionality would be great to see!

**Comment by sckott** [comment]
@maxhenschell sorry, i put it in the eg above, but to reiterate, you can't do range queries with the download api, - that's why the beginning and end of the range for year and month are two diff. queries. try taht

**Comment by maxhenschell** [comment]
@sckott OK, I see that the two queries did work (your suggested code, above). When I looked at the queue on my GBIF site I didn't see the maximal ends of the year and month, so I assumed it hadn't gone through. 

Thanks!

**Comment by maxhenschell** [comment]
In addition, using the above code, I was able to download data for 75 species, rather than having to break it into subsets. Thanks again @sckott!

**Comment by sckott** [comment]
@maxhenschell great! glad it worked
