### ISSUE TITLE
occ_download Import problem

### ISSUE THREAD

**Issue by poldham** [ropensci/rgbif#246]
Hi Scott, 

This is a question about importing a dataset using occ_download_get for a walkthrough I am writing on rgbif involving data for Kenya. 

I have an occurrence dataset for kenya at [doi:10.15468/dl.v4on0g](http://www.gbif.org/occurrence/download/0001369-160509122628363). 

Using `kenya_gbif <- occ_download_get("0001369-1605091#22628363", overwrite = TRUE) %>% occ_download_import(kenya_gbif)`

I get an error that arises from `occ_download_import` as follows (with traceback)

```r
Error in data.table::fread(file.path(tmpdir, "occurrence.txt"), data.table = FALSE) : File '/var/folders/lz/xwyq8xyn1xz22srmd74cn1l40000gq/T//Rtmp7cSNQP/0001369-160509122628363/occurrence.txt' does not exist. Include one or more spaces to consider the input a system command.
4.
stop("File '", input, "' does not exist. Include one or more spaces to consider the input a system command.")
3.
data.table::fread(file.path(tmpdir, "occurrence.txt"), data.table = FALSE)
2.
tibble::as_tibble(data.table::fread(file.path(tmpdir, "occurrence.txt"), data.table = FALSE))
1.
occ_download_import(kenya_gbif_download)
```

A review of the `occ_download()` code reveals that the problem is the reference to "occurrence.txt" in line 43. 

A possible fix is something like creating object "out" with the key, pasting the file extension and then calling "out" in place of "occurrence.txt" (see commented)

```r
  tmpdir <- file.path(tempdir(), key)
  unzip(path, exdir = tmpdir, overwrite = TRUE)
  out <- paste0(key, ".csv") # added
  tibble::as_tibble(
    # data.table::fread(file.path(tmpdir, paste0(key, "occurrence.txt"), data.table = FALSE)
    data.table::fread(file.path(tmpdir, out), data.table = FALSE) # modified
  )
```

With this modification the file imports and produces a message "Read 532768 rows and 44 (of 44) columns... etc" with a warning on coercion of images. That message is expected for this file. 

What is unclear to me is whether GBIF occurrence downloads take any other format than the .csv requiring more elaboration of the code. There may of course be a neater way of fixing the above.  

All the best, 

Paul 

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgbif_0.9.7          tidyr_0.6.1          tibble_1.2           rorcid_0.3.0        
[5] dplyr_0.5.0          RDocumentation_0.8.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8.4       plyr_1.8.4          tools_3.3.2         digest_0.6.10      
 [5] jsonlite_1.2        memoise_1.0.0       gtable_0.2.0        lattice_0.20-34    
 [9] DBI_0.5-1           curl_2.3            proto_0.3-10        withr_1.0.2        
[13] httr_1.2.1          stringr_1.1.0       knitr_1.15.1        xml2_1.1.0         
[17] rgeos_0.3-22        devtools_1.12.0     grid_3.3.2          data.table_1.10.0  
[21] geoaxe_0.1.0        R6_2.2.0            oai_0.2.2           githubinstall_0.1.0
[25] sp_1.2-4            readr_1.0.0         whisker_0.3-2       ggplot2_2.2.1      
[29] magrittr_1.5        scales_0.4.1        assertthat_0.1      colorspace_1.2-6   
[33] V8_1.1              stringi_1.1.2       lazyeval_0.2.0      munsell_0.4.3      
[37] rjson_0.2.15       ```

**Comment by sckott** [comment]
thanks @poldham I'll have a look

**Comment by sckott** [comment]
* how did you get that download? i assume it was through the GBIF website?  because all downloads i've seen requested through the rgbif package make a darwin core archive zip file with many files including `occurrence.txt` 
* your fix would work for csv files, but not when it's an occurrence.txt file - i'll look at a a lot of downloads and see what the range of file names is and see what general solution is best

**Comment by poldham** [comment]
Thanks Scott, That is correct, I created it on the website using the .csv rather than Darwin core option. I took another look this afternoon and there are only two options for occurrence downloads (csv and darwin). I guess that providing for both options would add flexibility for users. Maybe an argument to ask the user to specify the type of download, e.g. type = darwin or csv. Thanks for getting back so quickly on this, much appreciated.

**Comment by sckott** [comment]
@poldham  reinstall and try again

**Comment by poldham** [comment]
Hi Scott, That’s great. I have run this on a few datasets to test. 

1. Kenya. All good
2. Antigua and Barbuda  2MB and 22648 rows. All good.  Small file (maybe useful for testthat)  http://www.gbif.org/occurrence/download/0004579-160118175350007 <http://www.gbif.org/occurrence/download/0004579-160118175350007>.  doi:10.15468/dl.scred1 
3. Mexico 561.9 MB 8,131,716 records. All good. http://www.gbif.org/occurrence/download/0025620-160910150852091 <http://www.gbif.org/occurrence/download/0025620-160910150852091>. doi:10.15468/dl.quzxn5

I also ran a test on two occurrence sets for South Africa. The latest is 593.7 MB 14,225,175 records from May 2016. http://www.gbif.org/occurrence/download/0001355-160509122628363 . doi:10.15468/dl.raa6hs

Both versions threw the same error (below for info) suggesting that it is a new line problem in the ZA datasets and needs to be raised with the GBIF secretariat to fix. 

Thanks again for such a rapid fix. 

Best, 

Paul 

Download file size: 593.74 MB

possible truncation of >= 4GB file
 Show Traceback
Error in data.table::fread(targetpath, data.table = FALSE) : Expected sep ('	') but new line, EOF (or other non printing character) ends field 14 when detecting types from point 10: 1226330904	b4ae1720-1431-49ee-bfeb-8146fc42b1a3 urn:catalog:ADU:SAFRING:FA3919:1084497	Animalia Chordata	Aves	Passeriformes	Ploceidae	Quelea Quelea quelea	SPECIES	Quelea quelea (Linnaeus, 1758)	ZA	Klaserie

**Comment by sckott** [comment]
thanks for the report back @poldham  and glad it works. 

good idea for that Antigua/Barbuda dataset for testing

**Comment by poldham** [comment]
Thanks again Scott, 

This could be a separate issue, but the .csv data files contain a large number of blank cells as well as NAs. It may make sense to handle these when importing with fread by adding `na.strings = c("", NA)`. That would make life easier for the user later. I simply tacked on `%>% dplyr::na_if(“”)` to occ_download_import() to handle that.

**Comment by sckott** [comment]
hmm, i think i'd rather not alter the data - BUT could add to the docs a warning about this

**Comment by poldham** [comment]
Understood, I guess the options are to add a note to the docs or maybe make the na.strings argument for fread available? A note on how to deal with it would be good I think for new users.

**Comment by sckott** [comment]
There's currenlty no `...` in use in that fxn, so could allow `...` and those args get passed on to `fread`

**Comment by poldham** [comment]
Good idea, I tried the na arg this morning without looking at the code on the off chance. I guess the question is what other args are in … and whether they might cause problems. But, it sounds like a good solution with a note in the documentation on that.

**Comment by poldham** [comment]
Reviewing args to fread it looks like ... would provide additional flexibility.

**Comment by sckott** [comment]
is fine to allow args to pass on to `fread` - AFAIK they deal well with user inputs and fail well, so should be fine

**Comment by poldham** [comment]
Ok, cool and thanks.

**Comment by sckott** [comment]
i think this is sorted
