### ISSUE TITLE
Install Instructions in README

### ISSUE THREAD

**Issue by SriramRamesh** [ropensci/rgbif#254]
I installed rgbif in Mac os
I had to search for some missing install instructions.
Common Problems: fatal #include<openssl/ssl.h> not found, v8 install return non-zero exit,..
CMD
1.brew install openssl
2.brew install gdal
3.brew tap homebrew/versions
4.brew install v8-315
R terminal:
1.install.packages('openssl')
2.install.packages('rgeos')
3.install.packages('V8')
4.install.packages('rgbif')

Can I give a PR?

**Comment by sckott** [comment]
Hi - Thanks for the issue. 

Were you trying to install from master here or from CRAN?  b/c `V8` should no longer be needed - removed in the last commit, see https://github.com/ropensci/rgbif/commit/7363c0d5e37d04b6dbff5c587f3c63238a69b770  and i don't see any deps that depend on `V8`

I'd be happy to look at PR for the readme for the other bits though: gdal, openssl, rgeos

**Comment by SriramRamesh** [comment]
Thanks for replying!.. Yes I tried to install from CRAN I'll submit a PR

**Comment by sckott** [comment]
close via #255
