### ISSUE TITLE
occ_download_import error: bad new line or EOF

### ISSUE THREAD

**Issue by cathynewman** [ropensci/rgbif#257]
Hi Scott,

(This isn't urgent; I'm just playing around with the package.)

I initiated a download through rgbif using `occ_download`:
82 species
310,370 records
Zip file size: 84.8 MB
http://www.gbif.org/occurrence/download/0065010-160910150852091

I tried to import the data 2 ways. First, since I already had the zip file downloaded to my HD, I tried this:

```
as.download("0065010-160910150852091.zip")
as.download(key = "0065010-160910150852091")
occ_download_import(as.download("0065010-160910150852091.zip"))
```

At `occ_download_import` I got this error:

> Error in data.table::fread(file.path(tmpdir, "occurrence.txt"), data.table = FALSE) : 
>  Expected sep ('	') but new line or EOF ends field 174 on line 295879 when reading data: 866180086		http://vertnet.org/resources/norms.html																								urn:catalog:UTEP:Herps:H-16836									en	CC0_1_0			2015-02-14T01:00Z			http://portal.vertnet.org/o/utep/herps?id=h-16836												PhysicalObject		http://grbio.org/cool/gq95-3z97	urn:lsid:biocol.org:col:34876		UTEP	Herps			PRESERVED_SPECIMEN				urn:catalog:UTEP:Herps:H-16836	H-16836		UNIV. MISSISSIPPI (HUTCHINSON, DC 42) 0825								NATIVE	present	alcoholic						"TUBY TOBY" CREEK" SHOULD BE SPELLED "TOBY TUBBY" CREEK [USGS PLACENAME]												1968-07-30T01:00Z		212	212	1968	7	30											| USA | MISSISSIPPI | LAFAYETTE CO |  |  |  |	NORTH_AMERICA				US	Mississippi	Lafayette		5 MI. NW OXFORD, TUBY TOBY CREEK [SIC, SEE COMMENT]	USA | MISSISSIPPI | LAFAYETTE CO | 5 MI. NW OXFORD, TUBY TOBY CREEK [SIC, SEE COMMENT]							34.42195999533563	-89.61411772914715	2636.0			degrees decimal minutes					CS Lieb (UTEP)	6/23/20
>In addition: There were 28 warnings (use warnings() to see them)

Traceback:

```
3: data.table::fread(file.path(tmpdir, "occurrence.txt"), data.table = FALSE)
2: tibble::as_tibble(data.table::fread(file.path(tmpdir, "occurrence.txt"), 
       data.table = FALSE))
1: occ_download_import(as.download("0065010-160910150852091.zip"))
```

I then tried pulling the download from the server through rgbif instead:

`occ_download_get(key="0065010-160910150852091", overwrite = TRUE) %>%
occ_download_import`

But that gave the same error. I opened `occurrence.txt` and looked at that specific record, and there doesn't seem to be anything different about that record compared to a very similar one (from the same institution) a few lines above it - no new line or EOF character that I could find. But it seems like maybe fread isn't parsing that record correctly: warnings 18-28 are about that line, and the strings specified in the warnings aren't what should actually be in those columns/fields.

Later, to test whether the problem is something about that specific record that I wasn't able to find, I initiated another download through rgbif for only that species, _Eurycea longicauda_, taxonKey 5218348: http://www.gbif.org/occurrence/download/0065422-160910150852091

I tried importing that data set using the same `occ_download_get` and `occ_download_import` steps as above, and it worked fine. I checked `occurrence.txt` manually to make sure it included the problematic record (it does). So I'm not sure why the large import failed. I will try initiating a new download with all but _Eurycea longicauda_ to see if that works.

Cheers,
Cathy

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgbif_0.9.7

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8       lattice_0.20-34   assertthat_0.1    V8_1.2            R6_2.2.0          grid_3.3.2       
 [7] plyr_1.8.4        jsonlite_1.2      gtable_0.2.0      magrittr_1.5      scales_0.4.1      httr_1.2.1       
[13] ggplot2_2.2.1     stringi_1.1.2     curl_2.3          lazyeval_0.2.0    data.table_1.10.0 whisker_0.3-2    
[19] sp_1.2-4          xml2_1.0.0        oai_0.2.2         tools_3.3.2       stringr_1.1.0     munsell_0.4.3    
[25] colorspace_1.3-2  rgeos_0.3-21      tibble_1.2        geoaxe_0.1.0
```

**Comment by sckott** [comment]
@cathynewman so sorry for the delay!  

having a look now

**Comment by sckott** [comment]
@cathynewman try again after reinstalling (changes are on a different branch) `devtools::install_github("ropensci/rgbif@many-args")`

**Comment by sckott** [comment]
this should be fixed now, closing. let me know if it's not fixed!
