### ISSUE TITLE
Error with dataset_metrics function?

### ISSUE THREAD

**Issue by stevenpbachman** [ropensci/rgbif#270]
<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_1.1.0  rgbif_0.9.8  raster_2.5-8 sp_1.2-4    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10      whisker_0.3-2     xml2_1.1.1        knitr_1.15.1      magrittr_1.5      hms_0.3           munsell_0.4.3     colorspace_1.3-2 
 [9] lattice_0.20-34   R6_2.2.0          httr_1.2.1        stringr_1.2.0     plyr_1.8.4        tools_3.3.3       grid_3.3.3        geoaxe_0.1.0     
[17] data.table_1.10.4 gtable_0.2.0      htmltools_0.3.5   rgeos_0.3-22      lazyeval_0.2.0    yaml_2.1.14       rprojroot_1.2     digest_0.6.12    
[25] tibble_1.3.0      ggplot2_2.2.1     curl_2.6          crul_0.3.4        evaluate_0.10     rmarkdown_1.4     oai_0.2.2         stringi_1.1.3    
[33] scales_0.4.1      backports_1.0.5   jsonlite_1.5   
```
</details>

I was just trying to run the `dataset_metrics` function, but I get an *Error: Status: 204 - not found* response. See the line below. The call directly to GBIF seems ok:
http://api.gbif.org/v1/dataset/b5cdf794-8fa4-4a85-8b26-755d087bf531

I could also just be missing something very simple... Thanks in advance for looking into it.

```{r}
meta = dataset_metrics(uuid ='b5cdf794-8fa4-4a85-8b26-755d087bf531')
```

**Comment by sckott** [comment]
thanks for the report @stevenpbachman !

if you look internally in the `dataset_metrics` function, it calls a API route of `http://api.gbif.org/v1/dataset/<dastasetid>/metrics`, note the `/metrics` at the end

So the correct URL for the dataset id in question would be http://api.gbif.org/v1/dataset/b5cdf794-8fa4-4a85-8b26-755d087bf531/metrics  which gives an error like you reported above

This is a known problem by GBIF - I reported it a while back http://dev.gbif.org/issues/browse/POR-2809 

@timrobertson100 any thoughts on this problem?

**Comment by stevenpbachman** [comment]
thanks for looking into this @sckott & @timrobertson100 

I just realised that `datasets` function would get me what I need for now, but still useful to have `dataset_metrics` working as I'm sure I'll need to make use of that at some point.

thanks, Steve

**Comment by sckott** [comment]
will update this when I heard back @stevenpbachman

**Comment by timrobertson100** [comment]
Hi Scott, Steven

I'm not sure I fully understand the problem. 

[Dataset metrics](http://www.gbif.org/developer/registry#datasetMetrics) are only available for checklists.

[The dataset](https://demo.gbif.org/dataset/b5cdf794-8fa4-4a85-8b26-755d087bf531) is an occurrence dataset, so there are no metrics to return for that currently.  I think the API is returning a 204 as per the intended design, not throwing an error:

```
$ curl -v http://api.gbif.org/v1/dataset/2628fac4-bc07-4024-acd5-ed13c3b276f9/metrics
*   Trying 130.225.43.2...
* Connected to api.gbif.org (130.225.43.2) port 80 (#0)
> GET /v1/dataset/2628fac4-bc07-4024-acd5-ed13c3b276f9/metrics HTTP/1.1
> Host: api.gbif.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 204 No Content
```

**Comment by sckott** [comment]
thanks @timrobertson100 ! 

@stevenpbachman So i think best way forward is when a user passes a dataset ID that is anot a checklist, we give a message saying so so the user isn't left thinking there's some problem with `rgbif` or with GBIF

**Comment by timrobertson100** [comment]
Thanks Scott

If I recall correctly, the intention might have been that because metrics
are calculated asynchronously they return 204 and then will (hopefully) at
some point return 200.  I agree this area needs a revision (and all dataset
types should have metrics) but it'll be unlikely to be resolved soon I'm
afraid.

On Thu, Aug 10, 2017 at 6:07 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
thanks @timrobertson100 for the explanation, i think adding the additional message here for users will really help
