### ISSUE TITLE
Activate Zenodo switch and add DOI to package README?

### ISSUE THREAD

**Issue by cboettig** [ropensci/rgbif#273]

**Comment by sckott** [comment]
activated. do we git tag a release just for the paper? any particular tag name?

**Comment by cboettig** [comment]
nice.  oh, that's a good idea.  We could just use the tag `rgbifms` ?

**Comment by sckott** [comment]
sounds good

do we link the zenodo badge to the manuscript repo?

**Comment by cboettig** [comment]
Good question, that's probably a good idea.  I guess our 'releases' should correspond to the submission of the preprint copy, and then we can do another 'release' if we submit for peer review.  Activating zenodo and including the DOI will be a nice way for the reader of the preprint to see "has this thing changed?" or "is there a new version" etc.

**Comment by sckott** [comment]
sounds good. So we do releases:

- when we submit preprint
- when we submit for peer-review
