### ISSUE TITLE
citing GBIF downloads

### ISSUE THREAD

**Issue by dnoesgaard** [ropensci/rgbif#274]
While putting together some suggestions for authors on how to cite data downloaded through the GBIF API, I came across the gbif_citation function. I noticed that for asynchronous downloads, the function appears to pull citations from each of the contributing datasets? For these downloads, GBIF does mint a single DOI containing references to all datasets, and I was wondering if using this as a suggested citation might be a simpler solution?

The DOI is included in the download metadata, e.g
http://api.gbif.org/v1/occurrence/download/0005737-171002173027117

```
{
"key": "0005737-171002173027117",
"doi": "doi:10.15468/dl.j0ehrr",
...
"created": "2017-10-18T09:35:17.658+0000",
...
}
```

For the download, the recommended citation would be:

> GBIF Occurrence Download doi:`<doi>` accessed via GBIF.org on `<created>`

which could be amended as preferred, e.g.

> GBIF Occurrence Download doi:`<doi>` Accessed from R via rgbif (https://github.com/ropensci/rgbif) on `<created>`

The most important detail is the DOI which allows for tracking and also enables reproducibility.

**Comment by sckott** [comment]
thanks for the issue @dnoesgaard 

Good idea to have a citation for the download as a whole. 

This looks good to me:

> GBIF Occurrence Download doi:<doi> Accessed from R via rgbif (https://github.com/ropensci/rgbif) on <created>

----

for the `gbif_citation` function, I think I'd prefer to keep the citation output for each individual datasets, but have this single citation at the top, sound good?

**Comment by dnoesgaard** [comment]
Thanks, @sckott. Yes, that would be great. What makes DOI citation especially useful is that it refers to the specific records downloaded, not just the parent datasets (i.e. a download could contain a single record from a dataset of 200 million). And every time GBIF [picks up](https://www.gbif.org/literature-tracking) one of these in a paper reference, we store the link and the download is marked as a "cited" so it doesn't get deleted.

On that note, I've written up a [small guide](https://www.gbif.org/tool/81747/rgbif#citations) for citing data obtained using rgbif. I'd appreciate your comments, if you have moment.

**Comment by sckott** [comment]
Good point about specific records within datasets. 

I will have a look at that guide. 

I noticed that for some download Ids there is no DOI, eg., http://api.gbif.org/v1/occurrence/download/0000066-140928181241064  This is an older one (see the date), so I imagine DOIs weren't applied to downloads then?  In these cases, I can just pass and give back citations for the individual datasets ...

**Comment by sckott** [comment]
Or, in the case where no DOI is found, I could give the citation without DOI, but with URL for the download on GBIF's site? 

> GBIF Occurrence Download <https://www.gbif.org/occurrence/download/0000066-140928181241064> accessed via GBIF.org on \<created\>

**Comment by sckott** [comment]
pushed a change. here's an example of what it looks like:


```r
gbif_citation(d1)
#> $download
#> [1] "GBIF Occurrence Download https://doi.org/10.15468/dl.yghxj7 Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2017-10-20"
#> 
#> $datasets
#> $datasets[[1]]
#> <<rgbif citation>>
#>    Citation: Grant S, Jones J (2017). Field Museum of Natural History (Zoology)
#>         Invertebrate Collection. Version 18.6. Field Museum. Occurrence Dataset
#>         https://doi.org/10.15468/6q5vuc accessed via GBIF.org on 2017-10-20..
#>         Accessed from R via rgbif (https://github.com/ropensci/rgbif) on
#>         2017-10-20
#>    Rights: To the extent possible under law, the publisher has waived all
#>         rights to these data and has dedicated them to the Public Domain (CC0
#>         1.0). Users may copy, modify, distribute and use the work, including
#>         for commercial purposes, without restriction.
#> 
#> $datasets[[2]]
#> 
#> ... and so on
```

with DOI as a URL. That sound good?

**Comment by sckott** [comment]
@dnoesgaard   Some  feedback on the citation guide:

* can you make `gbif_citation` italics like you did for `occ_search`  ?
* usage of `gbif_citation`: in addition to getting citations from dataset key, occurrence key, and results of `occ_search`, users can pass results of `occ_download_get` as well (that is the fxn to fetch a download to the users machine). I mean to add more ways to use `gbif_citaiton` as well, so may ask for updates on that text later. 
* there's some unicode issues in the examples: replace with 

```
Citation: Moeslund J E (2016). Vegetation data from protected areas in
        Denmark (§ 3 in the Danish Nature Protection Act). Version 8.1.
        Department of Bioscience, Aarhus University. Occurrence Dataset
        https://doi.org/10.15468/ar7pbr accessed via GBIF.org on 2017-10-20..
        Accessed from R via rgbif (https://github.com/ropensci/rgbif) on
        2017-10-20
```

```
[[1]]
<<rgbif citation>>
   Citation: Baagøe H J, Secher Jensen T, Calabuig I (2016). Atlas of Danish
        Mammals. Danish Biodiversity Information Facility. Occurrence Dataset
        https://doi.org/10.15468/r2kvnz accessed via GBIF.org on 2017-10-20..
        Accessed from R via rgbif (https://github.com/ropensci/rgbif) on
        2017-10-20
   Rights:

[[2]]
<<rgbif citation>>
   Citation: Museum für Naturkunde Berlin. MfN - Fossil vertebrates IV.
        Occurrence Dataset https://doi.org/10.15468/kneffk accessed via
        GBIF.org on 2017-10-20.. Accessed from R via rgbif
        (https://github.com/ropensci/rgbif) on 2017-10-20
   Rights:
```

We have a preprint on rgbif/pygbif/gbifrb at https://doi.org/10.7287/peerj.preprints.3304v1 , if you could also use the citation 

> Chamberlain, S. A., & Boettiger, C. (2017). R Python, and Ruby clients for GBIF species occurrence data (Version 1). PeerJ Preprints. https://doi.org/10.7287/peerj.preprints.3304v1

and we've submitted that PeerJ for peer review as well, so will have an updated citation some day

**Comment by dnoesgaard** [comment]
Thanks Scott, sorry for the delay, that looks perfect. Can I download the updated library from this repo so as to test it myself?

I will incorporate the suggested changes to the citation guide. Thanks!

**Comment by dnoesgaard** [comment]
Perhaps the occ_download_meta function could also return the DOI (and maybe a suggested citation)?

**Comment by sckott** [comment]
Yes, you can install the latest version like `devtools::install_github("ropensci/rgbif")`

> Perhaps the occ_download_meta function could also return the DOI (and maybe a suggested citation)?

I'll look into that

**Comment by sckott** [comment]
@dnoesgaard added support for passing output of `occ_download_meta()` to `gbif_citation()` - can reinstall like above

Anything else to add here?

**Comment by sckott** [comment]
considering this good for now - can make changes as needed if issues arise.
