### ISSUE TITLE
How can I download all species in a certain area, one occurence dataset only per species? (presence/absence)

### ISSUE THREAD

**Issue by andzandz11** [ropensci/rgbif#277]
I want a list of all plant species that have a GPS record in Germany. How can I do that without downloading all occurence datasets and reduce them locally? That would take far too long, because it is too many records.
Thanks!

So basically only download the species names and species key, like this table without the occurences:
https://www.gbif.org/occurrence/species?basis_of_record=OBSERVATION&basis_of_record=PRESERVED_SPECIMEN&basis_of_record=LIVING_SPECIMEN&basis_of_record=HUMAN_OBSERVATION&taxon_key=6&advanced=1&geometry=POLYGON%20((4.21875%2044.93992412155162,%204.21875%2054.85637974835819,%2016.875%2054.85637974835819,%2016.875%2044.93992412155162,%204.21875%2044.93992412155162))&geometry=POLYGON%20((3.8671874999999996%2046.17678830513109,%203.8671874999999996%2055.41404977631955,%2016.5234375%2055.41404977631955,%2016.5234375%2046.17678830513109,%203.8671874999999996%2046.17678830513109))

I can not register on GBIF and download the data because every time I try to register I get the error: Invalid or insufficient information provided

**Comment by sckott** [comment]
Thanks for your question. 

you can do a facet query like 

http://api.gbif.org/v1/occurrence/search?facet=speciesKey&speciesKey.facetLimit=5&limit=0&country=BE

and can do that in `rgbif` as well

does that help?

**Comment by andzandz11** [comment]
Oh wow cool, I did read the rgbif .pdf file but obviously I did not understand the full power of this command.
That also solves my 2nd question, because there is no more need for it. Thanks!
