### ISSUE TITLE
Mass download speedup

### ISSUE THREAD

**Issue by andzandz11** [ropensci/rgbif#278]
I want to download 1 Mio occurence datasets. Looking at my network monitor it seems one "bundle" is downloaded every 3.5 seconds (1.5sec nothing 1sec 5Mb/s 1sec nothing -> repeat). How many datasets does one bundle contain?
Overall it seems a bit slow, I basically have unlimited internet speed and the download processing by R slows everything down quite a bit. It is possible to implement a parallel package here? Can GBIF handle this? I am on a cloud with 64 vCPU.
Thanks!

**Comment by sckott** [comment]
Thanks for your question @andzandz11 - i have some clarifying questions for you

- does "Mio" mean "million"?
- What is a bundle?  
- You haven't said what function(s) you are talking about

That's great that you can do things quickly, though you should consider being nice to GBIF's servers. It is a free service after all. 

We don't implement any parallel processing in the package, you can do that yourself easily. 

You can use their download service which we have fxns for here to download in bulk, though you can only have 3 of those running at once.

**Comment by andzandz11** [comment]
A bundle is if my network monitor shows a spike and 0% before and after that.
I have been finally able to register. I was not able to register because my official email adress contains 3 "." and 1 "-", but my private email worked.
