### ISSUE TITLE
Automate pagination across package?

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#281]
raised by a user - and others probably

Right now we auto-paginate using a `while` loop in just `occ_search` and `occ_data`. 

I (think?) it'd be okay to roll out across the pkg, but i'd want to make a standard implementation across functions so behavior is the same for users, and fixes to pagination happen in one place. 

will have a play and see how it goes

**Comment by peterdesmet** [comment]
I’d upvote that! Although it’s rather straightforward to paginate outside rgbif, it would be nice if you could more or less forget about it and have the package do it for you. 😬

**Comment by sckott** [comment]
thanks @peterdesmet for the note. i imagine many users of this pkg lean on the side of paginating themselves being a big PITA, so i'm sure people would like it. 

I do worry a bit that this will put a larger load on GBIF's servers since any request with this implemented would then get **all results** - but perhaps its worth a parameter that toggles `all` vs. `some` (current defaults)

**Comment by peterdesmet** [comment]
Yeah, I think such a `some` / `all` parameter would be useful. In fact, it could be implemented in the  `limit` parameter. It would retain its current default behaviour of `100` (sparing GBIF servers a bit) and option to choose a higher integer... but adding to functionality to set it to `all`, which would trigger automatic paging?

**Comment by sckott** [comment]
Right - could be worked into the `limit` parameter. 

I'm not sure if there's a hard limit (like there is for `/occurrences` at 200K) on other routes - trying to get some more clarification on limits form them now :) Unless you know?

(p.s. @peterdesmet do you think the python folks would want automated paging in the python client? or is that more of an audience that would want to do that themselves? )

**Comment by peterdesmet** [comment]
Don't know about other limits set by GBIF, so good to ask. For reference, here are all the endpoints that use paging. I just searched for paging=true (and discovered [some that probably are](https://github.com/gbif/portal-feedback/issues/712)):

## Registry

```
/dataset
/dataset/{UUID}/constituents
/dataset/deleted
/dataset/duplicate
/dataset/withNoEndpoint
/dataset/search
/installation
/installation/{UUID}/dataset
/installation/deleted
/installation/nonPublishing
/organization
/organization/{UUID}/hostedDataset	
/organization/{UUID}/publishedDataset
/organization/{UUID}/installation
/organization/deleted
/organization/pending
/organization/nonPublishing
/node
/node/{UUID}/organization
/node/pendingEndorsement
/node/{UUID}/pendingEndorsement
/node/{UUID}/dataset
/node/{UUID}/installation
/network
/network/{UUID}/constituents
```

## Species

```
/species
/species/root/{uuid|shortname}
/species/{int}/children
/species/{int}/synonyms
/species/{int}/related
/species/{int}/combinations
/species/{int}/descriptions
/species/{int}/distributions
/species/{int}/media
/species/{int}/references
/species/{int}/speciesProfiles
/species/{int}/vernacularNames
/species/{int}/typeSpecimens
/species/search
```

## Occurrence

```
/occurrence/search
/occurrence/download
/occurrence/download/user/{user}
/occurrence/download/dataset/{datasetKey}
```

For Python folks: it would be nice of course, but wouldn't necessarily do it for rgbif and pygbif at the same time if that would postpone things. 😄

**Comment by sckott** [comment]
awesome, thanks for this @peterdesmet 

still no answer from GBIF on what default and max values are for paging - will just trial and error I guess
