### ISSUE TITLE
occ_download with multiple taxonKeys inconsistency?

### ISSUE THREAD

**Issue by poldham** [ropensci/rgbif#283]
Dear Scott, 

When spinning up an occ_download this example works as expected. 

`occ_download('taxonKey = 3119195', user = Sys.getenv("GBIF_USER"))`

However, I think when entering multiple taxonKeys the behaviour seems inconsistent. 

For example, running the occ_download complex example as is works. But if shortened to: 

`occ_download("taxonKey = 2480946,5229208", user = Sys.getenv("GBIF_USER"))`

returns `Error: Bad Request HTTP 400`

I then tried: 

`res <- occ_download("taxonKey = 2480946,5229208", "basisOfRecord = HUMAN_OBSERVATION,OBSERVATION,MACHINE_OBSERVATION")`

That works. That suggests that for multiple taxonKeys some extra args have to be added? 

Best, 

Paul

**Comment by sckott** [comment]
hugh, don't know off the top. will look into it

**Comment by sckott** [comment]
@poldham  think i fixed it. can you reinstall and try again `remotes::install_github("ropensci/rgbif")`. sorry it took me a while to get around to this
