### ISSUE TITLE
name_usage() does not work with vector of datasetKeys

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rgbif#287]
session info as attachment:
[sessionInfo.txt](https://github.com/ropensci/rgbif/files/1700085/sessionInfo.txt)

I noticed an anomalous behavior while using RGBIF's function `name_usage()`with `datasetKey` equal to a character vector. Trying to run the code here below:
```r
test1 <- name_usage(datasetKey = "73605f3a-af85-4ade-bbc5-522bfb90d847")
test2 <- name_usage(datasetKey = "d7c60346-44b6-400d-ba27-8d3fbeffc8a5")
test3 <- name_usage(datasetKey = c("73605f3a-af85-4ade-bbc5-522bfb90d847",
                                   "d7c60346-44b6-400d-ba27-8d3fbeffc8a5"))
test4 <- name_usage(datasetKey = c("d7c60346-44b6-400d-ba27-8d3fbeffc8a5",
                                   "73605f3a-af85-4ade-bbc5-522bfb90d847")) #invert order datasetKeys
c(nrow(test1$data), nrow(test2$data), nrow(test3$data), nrow(test4$data))
c(unique(test1$data$datasetKey), unique(test2$data$datasetKey), 
  unique(test3$data$datasetKey), unique(test4$data$datasetKey))
```

I got this:
```r
c(nrow(test1$data), nrow(test2$data), nrow(test3$data), nrow(test4$data))
```
```
10  7 10 10
```
```r
unique(test1$data$datasetKey) 
[1] "73605f3a-af85-4ade-bbc5-522bfb90d847"
unique(test2$data$datasetKey)
[1] "d7c60346-44b6-400d-ba27-8d3fbeffc8a5"
unique(test3$data$datasetKey)
[1] "73605f3a-af85-4ade-bbc5-522bfb90d847"
unique(test4$data$datasetKey)
[1] "73605f3a-af85-4ade-bbc5-522bfb90d847"
```

while I was expecting this:
```r
c(nrow(test1$data), nrow(test2$data), nrow(test3$data), nrow(test4$data))
```
```
10  7 17 17
```
```r
unique(test1$data$datasetKey) 
[1] "73605f3a-af85-4ade-bbc5-522bfb90d847"
unique(test2$data$datasetKey)
[1] "d7c60346-44b6-400d-ba27-8d3fbeffc8a5"
unique(test3$data$datasetKey)
[1] "73605f3a-af85-4ade-bbc5-522bfb90d847", "73605f3a-af85-4ade-bbc5-522bfb90d847"
unique(test4$data$datasetKey)
[1] "73605f3a-af85-4ade-bbc5-522bfb90d847", "73605f3a-af85-4ade-bbc5-522bfb90d847"
```
or maybe `test3` and `test4` as a list of two (one per dataset) each one with `$meta` and `$data`?

Moreover, I think documentation should be updated:
> uuid (character) A uuid for a dataset. Should give exact same results as datasetKey.

That is not/ no longer true:

- http://api.gbif.org/v1/species/search?datasetKey=73605f3a-af85-4ade-bbc5-522bfb90d847:
[sessionInfo.txt](https://github.com/ropensci/rgbif/files/1700082/sessionInfo.txt)
 correct behaviour
- http://api.gbif.org/v1/species/search?uuid=73605f3a-af85-4ade-bbc5-522bfb90d847: return everything, and thus seems no longer supported as a parameter

Thanks for the support

**Comment by sckott** [comment]
thanks @damianooldoni i'll have a look

**Comment by sckott** [comment]
So the results coming back from this function seems like a bug, i think on GBIF's side, will contact them. 

Yes, you're right that seems like `uuid` is no longer supported. Will udpate the docs.

**Comment by sckott** [comment]
@damianooldoni looks like https://github.com/gbif/checklistbank/issues/54 they will change behavior to not allow more than 1 instance of a parameter, so to get data for multiple datasetkeys, user will have to lapply or similar

doesn't look like API is updated quite yet with new behavior

**Comment by damianooldoni** [comment]
Thank you very much, @sckott! Actually using sapply or similar is not a problem at all. And it 's good to know the reason of that strange behavior.

**Comment by sckott** [comment]
glad an sapply or so workflow is doable. we do loop internally in other functions, but it introduces a lot more chance for bugs and is harder to maintain so i prefer not to

**Comment by damianooldoni** [comment]
Yes, you are right. I understand it perfectly.
