### ISSUE TITLE
Add "origin" parameter to name_lookup()

### ISSUE THREAD

**Issue by peterdesmet** [ropensci/rgbif#288]
If you query taxa from a checklist:

https://api.gbif.org/v1/species/search?dataset_key=289244ee-e1c1-49aa-b2d7-d379391ce265

```r
names <- name_lookup(datasetKey = "289244ee-e1c1-49aa-b2d7-d379391ce265", limit = 500)
names$data
```

You get 139 results, while the [checklist only has 73](https://www.gbif.org/dataset/289244ee-e1c1-49aa-b2d7-d379391ce265). That is because GBIF denormalizes the classification for a checklist, creating a taxon for each unique value in `kingdom`,  `phylum` etc. (which is pretty neat). Luckily, the API provides a parameter `origin` to only return the source taxa:

https://api.gbif.org/v1/species/search?dataset_key=289244ee-e1c1-49aa-b2d7-d379391ce265&origin=SOURCE

Giving the expected 73 results. It is also available as a [search option on the left](https://www.gbif.org/species/search?dataset_key=289244ee-e1c1-49aa-b2d7-d379391ce265&origin=SOURCE&advanced=1).

The parameter is currently [undocumented](https://www.gbif.org/developer/species), but it seems the [accepted values](https://www.gbif.org/species/search?advanced=1) (open origin option on the left) are:

```
SOURCE
DENORMED_CLASSIFICATION
VERBATIM_ACCEPTED
EX_AUTHOR_SYNONYM
AUTONYM
BASIONYM_PLACEHOLDER
MISSING_ACCEPTED
IMPLICIT_NAME
PROPARTE
VERBATIM_BASIONYM
```

Our use case demands to search for `SOURCE` taxa only and it's easy to filter the data we get from `name_lookup()`, but since it is a GBIF API parameter, it seems better to have it as a parameter in `name_lookup()`, so it is available all rgbif users.

**Comment by sckott** [comment]
@peterdesmet Yes! this sounds good, please do send a PR - should I ask them to please document the parameter?

**Comment by peterdesmet** [comment]
Having it documented would be good indeed, including a link to the enum they use. 👍

**Comment by sckott** [comment]
will do

**Comment by damianooldoni** [comment]
@peterdesmet , @sckott , I put it on my to-do-list with pleasure. I will add the parameter in rgbif on my fork and send afterwards a PR for evaluation and upgrade. Stay tuned :+1:

**Comment by sckott** [comment]
any word on this? no rush

**Comment by damianooldoni** [comment]
Still no word on it. A lot of planned and unplanned stuff. 
I hope to do it very soon!

**Comment by damianooldoni** [comment]
While working on it, I found the following asymmetric behavior of GBIF API:

1. [https://api.gbif.org/v1/species/search?offset=0&limit=1&origin=SOURCE&datasetKey=289244ee-e1c1-49aa-b2d7-d379391ce265]() works fine
2. [https://api.gbif.org/v1/species?offset=0&limit=1&origin=SOURCE&datasetKey=289244ee-e1c1-49aa-b2d7-d379391ce265]() doesn't work as expected: parameter `origin` is not taken into account 

Does somebody have an idea about this inconsistency in GBIF API?

For this reason, I am now implementing `origin` on `name_lookup()` but not in `name_usage()`.

**Comment by damianooldoni** [comment]
See PR #293

**Comment by sckott** [comment]
i assume #293 fixes this @damianooldoni ?

**Comment by damianooldoni** [comment]
I think so. Last word to @peterdesmet about it.

**Comment by peterdesmet** [comment]
Tested: works!
