### ISSUE TITLE
Fixes for reading GBIF downloads data

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#292]
this dataset http://api.gbif.org/v1/occurrence/download/0016851-180131172636756 has 2,315,665 records

```r
z <- as.download("~/Downloads/0016851-180131172636756.zip")
z
#> <<gbif downloaded get>>
#>   Path: ~/Downloads/0016851-180131172636756.zip
#>   File size: 952.69 MB
```

`data.table::fread` gives 1,178,112

```r
x <- occ_download_import(z, blank.lines.skip=TRUE)
# A tibble: 1,178,112 x 235
```

and `readr::read_tsv` gives 1,431,934 records

**Comment by fischhoff** [comment]
fread is able to read in all the lines of the occurrence.txt file.

test = fread("occurrence.txt",blank.lines.skip=TRUE)
Read 2315665 rows and 235 (of 235) columns from 2.190 GB file in 00:00:57
Warning message:
In fread("occurrence.txt", blank.lines.skip = TRUE) :
  Bumped column 79 to type character on data row 243214, field contains 'MANAGED'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses a sample of 1,000 rows (100 rows at 10 points) so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.

**Comment by sckott** [comment]
seems to work now, I added a param `fill` to `occ_download_import()`  because with newest `data.table` was getting segfaults reading it, but not with `fill=FALSE`
