### ISSUE TITLE
Issues with gbifmap function

### ISSUE THREAD

**Issue by jkmccarthy** [ropensci/rgbif#301]
I am having trouble with the gbifmap function. Hopefully I am not doing something stupid, but the following code does not seem to work:

    key <- name_backbone(name='Puma concolor')$speciesKey
    dat <- occ_search(taxonKey=key, return='data', limit=100)
    gbifmap(dat)

I get the following error message:
`Error in .C(C_map_type, as.character(mapbase), integer(1)) : 
  Incorrect number of arguments (2), expecting 593896856 for 'waterBody'`

Note that this is the example code given for the function in the rgbif Reference Manual, and at the bottom of the rgbif tutorial:
https://ropensci.org/tutorials/rgbif_tutorial/

EDIT: I just saw that this function is in the process of being decommissioned (issues #298 and #296 ). Can anyone of the best replacement? I see that there are options in the `mapr` package, (e.g. `map_ggmap()`, via the `ggmap` package).

**Comment by sckott** [comment]
thanks for your question @jkmccarthy  - that eg does work for me, but there's any number of reasons why it may not work for you. it looks like some error in the `ggplot2` mapping part, but not sure. 

yes, you're correct that we are removing the function from the package soon. 

we do recommend using `mapr`, which has many different map output options (base plots, ggplot2, leaflet, ggmap, etc.) and works with many different inputs (from this pkg, from `spocc`, from `dismo`)  - Can you tell me if `mapr` works for you?

**Comment by jkmccarthy** [comment]
Thanks very much for the response, @sckott. You're right, it seemed to be a `ggplot2` issue. I reinstalled the package and updated RStudio and all is running well now. `mapr` works fine.

Thanks for your help narrowing down the issue.
