### ISSUE TITLE
Package/repo title & consistency

### ISSUE THREAD

**Issue by peterdesmet** [ropensci/rgbif#323]
I noticed that the official title of rgbif (from the `DESCRIPTION`) is:

> Interface to the Global 'Biodiversity' Information Facility API

Questions:

- Why is 'Biodiversity' in parenthesis? I also noticed it for other packages:

        'NOAA' Weather Data from R
        Access 'Nomis' UK Labour Market Data

- Would it make sense to update the repo title (currently "Wrapper to the Global Biodiversity Information Facility API") to the title? I noticed this type of consistency is rather rare for rOpenSci packages though. 😄 
- As there any guidance how to title packages that provide access? I've seen a bunch of formats:

        Access foo
        Access to data from foo
        Download data from foo
        Interface to foo
        R client for foo
        R interface to foo
        Wrapper for foo

**Comment by sckott** [comment]
thanks for this @peterdesmet 

The quoting comes from the CRAN submission process. They have some sort of spell checker and so we quote words we think their spell checker won't know. This is unfortunate, but unavoidable for now. 

> Would it make sense to update the repo title (currently "Wrapper to the Global Biodiversity Information Facility API") to the title

do you mean make this github repo title and the title in `DESCRIPTION` the same?  if so, which do you like better?

No, we don't have any opionion on formats for package titles. One thing we have to avoid in the titles in `DESCRIPTION` files is using `R` in the title as the CRAN maintainers don't like that. Other than that, no opinion. Do you have any ideas on a good format?

**Comment by peterdesmet** [comment]
> do you mean make this github repo title and the title in DESCRIPTION the same? if so, which do you like better?

Yes. I like the DESCRIPTION one better (but without the weird quotes):

> Interface to the Global Biodiversity Information Facility API

Regarding consistency over packages and between repo and DESCRIPTION title:

- Not mentioning R makes sense for both DESCRIPTION and the repo titles. There are other ways to indicate something is an R package on GitHub (shortname, tags, language)
- I quite like “Interface to foo” as it leaves the functionality more open (and potentially bidirectional) than “Download data from foo”, but it sounds more techy. Best to ask others too.
- In any case, I think it might be good to aim naming the repo = DESCRIPTION title, but that’s also because I like consistency. :smile:

**Comment by sckott** [comment]
I'm happy to change the repo title to match the DESCRIPTION file title. I think i agree that "interface to" sounds best.

**Comment by sckott** [comment]
repo title changed to match the DESCRIPTION `Title`
