### ISSUE TITLE
name_usage() returns more rows per single taxon

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rgbif#324]
The function `name_usage()` returns sometimes multiple rows. 
Example, key 8421432:
```r
example_duplicate <- name_usage(key = 8421432, return ="data")
> nrow(example_duplicate)
[1] 2
```
This is due to the presence of multiple issues:
```r
> example_duplicate$issues
[[1]]
[1] "ORIGINAL_NAME_DERIVED"

[[2]]
[1] "NAME_PARENT_MISMATCH"
```
This is quite strange, because I think everyone would expect to have one row per taxon. Why not dump all issues in one value, e.g. comma separated value? Something like this:
```r 
example_duplicate$issues
"ORIGINAL_NAME_DERIVED,NAME_PARENT_MISMATCH"
```
This solution is not tidy but way more intuitive to use. The issues are also vocabulary-based so it would be not such a big problem to filter using `contain`-like functions, e.g. `stringr::str_detect()` or older `stringi::stri_detect_fixed()` or other similar functions.

If still being 100% tidy is a must, why issues are given as list instead of character if they are still returned one by one? I would then expect:
```r
> example_duplicate$issues
[1] "ORIGINAL_NAME_DERIVED"  
[2] "NAME_PARENT_MISMATCH"
```
as it is the case for `scientificName` for example:
```r
example_duplicate$scientificName
[1] "Cornus sanguinea subsp. hungarica (Karpati) Soo"
[2] "Cornus sanguinea subsp. hungarica (Karpati) Soo"
```

**Comment by sckott** [comment]
thanks @damianooldoni 

right, was aware of this. 

turns out GBIF has name issues now - i need to add parsers for name issues

**Comment by sckott** [comment]
@damianooldoni reinstall and try again - added https://github.com/ropensci/rgbif/blob/master/R/name_issues.R to help parse issues

**Comment by sckott** [comment]
nice example. Would you prefer to have the complete code names? rather than the short codes

similarly I return short codes for occurrence issues in `occ_data`/`occ_search`.  Would you like something like this for `name_usage`:

```r
# from the occ_data eg.s
(res <- occ_data(geometry='POLYGON((30.1 10.1, 10 20, 20 40, 40 40, 30.1 10.1))', limit = 50))

### remove data rows with certain issue classes
library('magrittr')
res %>% occ_issues(gass84)
### split issues into separate columns
res %>% occ_issues(mutate = "split")
### expand issues to more descriptive names
res %>% occ_issues(mutate = "expand")
### split and expand
res %>% occ_issues(mutate = "split_expand")
### split, expand, and remove an issue class
res %>% occ_issues(-cudc, mutate = "split_expand")
```

**Comment by damianooldoni** [comment]
Well, that would be great! 
I think that maintaining the symmetry between checklist and occurrence functions (where possible) is welcome.

**Comment by damianooldoni** [comment]
I have just checked the mentioned `occ_issues()`. If you agree I will work on it in my fork and I will apply a PR when done. Good luck with CRAN submission :crossed_fingers:

**Comment by sckott** [comment]
okay, thanks. @damianooldoni this issue is fixed for now so i'll close it. Can you open a new issue for the new functionality discussed
