### ISSUE TITLE
introduce parsing errors functionality for checklist data

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rgbif#326]
# Goal 

As discussed with @sckott in #324, in this issue we will discuss the introduction of a functionality similar to `occ_issues()` which would work on checklist related issues instead of occurrence's ones. I will implement the functionality on my fork and I will submit a PR at the end.

# Implementation

Inspired by `occ_issues()` and gbif_issues()´ I would proceed as follows:
1. merge the table defined in `rgbif::name_issues()` in `gbif_issues()`
2. use `name_issues()` as the function for implementing the parsing, thus being the exact counterpart of `occ_issues()`

# Example 

Inspired by https://github.com/ropensci/rgbif/issues/324#issuecomment-427909944, I would say it would be useful to implement something like this:

```r
name_data <- name_usage(
    datasetKey = "9ff7d317-609b-4c08-bd86-3bc404b77c42",
    limit = 99999, # Should be more than total taxa
  )
### remove checklist data rows with certain issue classes
library('magrittr')
name_data %>% name_issues(npm)
### split issues into separate columns
name_data %>% name_issues(mutate = "split")
### expand issues to more descriptive names
name_data %>% name_issues(mutate = "expand")
### split and expand
name_data %>% name_issues(mutate = "split_expand")
### split, expand, and remove an issue class
name_data %>% name_issues(-npm, mutate = "split_expand")
```

Does it sound reasonable for you, @sckott ? 
Thanks!

**Comment by sckott** [comment]
thanks for this @damianooldoni 

> 1. merge the table defined in rgbif::name_issues() in gbif_issues()

not sure I follow here, can you clarify?

For 2 that sounds good. Though I think we should rename the current `name_issues` to something else so that we can use `name_issues` for the equivalent function of `occ_issues`. 

Making the interface for `name_issues` the same as `occ_issues` makes sense to me

**Comment by damianooldoni** [comment]
Yes, sorry, I made a mistake :disappointed: 
I try again...
I see that `nameissues` is a list of _name_ related issues, while `gbifissues` a list of _occurrence_ related issues.  Why don't merge the two lists in one list? `gbifissues` would be the prefect name for it, as it would contain all possible (GBIF) issues. In this way, the function `gbif_issues` replaces the current `name_issues` and no need for another name.

**Comment by sckott** [comment]
good idea, but name issues wouldn't be needed for occurence data and occurrence issues wouldn't be needed in name usage data, correct? or is that wrong?

**Comment by damianooldoni** [comment]
Yes, my idea was to merge them in a unique list with name `gbifissues`. This would prevent double hardcoding if common issues will be introduced in the future, though a very unlikely event. The name `gbifissues` would be perfect for such a comprehensive list. By reading  the Roxygen description in `gbif_issues.R` I see that you thought to have a list with all GBIF issues in it: no reference to occurrence data is present. Actually, your documentation triggered immediately the idea of having a unique list for all GBIF issues. Do you think that having a big list would make issues parsing much slower?

If we stay for two separate lists, I would suggest to modify the names `gbifissues` and `gbif_issues` because they are actually referring to occurrence issues, not all GBIF issues. Maybe `nameissues_list` and `occissues_list` for the two lists? I agree to have an underscore `_` to distinguish the list from the wrapping functions and R files (so, in this case: `name_issues_list()`/`name_issues_list.R` and `occ_issues_list()`/`occ_issues_list.R`). In this way we can use `name_issues()` and `occ_issues()` as the two main issue parsing functions.

**Comment by sckott** [comment]
Okay, i think we can merge the occurrence and name issues in the one list. maybe check to make sure there aren't any duplicate `code` values - I came up with those manually, so there could be duplicates. if merging though is it worth adding a fourth column that says whether its an occurrence or name issue? I for one won't remember which each issue belongs to

**Comment by sckott** [comment]
@damianooldoni i need to submit a new version of `rgbif` to CRAN before next Tuesday. Do you think you will have this done by then? if not I'll go ahead and submit

**Comment by damianooldoni** [comment]
I try to do it today. I will let you know asap if the deadline is reasonable.

**Comment by damianooldoni** [comment]
@sckott , I think things are slightly more complicated than expected. See #328.
So, the probability to get it before Tuesday is quite low.

**Comment by damianooldoni** [comment]
Sorry. I have still not found time to work much further on this :disappointed:  I hope to find it during before or after Christmas holidays!

**Comment by sckott** [comment]
Okay, no worries

**Comment by damianooldoni** [comment]
This was the discussed implementation:

> Inspired by `occ_issues()` and `gbif_issues()´ I would proceed as follows:
> 1. merge the table defined in `rgbif::name_issues()` in `gbif_issues()`
> 2. use `name_issues()` as the function for implementing the parsing, thus being the exact counterpart of `occ_issues()`

First point is ok and it is done on my fork.
About the second: I see that the function `occ_issues()` works fine with names as well (after having solved #328). That's very nice, of course. However, the name `occ_issues()` is not the best one. My idea is to write a _dummy_ `name_issues()` which actually would look like this (pseudocode alike):
```r
name_issues <- function(.data, ..., mutate = NULL) {
 return(occ_issues(.data, ..., mutate = mutate))
}
```
@sckott : what do you think about?

**Comment by damianooldoni** [comment]
Another thing I encountered while trying to reproduce the behavior of occ_issues() while working with names: `occ_issues()` accepts data of class gbif, gbif_data, data.frame, tbl_df, while `name_usage()` and `name_lookup()` return a **list** (`return`parameter default equal to `all`). At first glance, while watching the structure of `gbif_data`, e.g. in function `occ_search()`([lines 228-237](https://github.com/ropensci/rgbif/blob/master/R/occ_search.r#L228)), I see that it could be easily applied to name search functions as well. The paging iteration has been implemented around one year ago so we have the `iter` variable to assess the value of `$type`.

@sckott : are there reasons to not assign `gbif_data` class to this kind of data? They are after all gbif data...

Alternatives: working only on `data` field of the list. See example of possible code here below:
```r
name_issues <- function(.data, ..., mutate = NULL) {
  if ((is.list(.data)) & ("data" %in% names(.data)) {
    data_in <- .data$data
    data_out <- occ_issues(data_in, ..., mutate = mutate)
    .data$data <- data_out
    return(.data)
  }
  else {
    return(occ_issues(.data, ..., mutate = mutate))
  }
```

**Comment by sckott** [comment]
For the dummy fxn name, if it's literally exactly the same you could do i think

```r
foo <- function(x) x^2
bar <- foo
```

**Comment by sckott** [comment]
The `gbif` S3 class on the output of `occ_search()` is primarily used for linking it's print method defined here https://github.com/ropensci/rgbif/blob/master/R/print_gbif.R - Same goes for `occ_data()`. The `gbif` class is not really special, it could be named anything, e.g., `bear`, `cheese`, etc. - it just has to match the `whatever` in  `print.whatever` 

I didn't assign S3 classes to name functions because I didn't think they were needed, but we can do that if it makes things easier

I like the `name_issues()` function you have in https://github.com/ropensci/rgbif/issues/326#issuecomment-451401789  

which name* functions will be able to go through `name_issues()`?

**Comment by damianooldoni** [comment]
Thanks. I just checked the print method of `gbif` S3 class of the output of a (slightly modified) `name_usage()` ((6c8d7b549569a88604978481d9112e72f5bdc16c)) and it works nice :+1: I am always very happy when I see reusable code. I have still to double check everything of course, but I am quite confident we can use S3 class for names as well.

About your question:
> which name* functions will be able to go through `name_issues()`?

the short answer is: only `name_usage()` at the moment as only this function returns issues! It is not a problem of `rgbif`, but it is a kind of choice (or bug) at GBIF level. Read further for the complete overview about the issues handling of each of the name* functions. We will use this taxon from GBIF Backbone Taxonomy as example in the links: *Acidianus ambivalens (Zillig & Böck, 1987) Fuchs & al., 1996* with key = 1000048. This taxon has an issue: `ORIGINAL_NAME_DERIVED`.

### name_usage
The issue can be retrieved by `name_usage()` as this function relies on [api.gbif.org/v1/species/](https://api.gbif.org/v1/species/1000048).

### name_lookup

name_lookup doesn't return any issue field, although issues could be exist. It relies on GBIF API [/species/search](https://api.gbif.org/v1/species/search?q=Acidianus%20ambivalens%20(Zillig%20&%20B%C3%B6ck,%201987)%20Fuchs%20&%20al.,%201996). Few days ago I wrote issue https://github.com/gbif/gbif-api/issues/37 about it. Still waiting an answer. Maybe you know more about it?

### name_backbone
`name_backbone()`: the gbif API doesn't return issues for [/species/match](https://api.gbif.org/v1/species/match?name=Acidianus%20ambivalens%20(Zillig%20&%20B%C3%B6ck,%201987)%20Fuchs%20&%20al.,%201996)

### name_suggest

No issues returned by name_suggest. Even in this case, it is not a problem of rgbif as no issues are returned by GBIF API [/species/suggest](https://api.gbif.org/v1/species/suggest?q=Acidianus%20ambivalens%20(Zillig%20&%20B%C3%B6ck,%201987)%20Fuchs%20&%20al.,%201996)

**Comment by damianooldoni** [comment]
Answering to your comment: https://github.com/ropensci/rgbif/issues/326#issuecomment-451570287
Yes, actually `occ_issues()` works perfectly on output of `name_usage()` (after working on assigning S3 class `gbif` to names of `name_usage()`).

So, my first idea was this:
```r
name_issues <- function(.data, ..., mutate = NULL) {
  return(occ_issues(.data = .data, ... = ..., mutate = mutate))
}
```` 
and it works fine, I have just tested it on my fork. However, why writing such function if it is a perfect duplicate of an existent function? Two possible solutions:
1. change name of `occ_issues()` in order to avoid the link to occurrences in the function name. Something like `issues()`?
2. `occ_issues()` accepts ONLY occurrence related issues, `name_issues()` accepts ONLY name related issues. Error is thrown otherwise. We can do it because you asked and I added column `type` to the table with all issues (variable `gbifissues`, see https://github.com/ropensci/rgbif/issues/326#issuecomment-429484953). In this way we maintain the distinction among `name_*` and `occ_*` functions and it will prevent users by filtering occurrences by name related issues and viceversa. 
@sckott: what do you think about?

**Comment by sckott** [comment]
Thanks for the breakdown of all the name functions. Looking forward to PR. 

I don't have any thoughts on https://github.com/gbif/gbif-api/issues/37#issue-395295698 - agree it would be nice to have. 

For the two solutions to function naming, which do you prefer?

**Comment by damianooldoni** [comment]
I prefer the second one for the reasons I wrote above.

**Comment by sckott** [comment]
Okay, I think i like the 2nd option better as well

**Comment by damianooldoni** [comment]
Just to let you know, @sckott, that I sent an internal PR to colleagues for a first internal review (see https://github.com/damianooldoni/rgbif/pull/1). 2019 is not less busy than 2018: we are doing our best.

**Comment by sckott** [comment]
sounds good ! no worries on timing
