### ISSUE TITLE
Parsing errors in name_usage() works only for single taxa

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rgbif#328]
The issues are not always returned in the same way from `name_usage()`. 

## with `key` parameter

```r
> single_key <- name_usage(key = 1040162, return ="data")$issues
> single_key
[1] "onder"
```
The code is given, as you fixed in #324.

## with `datasetKey` parameter

```r
> more_keys <- name_usage(
  datasetKey = "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c", 
  limit = 100,  
  start = 40000,
  return = "data")
> (more_keys %>% filter(key == 1040162))$issues
[[1]]
[1] "ORIGINAL_NAME_DERIVED"
```
Old school list of issues are returned, no codes in a string with comma as separator.

So, the parsing doesn't occur if more taxa are read from checklist.

Something like this from `zzz.R` (see [here](https://github.com/ropensci/rgbif/commit/2cb0d11f5cdbacc8572dace05355af36f5ffe3cf#diff-434efa1e44ee83a15481ea98901eaaefR303)) should be added, I think. I can try to fix it, but I am not sure to get it before Tuesday.

**Comment by sckott** [comment]
Okay, that line in zzz seems like it would work. I'll go ahead and submit to CRAN as I don't want to risk rgbif being taken off CRAN. We can submit a new patch version soonish with this and any other fixes that can be done

**Comment by damianooldoni** [comment]
I got it in my fork. Waiting to solve #326 as well before PR.
