### ISSUE TITLE
Hex logo

### ISSUE THREAD

**Issue by peterdesmet** [ropensci/rgbif#331]
Hi @sckott, I'd like to create a [hex logo](http://hexb.in/) for the rgbif package, so it can be included in the README, pkgdown website (if there is one) and even ordered as stickers to share our love for this package. 😄I think the most straightforward approach would be to use the GBIF colours and [logo](https://www.gbif.org/logos). I'm just wondering if the name in the logo should be:

- **gbif.org**: as included in all GBIF logos except one. Points viewers to GBIF itself (not unuseful), but gives less focus to the package
- **rgbif**: name of package. Only green part of GBIF logo would then be used, but that might be OK. I could even try to have the font for `rgbif` match the GBIF font.

What do you think?

**Comment by sckott** [comment]
Thanks @peterdesmet !

I guess if it says **gbif.org** then people would assume it was a GBIF sticker, which is okay, but maybe we can do both?  e.g, have **rgbif** as the bigger text, and have gbif.org somewhere on the sticker? matching font sounds good

**Comment by sckott** [comment]
are they okay with their logo being used in the sticker?

**Comment by peterdesmet** [comment]
I’ll ask them. Would have to see if I can include both: the logos end up quite smallish for text.

**Comment by dnoesgaard** [comment]
We love rgbif too–and of course the logo can be used. We prefer it if the logo isn't changed though. Might we get to see what you had in mind? (cc @kcopas)

**Comment by peterdesmet** [comment]
Hi @dnoesgaard @kcopas, you beat me to it in contacting you. 😊I have something like this in mind:

![rgbif](https://user-images.githubusercontent.com/600993/48468505-5ccc6f80-e7ec-11e8-8255-811b1eb3e5e6.png)

But rather than `GBIF.org`, I would want it to say `rgbif` (lowercase), ideally in the same font. Would that be acceptable? Note: the size of the logo above is the (max) size it would have on web pages.

**Comment by sckott** [comment]
Looks good @peterdesmet

**Comment by peterdesmet** [comment]
Version with correct font and text. Font size is slightly larger than original to make it more readable. Margin between logo and font is the same. Let me know what you think. If 👍I'll submit as PR. 

![rgbif_3](https://user-images.githubusercontent.com/600993/48848673-d5ab6880-eda4-11e8-85c8-7000a1a21be5.png)

**Comment by sckott** [comment]
@peterdesmet I like it!

**Comment by peterdesmet** [comment]
@sckott just tried one more alternative version (previous comment), allowing a slightly bigger logo. Deviates more from official GBIF logo, so not sure we should go that way.

**Comment by sckott** [comment]
I like both. I guess the only way version 2 deviates is that the logo is rotated?

the only argument I can think of against version 2 is that most people place stickers upright and so in version 1 the `rgbif` is upright, where in version 2 its rotated a bit - i like version 2, but I think only in addition to version 1, or just version 1 😄

**Comment by peterdesmet** [comment]
> I guess the only way version 2 deviates is that the logo is rotated?

Well, the text yes. And a bigger icon. 🤓I agree that if version 2 is your first hex sticker, you might be inclined to place it with the edge rather than the corner at the bottom, messing up any future placement of hex stickers. 😱Clearly we don't want that, so let's stick to version 1. 😂

@dnoesgaard @kcopas can I have a go ahead from @gbif for version 1 in https://github.com/ropensci/rgbif/issues/331#issuecomment-440689798?

**Comment by kcopas** [comment]
Approved—thanks!

**Comment by peterdesmet** [comment]
For reference, here's the logo in 300dpi:

![rgbif](https://user-images.githubusercontent.com/600993/49224326-76230d80-f3e1-11e8-8e5b-5be22ec0e6de.png)
