### ISSUE TITLE
Create rgbif pkgdown website

### ISSUE THREAD

**Issue by peterdesmet** [ropensci/rgbif#336]
👋 @sckott I think it would be nice if rgbif has a [pkgdown](https://pkgdown.r-lib.org/) website, so users (including myself 😬) have a nice overview of the package, functions, vignettes and changelog. The [occurrence manual](https://ropensci.github.io/occurrence-manual/) (currently linked as the pkg website) doesn't cover that, but would be a good resource to reference from the website.

If you agree, I can set this up. We have done this before for https://ropensci.github.io/wateRinfo/ and http://adokter.github.io/bioRad/

**Comment by sckott** [comment]
hi, sounds good if you're willing to do it
