### ISSUE TITLE
GBIF API is broken when using bounding box

### ISSUE THREAD

**Issue by sacrevert** [ropensci/rgbif#340]
Just FYI. 
https://github.com/gbif/portal-feedback/issues/1769

**Comment by sckott** [comment]
thanks. I'd like to see the code that was tried. Is best practice to email the person to get more information?

**Comment by MortenHofft** [comment]
The polygon is invalid. See more at https://github.com/gbif/portal-feedback/issues/1769#issuecomment-460778639

**Comment by sckott** [comment]
thanks, makes sense. 

I've built a geometry/wkt check into functions that work with the `/occurrence/search` route, but not for the download route functions. 

The problem we're having is that we're using an R client wrapping the C++ Boost::Geometry library, and when we use it's geometry validate method it flags WKT that is correct for GBIF as the wrong winding order. So it's not ideal

**Comment by sckott** [comment]
@sacrevert @MortenHofft It seems that the handling of WKT is different for `/occurrence/search` vs. `/occurrence/download/request`, correct?

for example, queries to the search route with the same invalid WKT go through but do not go through on the download route. 

for now, i'll add to the docs for the download methods wording about checking geometry input and winding order and how to fix with R tools.

**Comment by MortenHofft** [comment]
Yes, seems you are correct. The `/occurrence/search` route is more forgiving apparently. But not always: e.g. this clockwise winded gives semi reversed results https://www.gbif.org/occurrence/map?has_geospatial_issue=false&geometry=POLYGON((-3.63922%2040.86576,-3.63922%2046.99149,7.44598%2046.99149,7.44598%2040.86576,-3.63922%2040.86576))

**Comment by sckott** [comment]
thanks @MortenHofft - i do remember something about this, maybe this is correct: 

that if the ring is clockwise, that means the ring is excluding the area within it rather than including only the area within it.  

e.g., https://github.com/gbif/portal-feedback/issues/1251#issuecomment-391997038
