### ISSUE TITLE
Allow NA for kingdom and rank in name_backbone

### ISSUE THREAD

**Issue by peterdesmet** [ropensci/rgbif#351]
`name_backbone()` expects empty `kingdom` or `rank` parameters to be expressed as `NULL` if unknown. When passing data, empty values are more likely to be expressed as `NA` however (e.g. in dataframes).

Could the function be updated so that `NA` values are handled correctly (e.g. converted to `NULL` in the function) for these parameters?

**Comment by sckott** [comment]
thanks peter, are you talking about this behavior?

```r
name_backbone(name='Helianthus annuus', rank=NA)
#> Error: Cannot parse NA into a known Rank
```

I'm hesitant to change how a single fxn handles this while not changing the other functions in the pkg. if it's changed here, i'd want to make it consistent throughout the pkg. the change i think would just need to be in `rgbif_compact` to remove `NULL` and any `NA` type

**Comment by peterdesmet** [comment]
Indeed that behaviour. @damianooldoni told me about it. It currently means users have to code around that.

I also agree it should be handled consistently across the pkg.

**Comment by sckott** [comment]
okay, will look at this soon

**Comment by sckott** [comment]
@peterdesmet okay, reinstall and try again, NA should be removed across the package now

**Comment by peterdesmet** [comment]
Thanks @sckott, but I still get the exact same error as in https://github.com/ropensci/rgbif/issues/351#issuecomment-482644554

**Comment by peterdesmet** [comment]
Sorry, my mistake: pkg wasn't loaded properly. Is fixed, thanks. 👍

**Comment by damianooldoni** [comment]
I confirm. It is fixed. Thanks again.

**Comment by sckott** [comment]
glad it works
