### ISSUE TITLE
Count unique species

### ISSUE THREAD

**Issue by simontarr-aecom** [ropensci/rgbif#352]
Hello,

I have a quick question about rgbif - I thought I'd post here before potentially reinventing the wheel. The problem can be summarised as follows: I would like to define a bounding box around an area of interest, query GBIF and count the number of unique species that fall within that region, ideally across all taxa. In short, I would like to calculate a very rough and ready measure of species richness within an area. 

Is there a reasonably straightforward way of doing this using rgbif (or perhaps spocc)?

Thanks in advance.

**Comment by dnoesgaard** [comment]
GBIF has [recently introduced](https://discourse.gbif.org/t/new-feature-download-lists-of-distinct-species-contained-in-occurrence-searches/687) the ability to download a list of unique taxa in any occurrence query. Not sure this has been added to rgbif (needs "format": "SPECIES_LIST" in the query)—correct me if I'm wrong. 

However, it seems rgbif is fine with importing these lists, e.g. did a simple bounding box of an island (http://api.gbif.org/v1/occurrence/download/0014128-190320150433242) and imported the download here:

```
> dl<-occ_download_get("0014128-190320150433242")
Download file size: 0.04 MB
On disk at ./0014128-190320150433242.zip
> occ_download_import(dl)
# A tibble: 801 x 21
   taxonKey scientificName acceptedTaxonKey acceptedScienti… numberOfOccurre… taxonRank taxonomicStatus kingdom kingdomKey phylum phylumKey class classKey order orderKey
      <int> <chr>                     <int> <chr>                       <int> <chr>     <chr>           <chr>        <int> <chr>      <int> <chr>    <int> <chr>    <int>
 1  7570897 Spergularia m…          7570897 Spergularia med…               25 SPECIES   ACCEPTED        Plantae          6 Trach…   7707728 Magn…      220 Cary…      422
 2  2481618 Stercorarius …          2481618 Stercorarius sk…                3 SPECIES   ACCEPTED        Animal…          1 Chord…        44 Aves       212 Char…  7192402
 3  3807718 Cerastium sub…          3807718 Cerastium subte…                4 SPECIES   ACCEPTED        Plantae          6 Trach…   7707728 Magn…      220 Cary…      422
 4  2252458 Terebratulina…          2252458 Terebratulina D…                1 GENUS     ACCEPTED        Animal…          1 Brach…       110 Rhyn…      210 Tere…      509
 5  4856677 Osculipora d'…          4856677 Osculipora d'Or…                1 GENUS     ACCEPTED        Animal…          1 Bryoz…        53 Sten…      226 Cycl…     1497
 6  7192432 Haematopus os…          7192432 Haematopus ostr…                2 SUBSPECI… ACCEPTED        Animal…          1 Chord…        44 Aves       212 Char…  7192402
 7  7473187 Draba verna L.          7473187 Draba verna L.                  4 SPECIES   ACCEPTED        Plantae          6 Trach…   7707728 Magn…      220 Bras…  7225535
 8  2480242 Vanellus vane…          2480242 Vanellus vanell…              225 SPECIES   ACCEPTED        Animal…          1 Chord…        44 Aves       212 Char…  7192402
 9  2480281 Charadrius mo…          2480281 Charadrius mori…               14 SPECIES   ACCEPTED        Animal…          1 Chord…        44 Aves       212 Char…  7192402
10  2480726 Pandion halia…          2480726 Pandion haliaet…               60 SPECIES   ACCEPTED        Animal…          1 Chord…        44 Aves       212 Acci…  7191147
```

Note, these lists also contain records of organisms identified to genus and higher. So you'll have to filter, if only interested in species.

**Comment by sckott** [comment]
thanks for your question @simontarr-aecom and thanks for your response @dnoesgaard 

looks as though we don't support species list just yet, working on it now

**Comment by sckott** [comment]
reinstall `remotes::install_github("ropensci/rgbif@download-format")`, reload R, then try for example:

```r
geometry <- "POLYGON((30.1 10.1,40 40,20 40,10 20,30.1 10.1))"
res <- occ_download(paste0("geometry within ", geometry), type = "within", format = "SPECIES_LIST")
res 
#> <<gbif download>>
#>   Username: sckott
#>   E-mail: myrmecocystus@gmail.com
#>   Format: SPECIES_LIST
#>   Download key: 0000182-190415153152247

occ_download_meta(res) # see when ready

x <- occ_download_get(res) # download
#> Download file size: 4.73 MB
#> On disk at ./0000182-190415153152247.zip

occ_download_import(x) # import into R
```

it's important to do `geometry within <WKT>`  instead of `geometry = <WKT>`

**Comment by simontarr-aecom** [comment]
Hi @dnoesgaard @sckott 

Thank you both for your help with this and for applying a solution so quickly. This is really useful stuff and will save me a ton of time :)

**Comment by sckott** [comment]
@simontarr-aecom great, glad it works and that it will save you time

**Comment by simon-tarr** [comment]
Hi @sckott I know this issue is now closed but do you know of an easy way to filter out extinct species using the above method? A few Irish Elk have crept into my downloaded dataframe! I can't see an obvious way of filtering out extinct species.

**Comment by sckott** [comment]
having a look.

**Comment by sckott** [comment]
i think maybe occurrence API use to have an extinct parameter to toggle those records, but no longer exists. they do have an `isExtinct` parameter in the name lookup method, e.g., `name_lookup(isExtinct=TRUE, limit=10)` 

@dnoesgaard is there any way to filter by exinction status with the occurrence download API? AFAIK there is not. there is isExtinct on the `/species/search` route, but i dont think there's a way to pass a taxon key to that route so e.g. a user could get a species list with the download API , then check extinction status with `/species/search`. And extinction status doesn't seem to be in the data for an extinct species e.g., http://api.gbif.org/v1/species/104070564

**Comment by dnoesgaard** [comment]
Not that I'm aware. Perhaps @MattBlissett knows more?

**Comment by simon-tarr** [comment]
@sckott @dnoesgaard thank you both for taking some more time to investigate this for me. I'm very grateful!

**Comment by MattBlissett** [comment]
> Not that I'm aware. Perhaps @MattBlissett knows more?

The extinction data comes from a GBIF extension, and is stored in species profiles: http://api.gbif.org/v1/species/107207961/speciesProfiles 

However, the Irish elk example doesn't include this extension, so I don't think the data is complete enough for it to be useful to you. That's probably why there's not an easy way to use it.

**Comment by simon-tarr** [comment]
> > Not that I'm aware. Perhaps @MattBlissett knows more?
> 
> The extinction data comes from a GBIF extension, and is stored in species profiles: http://api.gbif.org/v1/species/107207961/speciesProfiles
> 
> However, the Irish elk example doesn't include this extension, so I don't think the data is complete enough for it to be useful to you. That's probably why there's not an easy way to use it.

Thanks for the reply @MattBlissett. Makes sense.
I may have to approach this from a different angle, using a list of known extant species and filtering the GBIF species list download from a "known" list of species.

**Comment by dnoesgaard** [comment]
Correct me if I'm wrong but doesn't the taxize library have a function to filter out extinct species?

**Comment by sckott** [comment]
good idea @dnoesgaard  - the only data source for names that includes ability to toggle extinction status is Catalogue of Life. and trying it it doesn't seem to work as expected, that is only extant species are listed 

http://www.catalogueoflife.org/col/webservice?name=Cervidae&response=full

and when you search for Megaloceros in COL's web interface you only get other taxa matching Megaloceros for an epithet

**Comment by sckott** [comment]
the quickest way to do this, if you're trying to target a specific geographic area, should be to use  occ_download query with geometry and then filter out taxa that are extinct.
