### ISSUE TITLE
R Session Aborting when using occ_download_import()

### ISSUE THREAD

**Issue by simon-tarr** [ropensci/rgbif#353]
Hello, I am trying to download and import a large data set from GBIF into R (All mammal observations in the UK since 2000):

```
res <- rgbif::occ_download(
                           "taxonKey = 359",
                           "basisOfRecord = HUMAN_OBSERVATION, PRESERVED_SPECIMEN",
                           "country = GB", 
                           "hasCoordinate = true",
                           "hasGeospatialIssue = false",
                           "year >= 2000"
)
```
The above generates a .zip file of about 200MB in size. When using `occ_download_import()` the object `res`, my R session aborts every time. 

![58389cf93dd1a75ae33ffb884fce301f0716c51e](https://user-images.githubusercontent.com/27423094/56971290-de2c7a00-6b60-11e9-96d6-8dbcb5009cfd.png)

Am I trying to import too much data for the function/R to handle? I have 32GB RAM with a 16-core Xeon and if I watch Task Manager when importing the data, there's nothing out of the ordinary - RAM utilisation remains steady (and low), and there are no spikes in CPU usage. 

I only need to do this once for certain classes of animal in the UK - once imported, I intend to cut the data frame right down to size and use that instead (I only need class, order, family, genus, species, lat, long). Unfortunately I can't get to that stage due to the crashes. I noticed that `rgbif` will handle selecting columns with `occ_search()`, but that the GBIF API doesn't allow selecting columns prior to download. Seems like a weird omission to me....they'd save a ton a bandwidth if you you could specify what data you want before downloading :) . Am I hitting a hard limit of the API here with no way past? 

Any help would be much appreciated. Thanks in advance.

**Comment by sckott** [comment]
thanks for the issue @simon-tarr - Please share your `sessionInfo()` (or `devtools::session_info()`) as requested

**Comment by sckott** [comment]
my guess without testing this/knowing your session info is it's a problem with `data.table::fread`

**Comment by simon-tarr** [comment]
Hi @sckott, sorry for not including `sessionInfo()`. I've included it below:

> 
> > sessionInfo()
> R version 3.5.3 (2019-03-11)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] rgbif_1.2.0.9511
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1        pillar_1.3.1      compiler_3.5.3    plyr_1.8.4        tools_3.5.3       jsonlite_1.6      tibble_2.1.1      gtable_0.3.0     
>  [9] lattice_0.20-38   pkgconfig_2.0.2   rlang_0.3.4       rstudioapi_0.10   crul_0.7.4        curl_3.3          yaml_2.2.0        dplyr_0.8.0.1    
> [17] httr_1.4.0        stringr_1.4.0     xml2_1.2.0        rgeos_0.4-2       triebeard_0.3.0   grid_3.5.3        tidyselect_0.2.5  glue_1.3.1       
> [25] httpcode_0.2.0    data.table_1.12.2 geoaxe_0.1.0      R6_2.4.0          oai_0.2.2         sp_1.3-1          ggplot2_3.1.1     purrr_0.3.2      
> [33] magrittr_1.5      whisker_0.3-2     urltools_1.7.3    scales_1.0.0      assertthat_0.2.1  colorspace_1.4-1  stringi_1.4.3     lazyeval_0.2.2   
> [41] munsell_0.5.0     crayon_1.3.4

**Comment by sckott** [comment]
thanks, your example does indeed cause rstudio to abort on the call to `occ_download_import` 

it is a `data.table::fread` problem. 

You can pass on additional parameters to `data.table::fread` through the `...`. I tried `fill=FALSE` and that made it work, but still had a parsing error, and the error suggested trying `quote` parameter. this works for me:

```r
res <- occ_download(
                           "taxonKey = 359",
                           "basisOfRecord = HUMAN_OBSERVATION, PRESERVED_SPECIMEN",
                           "country = GB", 
                           "hasCoordinate = true",
                           "hasGeospatialIssue = false",
                           "year >= 2000"
)
x <- occ_download_get(res)
occ_download_import(x, fill=FALSE, quote = "")
```

**Comment by simon-tarr** [comment]
@sckott this works great, thank you (again!) for your help. Appreciated as always.

**Comment by sckott** [comment]
glad it works
