### ISSUE TITLE
Unit-test of function elevation not passed

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rgbif#357]
While unit-testing my PR #356 I found that the test from `test-elevation.r` here below didn't pass. I have a working geonames account saved following the well written documentation of function `elevation`. The account works well as previous tests passed flawlessly.

```r
test-elevation.R:100: error: fails correctly
Unauthorized (HTTP 401)
1: expect_warning(elevation(dat), "Input data has some points at 0,0")
```

Any idea about it? Thank you very much.

**Comment by sckott** [comment]
thanks, not sure, will take a look

**Comment by sckott** [comment]
ah, env vars on travis shouldn't be available on PR's, so that failure makes sense. as does the occ_download failures. 

i'm not sure if there's a best practice for this scenario where you ideally don't want build on travis to fail on PR's where you have env vars required in tests. maybe there's a travis env var that says whether it's a PR or not?

**Comment by damianooldoni** [comment]
I think I found documentation about it: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions.
It's worth a try, isn't?

**Comment by sckott** [comment]
are you thinking like this within R:

```r
x <- Sys.getenv("TRAVIS_PULL_REQUEST")
travis_pr <- x == "true"
if (!travis_pr) { # run only if NOT a Travis PR
    test_that("some tests ...", {
        expect_is(occ_search(...), "some-class")
    })
}
```

or just in the .travis.yml file?

**Comment by damianooldoni** [comment]
@sckott , I don't find an easy solution to this. What if we do the following workaround:
1. PR from my fork to a new ad-hoc branch of `ropensci/rgbif`
2. review it and eventually accept it even if Travis says no
3. PR within `ropensci/rgbif` to check possible remaining Travis issues

Or do you have other ideas about it?

**Comment by sckott** [comment]
how about we add you as a collaborator and you can send PR's from within the repository? that way env vars are available on PR's

**Comment by damianooldoni** [comment]
Well, it would be a good solution. And a big honor! :+1:

**Comment by sckott** [comment]
you should get an invite

**Comment by damianooldoni** [comment]
Indeed, I accept it.

**Comment by damianooldoni** [comment]
Sorry for being late. I will try to schedule it within this week!

**Comment by damianooldoni** [comment]
I think this issue can be closed, @sckott , isn't?

**Comment by sckott** [comment]
yes, closing
