### ISSUE TITLE
occ_download failure with wkt parameter

### ISSUE THREAD

**Issue by jivelasquezt** [ropensci/rgbif#360]
The following occurrence download call has status KILLED whenever is called from R:

```
key <- name_backbone(name = "Mammalia")$classKey
aoi<-getData(name="GADM",country="COL", level=0) #Get country shapefile
data.request<-occ_download(paste0('taxonKey = ', key),
                           'hasCoordinate = TRUE',
                           user="xxxx",
                           pwd="xxx",
                           email="xxxx@gmail.com",
                           format="SIMPLE_CSV",
                           paste('geometry = ', gbif_bbox2wkt(bbox=c(extent(aoi)@xmin,extent(aoi)@ymin,extent(aoi)@xmax,extent(aoi)@ymax))))
```
However, if I open the download link in GBIF and rerun the query it is successful. I believe there may be something worng with how the geometry parameter is being interpreted by the GBIF API. I'd appreciate any help with this. For reference, the download link for the above request was:  https://www.gbif.org/occurrence/download/0020539-190415153152247

**Comment by sckott** [comment]
session info please, as requested

**Comment by MattBlissett** [comment]
The geometry part of the query is sent as an "equals" predicate rather than "within".

```
{"type":"within","geometry":"POLYGON((-73…))"}
```

I've created an issue (https://github.com/gbif/occurrence/issues/124) to reject using "equals" on geometry.

**Comment by sckott** [comment]
thanks @MattBlissett ! 

closing this for now unless user wants to re-visit this

**Comment by jivelasquezt** [comment]
Sorry, I forgot to close the issue. Effectively, this fixes the problem.
