### ISSUE TITLE
map_fetch projection issues

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/rgbif#366]
The function `map_fetch` returns a raster of occurrence densities. Several different projections are possible. Using projection EPSG:3857 we get the correct data but we're having trouble merging this with other mapped data due to projection issues it appears. The self contained example demonstrates that when reprojecting the longitude and latitudes of an occurrence search query to projection EPSG:3857 that those points are converted to units of meters i.e. on a range from -1.9e-7 to 1.9e7 along the x-axis while the density data which is supposedly also in EPSG:3857 the x-axis ranges from -180 to 180.  Does anyone have a clue why there is this discrepancy? 

```r
library(rgbif)
library(sp)
library(raster)

den <- map_fetch(taxonKey = 2480498, srs = "EPSG:3857")
den

occs = occ_search(taxonKey = 2480498)
crds <- occs$data[c("decimalLongitude","decimalLatitude")] ## Extract only the coordinates

plot(den)
points(crds, pch='.', col='red')
# clearly they are in different projections
# as the points are in longlat and 
# the density data is in EPSG:3857 so let's reproject the points

crds = sp::SpatialPoints(crds, proj4string = CRS("+proj=longlat"))
crds_3857 = sp::spTransform(crds, CRSobj = CRS(projection(den)))

plot(den)
points(crds_3857, pch='.', col='red')

summary(coordinates(den))
       x                 y         
 Min.   :-179.65   Min.   :-84.93  
 1st Qu.: -89.82   1st Qu.:-42.47  
 Median :   0.00   Median :  0.00  
 Mean   :   0.00   Mean   :  0.00  
 3rd Qu.:  89.82   3rd Qu.: 42.47  
 Max.   : 179.65   Max.   : 84.93  
summary(coordinates(crds_3857))
      long                lat          
 Min.   :-19902070   Min.   :-5886752  
 1st Qu.:-11170880   1st Qu.: 2246288  
 Median :-10623397   Median : 3877159  
 Mean   : -7806810   Mean   : 3071206  
 3rd Qu.: -9283286   3rd Qu.: 4925072  
 Max.   : 19954019   Max.   : 8216917 
```

<details> <summary><strong>Session Info</strong></summary>

```r
devtools::session_info()
Session info ----------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32             
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2019-07-23                  

Packages --------------------------------------------
 package     * version date       source        
 assertthat    0.2.1   2019-03-21 CRAN (R 3.5.3)
 backports     1.1.2   2017-12-13 CRAN (R 3.5.0)
 base        * 3.5.0   2018-04-23 local         
 cli           1.0.0   2017-11-05 CRAN (R 3.5.1)
 colorspace    1.3-2   2016-12-14 CRAN (R 3.5.1)
 compiler      3.5.0   2018-04-23 local         
 crayon        1.3.4   2017-09-16 CRAN (R 3.5.1)
 crosstalk     1.0.0   2016-12-21 CRAN (R 3.5.1)
 crul          0.6.0   2018-07-10 CRAN (R 3.5.1)
 curl          3.2     2018-03-28 CRAN (R 3.5.1)
 data.table    1.11.8  2018-09-30 CRAN (R 3.5.1)
 datasets    * 3.5.0   2018-04-23 local         
 devtools      1.13.6  2018-06-27 CRAN (R 3.5.1)
 digest        0.6.17  2018-09-12 CRAN (R 3.5.1)
 dplyr         0.8.1   2019-05-14 CRAN (R 3.5.3)
 fansi         0.4.0   2018-10-05 CRAN (R 3.5.3)
 foreign       0.8-70  2017-11-28 CRAN (R 3.5.0)
 geoaxe        0.1.0   2016-02-19 CRAN (R 3.5.1)
 ggplot2       3.2.0   2019-06-16 CRAN (R 3.5.3)
 glue          1.3.1   2019-03-12 CRAN (R 3.5.3)
 graphics    * 3.5.0   2018-04-23 local         
 grDevices   * 3.5.0   2018-04-23 local         
 grid          3.5.0   2018-04-23 local         
 gtable        0.2.0   2016-02-26 CRAN (R 3.5.1)
 htmltools     0.3.6   2017-04-28 CRAN (R 3.5.1)
 htmlwidgets   1.3     2018-09-30 CRAN (R 3.5.1)
 httpcode      0.2.0   2016-11-14 CRAN (R 3.5.0)
 httpuv        1.4.5   2018-07-19 CRAN (R 3.5.1)
 httr          1.3.1   2017-08-20 CRAN (R 3.5.1)
 jsonlite      1.5     2017-06-01 CRAN (R 3.5.1)
 later         0.7.5   2018-09-18 CRAN (R 3.5.1)
 lattice       0.20-35 2017-03-25 CRAN (R 3.5.0)
 lazyeval      0.2.1   2017-10-29 CRAN (R 3.5.1)
 leaflet     * 2.0.2   2018-08-27 CRAN (R 3.5.3)
 magrittr      1.5     2014-11-22 CRAN (R 3.5.1)
 maps        * 3.3.0   2018-04-03 CRAN (R 3.5.1)
 maptools    * 0.9-4   2018-09-19 CRAN (R 3.5.1)
 memoise       1.1.0   2017-04-21 CRAN (R 3.5.1)
 methods     * 3.5.0   2018-04-23 local         
 mime          0.5     2016-07-07 CRAN (R 3.5.0)
 munsell       0.5.0   2018-06-12 CRAN (R 3.5.1)
 oai           0.2.2   2016-11-24 CRAN (R 3.5.1)
 parallel      3.5.0   2018-04-23 local         
 pillar        1.4.1   2019-05-28 CRAN (R 3.5.3)
 pkgconfig     2.0.2   2018-08-16 CRAN (R 3.5.1)
 plyr          1.8.4   2016-06-08 CRAN (R 3.5.1)
 png           0.1-7   2013-12-03 CRAN (R 3.5.0)
 promises      1.0.1   2018-04-13 CRAN (R 3.5.1)
 purrr         0.3.2   2019-03-15 CRAN (R 3.5.3)
 R6            2.4.0   2019-02-14 CRAN (R 3.5.3)
 raster      * 2.6-7   2017-11-13 CRAN (R 3.5.1)
 Rcpp          1.0.1   2019-03-17 CRAN (R 3.5.3)
 rgbif       * 1.1.0   2018-10-19 CRAN (R 3.5.1)
 rgdal         1.3-6   2018-10-16 CRAN (R 3.5.1)
 rgeos         0.3-28  2018-06-08 CRAN (R 3.5.1)
 rlang         0.3.4   2019-04-07 CRAN (R 3.5.3)
 rstudioapi    0.7     2017-09-07 CRAN (R 3.5.1)
 scales        1.0.0   2018-08-09 CRAN (R 3.5.1)
 shiny         1.1.0   2018-05-17 CRAN (R 3.5.0)
 sp          * 1.3-1   2018-06-05 CRAN (R 3.5.1)
 stats       * 3.5.0   2018-04-23 local         
 stringi       1.2.4   2018-07-20 CRAN (R 3.5.1)
 stringr       1.3.1   2018-05-10 CRAN (R 3.5.1)
 tibble        2.1.3   2019-06-06 CRAN (R 3.5.3)
 tidyselect    0.2.5   2018-10-11 CRAN (R 3.5.3)
 tools         3.5.0   2018-04-23 local         
 triebeard     0.3.0   2016-08-04 CRAN (R 3.5.1)
 urltools      1.7.1   2018-08-03 CRAN (R 3.5.1)
 utf8          1.1.4   2018-05-24 CRAN (R 3.5.1)
 utils       * 3.5.0   2018-04-23 local         
 vctrs         0.1.0   2018-11-29 CRAN (R 3.5.3)
 whisker       0.3-2   2013-04-28 CRAN (R 3.5.1)
 withr         2.1.2   2018-03-15 CRAN (R 3.5.1)
 xml2          1.2.0   2018-01-24 CRAN (R 3.5.1)
 xtable        1.8-3   2018-08-29 CRAN (R 3.5.1)
 yaml          2.2.0   2018-07-25 CRAN (R 3.5.1)
 zeallot       0.1.0   2018-01-28 CRAN (R 3.5.3)
```

</details>

One other quick note is that only projection `EPSG:3857` returns the entire Earth. This seems to be a GBIF rather than `rgbif` issue: 

Compare the following: 
https://api.gbif.org/v2/map/occurrence/density/0/0/0@1x.png?srs=EPSG:3857
https://api.gbif.org/v2/map/occurrence/density/0/0/0@1x.png?srs=EPSG:4326
 
As can be seen at those links EPSG:4326 is centered on the western hemisphere and crops out a larger portion of the Earth. The other projection options that `map_fetch` provide return similar kinds of results.

**Comment by sckott** [comment]
@jhnwllr  @timrobertson100 @MattBlissett  Any thoughts on the 2nd point above about projections containing the whole earth or portions of it?

**Comment by sckott** [comment]
thanks @dmcglinn - pinged GBIF folks about the 2nd point. 

For the 1st point, maybe someone with more spatial experience than I can point us in the right direction. @mdsumner  @mpadge Any ideas on the stuff above the session info block?

**Comment by MattBlissett** [comment]
Very briefly, the EPSG:4326 projection has two tiles at zoom level 0:

https://api.gbif.org/v2/map/occurrence/density/0/0/0@1x.png?srs=EPSG:4326

https://api.gbif.org/v2/map/occurrence/density/0/1/0@1x.png?srs=EPSG:4326

![west](https://api.gbif.org/v2/map/occurrence/density/0/0/0@1x.png?srs=EPSG:4326)

![east](https://api.gbif.org/v2/map/occurrence/density/0/1/0@1x.png?srs=EPSG:4326)

**Comment by dmcglinn** [comment]
ahh thanks for that @MattBlissett !

**Comment by mdsumner** [comment]
Late to the rgbif party but could probably use ceramic, or just slippymath to get these tiles

**Comment by dmcglinn** [comment]
Thanks for the suggestion. I’ll look into that. So does the geometry of this projection seem funky to you too?

**Comment by mdsumner** [comment]
Nothing funky, I didn't expect that the 4326 version would have two tiles at zoom=0 where the 3857 one has only one (as @MattBlissett points out above). 

This confirms the two-tiles thing but doesn't explain why https://stackoverflow.com/questions/36366481/incomplete-map-comes-back-from-tile-server-more-tiles-available-at-zoom-level-t#comment60440548_36378046

I'll learn a bit from this, and in time maybe can patch it into ceramic - it's brought up some issues with hardcoded stuff that I can see already.  (But I otherwise have nothing to offer).

**Comment by MattBlissett** [comment]
Our [demo/debugging example](https://tile.gbif.org/ui/4326/) might be helpful for understanding the tile scheme, although the tile grid which can be enabled is OpenLayers' system (counting down from -1 for some reason).

It's unusual for anyone to provide tiles in EPSG:4326 projection.  I only know of one other provider: ESRI's at https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer/tile/0/0/0

I copied their tile scheme, of two tiles at zoom zero, which they've chosen because the projection is exactly twice as wide as it is high: 360° by 180°.

Any projection other than Web Mercator (3857) is more difficult to use with mapping tools intended for web sites, or for working with typical web maps — at first glance, I think ceramic is designed this way. 

(We considered an alternative tile scheme, squashing the rectangle into single square at zoom 0. This means some parts of web-mercator libraries would work, but it doesn't help plot a point over that map, and the empty space above and below the map could cause problems, like crashing a mapping tool if someone clicks the map "north of the north pole".)

Converting from a latitude+longitude to a tile at a given zoom is straightforward (the width of the map is 2⁽ᶻ⁺¹⁾ tiles, the height is 2ᶻ tiles, etc)

**Comment by mdsumner** [comment]
Oh of course (two tiles!), thanks for the details

**Comment by dmcglinn** [comment]
Thanks for the additional details about the projections. Those are very helpful. 
My main question remains: Why do the grid coordinates of the EPSG:3857 (web mercator) provided by GBIF appear to be in longitudes and latitudes while projecting a coordinate system to EPSG:3857 in R using spTransform seems to convert grid coordinates into something that is not longitudes and latitudes. There is likely something trivial I'm overlooking here.

**Comment by mdsumner** [comment]
whoa, gee good point - that's just wrong, your `den` above

```R
extent     : -180, 180, -85.1, 85.1  (xmin, xmax, ymin, ymax)
crs        : +init=epsg:3857 +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs 

```

should be 

```R
library(rgbif)
library(rgbif)
library(sp)
library(raster)
den <- map_fetch(taxonKey = 2480498, srs = "EPSG:3857")

r <- setExtent(den, extent(-20037508, 20037508, -20037508, 20037508))


plot(r)
mp <- maps::map(plot = FALSE)
xy <- rgdal::project(cbind(mp$x, mp$y), projection(den))
lines(xy)

```

It's not clear (I haven't looked) if the extent in Y should be -20037508, 20037508 or -20100885, 20100885 for latitude 85.1 (the classic extent is 85.05113 which is where Mercator is a square).

**Comment by mdsumner** [comment]
Please try PR #367

**Comment by MattBlissett** [comment]
> It's not clear (I haven't looked) if the extent in Y should be -20037508, 20037508 or -20100885, 20100885 for latitude 85.1 (the classic extent is 85.05113 which is where Mercator is a square).

The GBIF tiles use spherical Mercator, so 85.05113°, or exactly `180/PI * 2*atan(exp(PI)-PI/2)`

Using https://mygeodata.cloud/cs2cs/ I get a maximum coordinate of 20037508.3428.

(I can't see where 85.1° came from.)

**Comment by sckott** [comment]
thanks @mdsumner @MattBlissett and @dmcglinn - having a look at the PR

**Comment by sckott** [comment]
@dmcglinn the PR is merged now. let me know if it doesn't address your issue

**Comment by dmcglinn** [comment]
Thanks @MattBlissett and @mdsumner for all your help on this. @sckott the PR did address my issue.
