### ISSUE TITLE
occ_search with more than 1 taxon, and more than 1 type of basis of record

### ISSUE THREAD

**Issue by Huasheng12306** [ropensci/rgbif#368]
Dear Sckott,

`occ_search` with 1 taxa and one type of basis of record worked well for me. But when it turned to more, it showed error. e.g. 

```r
occ_search(scientificName = ’Nypa’ & ‘Calamus’, basisofRecord = ‘PRESERVED_SPECIMEN’ & ‘OBSERVATION’ & ‘HUMAN_OBSERVATION'...)
```

What could be wrong?

Thank you in advance for your reply!
Huasheng

**Comment by sckott** [comment]
that's not how you construct vectors in R. you'd do `c('foo', 'bar')`

you can do many values for scientificname, but only 1 per request for basisofrecord

**Comment by Huasheng12306** [comment]
Thanks Sckott! I am a beginner on R. In this case, it is inconvenient for more than 1 types of records.
