### ISSUE TITLE
Density Differences with Raw Data and Mapfetch

### ISSUE THREAD

**Issue by AshleyWoods** [ropensci/rgbif#373]
Using the `map_fetch()` method, it is possible to get the proportional density for each cell of the raster layer returned (cells have values of 0 to 1, 0 being no occurrences reported and 1 being the maximum number of occurrences reported). It should, therefore, be possible to reproject the coordinates gained from `occ_download()` and `occ_download_get()` into the same projection and divide the value of each cell by the maximum occupancy to convert the occurrence values into proportional density as well. If this is done with the same data for `map_fetch()` and `occ_download() `then a plot of the two should have a trendline of 1:1. 

However, the code below shows that the data between the two do not match up. Does anyone know why this might be? In the example below, replace the '#' with your GBIF login credentials. This will grab the most recent data so that it's not a matter of outdated data. 

```
library(rgbif)
library(raster)
library(sp)
library(rgdal)

#get the data in here, this is the most recent data
sp_key <- name_suggest(q ="Caretta caretta", rank = "species")$key[1]
res = occ_download(paste("taxonKey =", sp_key), 'hasCoordinate = TRUE',
                   user = "#", pwd = "#", 
                   email = "#")
continue = TRUE
while(continue){
  meta = occ_download_meta(res)
  if (meta$status == "SUCCEEDED"){
    continue = FALSE
    dat <- occ_download_get(res[1], overwrite = TRUE) %>%
      occ_download_import()
  }     
  if (meta$status == "KILLED"){
    continue = FALSE
    #Returns: ERROR:Bad Request(HTTP 400)
  }
  #30 second delay --  Extend?
  Sys.sleep(30)
}

#This is the most recent map_fetch() data for the same sp_key
comparison <- map_fetch(taxonKey = sp_key, srs = "EPSG:3857")

comparison3 <- setExtent(comparison, extent(-20037508, 20037508, -20037508, 20037508))

  #Throw out invalid crds + reproject it
  crds = data.frame(long = dat$decimalLongitude, lat = dat$decimalLatitude)
  crds = subset(crds, subset= lat > -85.06)
  crds = subset(crds, subset = lat < 85.06)
  
  #This grabs columns that tell if the occurrence is for MORE THAN ONE example of the organism at that location
  crds2 = data.frame(long = dat$decimalLongitude, lat = dat$decimalLatitude, count = dat$individualCount, quantity = dat$organismQuantity)
  crds2 = subset(crds2, subset= lat > -85.06)
  crds2 = subset(crds2, subset = lat < 85.06)
  
  #This loops through and duplicates records with more than one organism per record so that the number of 
  #coordinates listed matches the total number of occurrences logged overall
  for (i in 1:length(rownames(crds2))) {
    if (!is.na(crds2[i,3]) && crds2[i,3] > 1) {
      #it has more than 1 occurrence in the individualCount column, append it however many times to the end of crds
      for (j in 1:crds2[i,3]) {
        crds <- rbind(crds, c(crds2[i,1], crds2[i,2]))
      }
      
    }else if (!is.na(crds2[i,4]) && is.numeric(crds2[i,4]) && crds2[i,4] > 1) {
      #it has more than 1 occurrence in the organismQuantity column, append it however many times to the end of crds
      for (j in 1:crds2[i,4]) {
        crds <- rbind(crds, c(crds2[i,1], crds2[i,2]))
      }
      
    }
  }
  
  crds_3857 <- rgdal::project(as.matrix(crds), projection(comparison3))
  
  #Rasterize the crds
  ct = rasterize(crds_3857, comparison3, fun='count')
  
  #turn the numeric values into density values
  max_ct = maxValue(ct)
  prop = calc(ct, function(x) ifelse(is.na(x), 0, x / max_ct))
  test = calc(ct, function(x) ifelse(is.na(x), NA, x/max_ct))

  
#plot final plot (should be 1:1)
plot(comparison3, prop, 
     xlab = "Density of Refrence Points (Comparison dataset)",
     ylab = "Density of Species of Interest", maxpixels = 262144, xlim = c(0,1), ylim = c(0,1))

#add best fit line to plot (should be 1:1)
abline(lm(getValues(prop) ~ getValues(comparison3)))

#show problem - the data for the two is in different ranges
plot(comparison3, comparison3, 
     xlab = "Density of Comparison Dataset",
     ylab = "Density of Comparison Dataset", maxpixels = 262144, xlim = c(0,1), ylim = c(0,1))

plot(prop, prop,
     xlab = "Density of Interest Dataset",
     ylab = "Density of Interest Dataset", maxpixels = 262144, xlim = c(0,1), ylim = c(0,1))
```

The plots returned by this are (in order)
![image](https://user-images.githubusercontent.com/35774040/63457981-ed8d4700-c41f-11e9-9f82-78478abe4a1e.png)
![image](https://user-images.githubusercontent.com/35774040/63458016-fda52680-c41f-11e9-9f86-46acc0677414.png)
![image](https://user-images.githubusercontent.com/35774040/63458041-08f85200-c420-11e9-90c2-4c8ef244ef14.png)

@dmcglinn  

<details> <summary><strong>Session Info</strong></summary>

```r
> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Ubuntu 14.04.3 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2019-08-21                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.2)
 backports     1.1.4   2019-04-10 [1] CRAN (R 3.5.2)
 callr         3.3.1   2019-07-18 [1] CRAN (R 3.5.2)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.2)
 codetools     0.2-16  2018-12-24 [4] CRAN (R 3.5.2)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.2)
 devtools      2.1.0   2019-07-06 [1] CRAN (R 3.5.2)
 digest        0.6.20  2019-07-04 [1] CRAN (R 3.5.2)
 fs            1.3.1   2019-05-06 [1] CRAN (R 3.5.2)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.2)
 lattice       0.20-38 2018-11-04 [4] CRAN (R 3.5.1)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.2)
 pkgbuild      1.0.4   2019-08-05 [1] CRAN (R 3.5.2)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.2)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.2)
 processx      3.4.1   2019-07-18 [1] CRAN (R 3.5.2)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.2)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.2)
 raster      * 2.9-23  2019-07-11 [1] CRAN (R 3.5.2)
 Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.5.2)
 remotes       2.1.0   2019-06-24 [1] CRAN (R 3.5.2)
 rgdal         1.4-4   2019-05-29 [1] CRAN (R 3.5.2)
 rlang         0.4.0   2019-06-25 [1] CRAN (R 3.5.2)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.2)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.5.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
 sp          * 1.3-1   2018-06-05 [1] CRAN (R 3.5.2)
 testthat      2.2.1   2019-07-25 [1] CRAN (R 3.5.2)
 usethis       1.5.1   2019-07-04 [1] CRAN (R 3.5.2)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.2)

```
</details>

**Comment by sckott** [comment]
thanks for this @AshleyWoods ! If you don't mind, I'll check with the GBIF folks. 

@jhnwllr @timrobertson100 @MattBlissett  Does the premise check out in the first paragraph of the comment above?  Should you be able to compare data from the downloads API to the maps API as she does?

**Comment by timrobertson100** [comment]
Replying quickly from phone

2 things spring to mind. Firstly we have an eventual consistency system so maps and occurrence download can be out by a few hours during heavy updates. Secondly, maps will not show records where “hasCoordinateIssue” has been flagged so should be excluded in the comparison.

Let’s get to the bottom of this though.

Thanks,

Tim

**Comment by AshleyWoods** [comment]
I removed the occurrences with "hasGeospatialIssues" flagged (I could not find one labeled "hasCoordinateIssue"). However, the results look the same. Thank you for responding so quickly.

**Comment by MattBlissett** [comment]
Hi,

(Yes, it's "hasGeospatialIssues" which should be excluded.)

* The map tiles ( https://api.gbif.org/v2/map/occurrence/density/0/0/0@1x.png?srs=EPSG:3857&taxonKey=8894817 etc) are counts of occurrence records, not individuals.  They don't take account of individualCount or occurrenceQuantity.

> Using the `map_fetch()` method, it is possible to get the proportional density for each cell of the raster layer returned (cells have values of 0 to 1, 0 being no occurrences reported and 1 being the maximum number of occurrences reported).

I'm afraid that as it stands, I don't think this number is useful for data analysis. It's probably intended more for convenient display/inclusion of a map.

If I understand the R code correctly (and it's not a language I'm particularly familiar with), the rGBIF library takes the "greenness" of the map tile pixels as the density value between 0…1, and the actual values are therefore a bit arbitrary (just from the shades of orange).

https://github.com/ropensci/rgbif/blob/fd3464202156c94aa0ff54bb37fe87669a588fb3/R/map_fetch.R#L227-L230

(A PNG image is four matrices, one each for red, green, blue and transparency.)

It would be possible to determine a more appropriate value, since these are defined on this scale (for the yellow/orange map).

https://github.com/gbif/maps/blob/2d64d1a5576a60e699b577def542d5b1ace40b7b/mapnik-server/src/main/node/cartocss/classic-dot.mss#L1-L8
```css
#occurrence {
  dot-width: 2;
                 [total <=    10] { dot-fill: #FFFF00;  }
  [total >    10][total <=   100] { dot-fill: #FFCC00;  }
  [total >   100][total <=  1000] { dot-fill: #FF9900;  }
  [total >  1000][total <= 10000] { dot-fill: #FF6600;  }
  [total > 10000]                 { dot-fill: #D60A00;  }
}
```

but the best solution would be to use the vector tiles. Unfortunately, that is complicated — vector tiles are optimized for small size (fast download).

The tiles do include exact occurrence count values. An example tile is https://api.gbif.org/v2/map/occurrence/density/0/0/0.mvt?srs=EPSG:3857&taxonKey=8894817

Unfortunately, there doesn't seem to be an R library for reading Mapbox Vector Tile format.  

As a quick check, based on [this Python library](https://github.com/mapbox/vector-tile-base#decode), I've run a count on the same tile:

```python
import vector_tile_base
import sys

f = open(sys.argv[1], "rb")
raw_tile = f.read()
f.close()

total = 0

vt = vector_tile_base.VectorTile(raw_tile)
for l in vt.layers:
    print(l.name)
    for f in l.features:
        print('Point', f.get_geometry(), 'data', f.attributes)
        if (f.get_geometry()[0][0] >= 0 and f.get_geometry()[0][0] <= 511):
            if (f.get_geometry()[0][1] >= 0 and f.get_geometry()[0][1] <= 511):
                total += f.attributes['total']

print(total)
```

(Note excluding points outside 0…512; for display in a web browser the tiles need a "buffer" so the lines join up. A better library would probably handle this automatically.)

This gives 10,742, the same as the [capabilities response for a map tile](http://api.gbif.org/v2/map/occurrence/density/capabilities.json?taxonKey=8894817)

A few lines output by that, showing the year totals and overall totals:

```
Point [[143, 224]] data {'total': 4, '1966': 4}
Point [[210, 198]] data {'2009': 1, 'total': 2, '2011': 1}
Point [[210, 199]] data {'2007': 1, 'total': 2, '2011': 1}
Point [[143, 233]] data {'total': 2, '2017': 2}
```

> Does anyone know why this might be?

> Should you be able to compare data from the downloads API to the maps API as she does?

So sort of: with additional logic, a rough comparison could be made using the PNG image tiles. An exact alignment would require a fair bit more work to parse the MVT tiles.

I hope that's clear! ...

**Comment by sckott** [comment]
thanks @MattBlissett for the thorough reply! 

true, unfortunately there's no mvt R pkg

@AshleyWoods does that clear things up? or no?

**Comment by AshleyWoods** [comment]
Thank you both, that clears things up immensely.

**Comment by sckott** [comment]
@AshleyWoods is the goal here to get occurrence data from `map_fetch`?  or some other goal? is the motivation that `occ_search` or `occ_download` and friends are too slow for your use case?

**Comment by AshleyWoods** [comment]
The goal was to be able to compare the spatial coverage of two different datasets quickly. One would be fetched using `occ_download` and the comparison would be chosen and fetched quickly using `map_fetch`. I already have one graph with the two datasets mapped together but I was hoping to get a more detailed result using a graph of the density of the areas plotted against each other. `occ_download` would be too slow for this case.

**Comment by sckott** [comment]
cool, thanks. 

> compare the spatial coverage of two different datasets quickly.

Visually with your own eyes, or quantitatively?  If the latter, is the "rough comparison could be made using the PNG image tiles"  that Matt references good enough?

**Comment by AshleyWoods** [comment]
I already have something for visual comparison. I was hoping for something quantitative. I'll look into the rough comparison, but I don't know at the moment.

**Comment by AshleyWoods** [comment]
@dmcglinn and I were talking about a way around this issue. The possibility of working with the mvt in python was bought up and we were wondering if you would be interested in having the solution added to rgbif as a modification of the map_fetch function. 

It would work something like this: A python file would be created that could take the result of the mvt api for map_fetch. The python could would then process the result into a matrix/raster that could be manipulated and worked with in R and passed back as the result of map_fetch. 

Is that something you would be interested in adding to rgbif?

**Comment by timrobertson100** [comment]
@AshleyWoods - An alternative could be to just read the MVT in R. MVT is a fairly simple data structure encoded using Google Protocol Buffers. It looks like there is [an R protobuf library](https://github.com/eddelbuettel/rprotobuf). You wouldn't need to implement all features of MVT to read GBIF tiles. Just a thought...

**Comment by AshleyWoods** [comment]
Thank you, I was not aware of this package. It's proving tricky to install but as soon as I get it installed I'll look into that.

**Comment by timrobertson100** [comment]
To give you an idea of what is involved, here is the [Java version](https://github.com/ElectronicChartCentre/java-vector-tile/blob/master/src/main/java/no/ecc/vectortile/VectorTileDecoder.java) which I contributed some minor fixes to.

**Comment by MattBlissett** [comment]
I wrote above that it was "a fair bit more work" to read the MVT tiles in R. I meant that in proportion to the work already done — Ashley's script is under 100 lines, my Python example is 15 lines, but that Java MVT class is 400 lines, and the Python MVT class is 1,200 lines.

**Comment by sckott** [comment]
Good idea @AshleyWoods - I don't want to add anything here that depends on Python, shelling out or otherwise (e.g., reticulate), just cause want to avoid anything that complicates installation for users. It could be another package though if it does require python. 

there's another R pkg for protocol buffers, [protolite](https://cran.r-project.org/web/packages/protolite/) that is maintained by one of our staff, so that'd be a faster approach perhaps in case we need help/fixes - e.g., Jeroen created an interface for serializing geobuf https://github.com/jeroen/protolite/blob/master/R/geobuf.R and geobuf files here https://github.com/jeroen/protolite/tree/master/src - then that interface is used in this other pkg https://github.com/ropensci/geojson/blob/master/R/geobuf.R#L136 

Anyway, all that to say, more soon ...

**Comment by sckott** [comment]
An ideal setup would be if we can get a protobuf implementation - I'll ask @jeroen about this.

**Comment by sckott** [comment]
@AshleyWoods et al. @jeroen was able to get a mvt parser in his `protolite` package https://github.com/jeroen/protolite 

Install `remotes::install_github("ropensci/rgbif@map-fetch-mvt")` , then 

```r
library(rgbif)
library(mapview)
x <- map_fetch(taxonKey = 2480498, year = 2010,
  format = ".mvt")
mapview(x)
```

**Comment by sckott** [comment]
(p.s. i still need to do more testing to make sure we're parsing the mv tiles correctly)

**Comment by sckott** [comment]
@AshleyWoods looks all good to go on our side in terms of `protolite` doing an accurate job of converting mvt tiles to data we can use in R.  Let us know here if you get a chance to try it
g

**Comment by AshleyWoods** [comment]
Thank you @sckott I've been trying to get permissions to install the packages I need to test these options. Unfortunately, it's taking a while. I'll get back to you once I've had a chance to check.

**Comment by AshleyWoods** [comment]
@sckott I tried out the code you posted today and the `mapview()` method seems to be having trouble with projection. For example, here is the result of your code (I zoomed out to give a better view of how off it is):
![image](https://user-images.githubusercontent.com/35774040/65374908-0ece9680-dc5d-11e9-902c-f79a3665901e.png)

When I try to run this fetching all Caretta caretta data I get this warning:
```
sp_key <- name_suggest(q ="Caretta caretta", rank = "species")$key[1]


library(rgbif)
library(mapview)
y <- map_fetch(taxonKey = sp_key, format = ".mvt")
mapview(y)

Warning message:
In sf::st_is_longlat(x) :
  bounding box has potentially an invalid value range for longlat data
```
and this result:
![image](https://user-images.githubusercontent.com/35774040/65374963-869cc100-dc5d-11e9-95d0-7b2e8c069909.png)
It will not let me keep the view scrolled to the right any further but the points that go around the coast of Australia are hidden over there. The key is also strange. 

Any idea what could be happening?

**Comment by sckott** [comment]
thanks @AshleyWoods ! I'll have a look ...

**Comment by AshleyWoods** [comment]
Hey @sckott, I think I solved the geometry problem that occurred in my previous code. It turns out that if I specify the projection to be "EPSG:3857" it matches the map projection. So in your example code you would just define `x` as: 

`x <- map_fetch(taxonKey = 2480498, year = 2010, srs= "EPSG:3857", format = ".mvt")`

That will result in a nice map that lines up with the continents. However, there are some attributes that are incorrect 

```r
x$occurrence
Simple feature collection with 902 features and 116 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: -225 ymin: -43.06889 xmax: 203.9062 ymax: 60.93043
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
```
Note above that epsg is listed as 4326 and not 3857 this is a side effect of `protolite::read_mvt_sf` which appears to set all `mvt` files to 4326.  Also the `proj4string` above is incorrect as this is in the web mercator (3857) projection and not longlat. 

Thank you all so much for implementing this patch - now it appears that the true occurrence counts are available!! Unfortunately it is still unclear what the geometry of the raster is that is used to create the occurrence counts. Specifically the resolution of the cells? The imported mvt should be in 3857 projection but it does not appear to be in units of "m" or "km" for example based on some of the coordinate values. @MattBlissett @timrobertson100 can you offer any help on this?

**Comment by timrobertson100** [comment]
Thanks @AshleyWoods and all for progressing this.

An MVT has no concept of geometry or projection but only pixel offsets (similar to a bitmap) where 0,0 is the top left. GBIF prepares MVTs to four different projections and the counts are recorded against pixel level at each zoom. If a "bin" is added to the request then the pixels are simply aggregated up to either squares or hexagons. 

I presume you are looking at counts per pixel, and that varies at different zoom levels.

I can't tell for sure but the screenshot above, and that you only got half the world suggests you're requesting 4326 (4326 has 2 tiles at zoom 0 as the view is twice as wide as it is tall, while 3857 has a single tile).

While this doesn't answer your question does it help provide some hints as to where to look?

**Comment by dmcglinn** [comment]
Hey @timrobertson100 thanks for the clarification here about `sf` objects!

Also I'm fairly sure that @AshleyWoods is working with EPSG:3857 (web mercator) because her query to `map_fetch` specified it in the `srs` argument. Here is an update screen shot over what she provided that shows the entire earth is returned: 

![Screenshot from 2019-10-02 11-36-11](https://user-images.githubusercontent.com/1190381/66058847-10277b00-e509-11e9-8bba-c8ce3ca2bec9.png)

When you write: 

> GBIF prepares MVTs to four different projections and the counts are recorded against pixel level at each zoom.

Can you please tell us the parameters of that projection for the default zero level of zoom? It is clear that the projection is EPSG 3857 but what is the resolution of the grid cells (i.e., how many pixels wide x tall is the map)? What are the units of map projection, because the bounding box of the `sf` object are
```
bbox:           xmin: -225 ymin: -45.08904 xmax: 224.2969 ymax: 82.76537
``` 
Which implies to me that they are in units of 10's of km - does that seem reasonable to you? I'm not a map guru but I've typically seen it where the units of the map projection are set as m or km so this is surprising to me.  

We could not find this information on GBIF's map api webpage. 

Essentially what we want to do is rasterize the returned `sf` object that has the occurrence counts in it so that we can perform quantitative comparisons between a cleaned raster of data and the raster of occurrence counts. 
![Screenshot from 2019-10-02 11-38-17](https://user-images.githubusercontent.com/1190381/66059289-cab77d80-e509-11e9-9d72-544bae97bbbd.png)

In the image above there is a clear (as expected) grid geometry to the points we just need the parameters for that grid to proceed. Thank you all for all your hard work on this!

**Comment by dmcglinn** [comment]
Ugg, I think I seem my mistake now. EPSG:3857 returns latitude and longitude coordinates it is just that they are on a different spheroid. So these coordinates are just in decimal degrees. I apologize for my stupidity on that!  This still creates a question of what the dimensions of the grid are. I'll try 512 x 512 as there is a note on the map api webpage that this is the resolution of the raster files. Stay tuned.

**Comment by timrobertson100** [comment]
They are indeed 512x512 and you should be looking for decimal degrees.

Please make that configurable though, as we could at some point increase to 1024, 2048 or even 4096 although I suspect it is unlikely.

[This shows](https://github.com/gbif/maps/blob/master/common/src/main/java/org/gbif/maps/common/projection/SphericalMercator.java#L15) how we encode this projection, and I presume there are libraries that can do this encoding/decoding for you.

**Comment by dmcglinn** [comment]
awesome thanks @timrobertson100 that's really helpful. The following code seems to be working for querying the density of occurrences for a species and then converting that to a raster. 

```r
library(raster)
library(rgbif)

x <- map_fetch(taxonKey = 2480498, srs = "EPSG:3857", format = ".mvt")

x_pts <- unlist(x$occurrence$geometry)
x_pts <- matrix(x_pts, nrow=length(x_pts)/2, byrow = T)
x_sp <- SpatialPointsDataFrame(coords = x_pts,
        data = data.frame(total = x$occurrence$total))

y <- raster(ncol=512, nrow=512)

tst <- rasterize(x_sp, y, field = 'total', fun='sum') 
tst4 <- aggregate(tst, fact = 4)
plot(tst4)
```
Which looks like it matches up with: https://www.gbif.org/species/2480498

The last thing to check is just that going from a raw queried points to a mapped density is the same as returned by `map_fetch`. @AshleyWoods can you please double check that then we should be able to close this issue. 

I'll post an issue over at `protolite` pointing out the problem with assigning EPSG 4326 to every imported mvt file.

**Comment by jeroen** [comment]
I have updated `protolite` to do the coordinate transformation with the sf package. Can you try again and see if things work better now?

```r
remotes::install_github("jeroen/protolite")
```

**Comment by sckott** [comment]
@timrobertson100 since you mentioned `bin` above, i'm guessing that `bin` is allowed with the mvt format?  Just making sure as we're erroring on parsing binned mvt results. 

@jeroen this isn't working: 

```r
mvt_fetch(taxonKey = 212, year = 1998, bin = "hex",  hexPerTile = 30)
#> Error in MtrxSet(x, dim, type = "POLYGON", needClosed = TRUE) :
#>   polygons not (all) closed
traceback()
#> 11: stop("polygons not (all) closed")
#> 10: MtrxSet(x, dim, type = "POLYGON", needClosed = TRUE)
#> 9: sf::st_polygon(split_matrix_groups(mat))
#> 8: mvt_sf_polygon(feature$geometry)
#> 7: FUN(X[[i]], ...)
#> 6: lapply(layer$features, function(feature) {
#>        switch(feature$type, POINT = mvt_sf_point(feature$geometry),
#>     ...
#> 5: sf::st_sfc(lapply(layer$features, function(feature) {
#>        switch(feature$type, POINT = mvt_sf_point(feature$geometry),
#>     ...
#> 4: FUN(X[[i]], ...)
#> 3: lapply(layers, function(layer) {
#>        geometry <- sf::st_sfc(lapply(layer$features, function(feature) {
#>     ...
#> 2: protolite::read_mvt_sf(res$content, zxy = c(z, x, y), crs = crs) at mvt_fetch.R#200
#> 1: mvt_fetch(taxonKey = 212, year = 1998, bin = "hex", hexPerTile = 30,
       verbose = TRUE)
```

**Comment by timrobertson100** [comment]
Yes @sckott, we support `bin` for the MVT tiles

**Comment by jeroen** [comment]
@timrobertson100 does the API ever return multipolygons? I'm having a hard time calculating the area to distinguish inner and outer polygons.

**Comment by jeroen** [comment]
I'm seeting this now, but perhaps that's a bug in mapview being unable to wrap around the earth:


```r
library(rgbif)
library(mapview)
out <- mvt_fetch(taxonKey = 212, year = 1998, bin = "hex",  hexPerTile = 30)
mapview(out)
```

<img width="808" alt="Screen Shot 2019-10-08 at 2 41 59 PM" src="https://user-images.githubusercontent.com/216319/66396349-ddcebf80-e9d9-11e9-8d42-257c9517c5fb.png">

**Comment by timrobertson100** [comment]
> @timrobertson100 does the API ever return multipolygons?

No. You can explore the map views in this [developer debug tool](http://api.gbif.org/v2/map/debug/ol/) 

> I'm seeting this now
That looks very close - nice

**Comment by jeroen** [comment]
OK thanks. Two more questions for you:

 - Do you know where I can find example mvt data (with e.g. multi-polygons) that I can use for unit testing my parser?
 - The gbif API allows for setting a custom srs for mvt data. Is this described in the mvt spec? I cannot find how to handle this, or how my client is supposed to know the srs of the mvt data.

**Comment by timrobertson100** [comment]
> Do you know where I can find example mvt data (with e.g. multi-polygons) that I can use for unit testing my parser?

I'm afraid I don't. Because we deal with multiple projections we needed to prepare our [own base maps](https://tile.gbif.org/ui/) too. I'm afraid I don't have time to check now, but perhaps one of them has multi-polygons...

> The gbif API allows for setting a custom srs for mvt data. Is this described in the mvt spec? 

It is explicitly mentioned [in the spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#3-projection-and-bounds) as:

> A Vector Tile SHOULD NOT contain information about its bounds and projection. The file format assumes that the decoder knows the bounds and projection of a Vector Tile before decoding it.

For the GBIF API you know this as you use the `srs` and the tile address (x,y,z) in the request.

**Comment by timrobertson100** [comment]
The [mapbox examples](https://docs.mapbox.com/mapbox-gl-js/example/vector-source/) may well yield a multi polygon somewhere too

**Comment by jeroen** [comment]
> For the GBIF API you know this as you use the srs and the tile address (x,y,z) in the request.

Sorry for not understanding, I'm geologist :) The spec does say `"Web Mercator is the projection of reference"`. What confuses me is that the mvt data are defined [0-1] range (after dividing by 2^z) however it seems that in order to get EPSG:3857 data I need to multiply it by this: https://github.com/jeroen/protolite/blob/master/R/mapbox.R#L125-L129

So what coordinates do I need to expect for other srs values? Should I still normalize to `20037508` or is this already done on the server?

**Comment by timrobertson100** [comment]
I'll try and explain a little.

When you say _scale_ I think you mean to apply the inverse of the [map projection](https://en.wikipedia.org/wiki/Map_projection) which is defined as part of the [spatial reference system](https://en.wikipedia.org/wiki/Spatial_reference_system).

Knowing that we have 512 pixel sized tiles you know that at zoom 0 you have 512x512 in EPSG:3857, EPSG:3575 and EPSG:3031 and 1024x512 for EPSG:4326 (2 tiles). At zoom level 1 you have 1024x1024 and 2048x1024. At zoom level 2 you have... etc

Within a tile, you can decode the pixel location to determine the offset from the top left of the tile, (tile local coordinate space) and can apply some basic math to convert that into the address on the world coordinate space (i.e. 1024x1024 at zoom 1).

From there you need to apply an inverse transformation of the pixel to the decimal degree space. Generally, you find a library for that (Geotools/JTS in Java for example) as it is different for every projection and ranges from simple (EPSG:4326) to fairly complex calculations. Our calculations are always the encoding end, so I am not immediately familiar with how to decode them I'm afraid (JS libraries like OpenLayers do this for us).

**Comment by jeroen** [comment]
I have released protolite 2.0 to CRAN. I think we should be able to merge https://github.com/ropensci/rgbif/pull/378

**Comment by sckott** [comment]
All, this is merged into master now. Let us know of any further issues

**Comment by AshleyWoods** [comment]
I apologize for taking this long to get back. Everything's working great on this end. Thank you for all of your help!

**Comment by timrobertson100** [comment]
Very impressive work folks.

**Comment by sckott** [comment]
glad to hear @AshleyWoods  and thanks for raising the issue here

thanks for all your help @timrobertson100 & @MattBlissett !!
