### ISSUE TITLE
occ_search - getting different number of fields

### ISSUE THREAD

**Issue by Xuletajr** [ropensci/rgbif#376]
I am downloading hundreds of plant species occurrence with occ_search, however it is returning different number of fields for each species (number of columns). 

I tried to use "field" argument to select the data fields I want (e.g., field = c("species", "family", "fieldNumber", "infraspecificEpithet", etc)), but it did not work. 

I look forward to hear from you.

Thank you for your cooperation

**Comment by sckott** [comment]
Thanks for your question @Xuletajr !

Please provide your session info as requested, and share a brief example of what you're talking about if possible.

**Comment by Xuletajr** [comment]
Right. 

I have a loop to read all the species occurrence and export csv files for each one. The csv files exported have different number of columns (variables), but I need all the tables (species) return the same information (same number of columns) for next step. 


for (i in 1:length(especies)) {
    dir.create(paste0("./output_final/",familias[i]), showWarnings = F)
    nome_arquivo <- paste0("./output_final/", familias[i],"/",familias[i],"_", especies[i],"_", "raw.csv")
    print(paste("Processando", especies[i], i, "de", length(especies), sep = " "))
    
    if (!file.exists(nome_arquivo)) {
        key <- name_backbone(name = treespp$scientificName[i])$speciesKey
        if (!is.null(key)) {
            occs <- list()
            for (k in 1:length(key)) {
                occs[[k]] <- occ_search(
                    taxonKey = key[k],
                    limit = 100000,
                    hasCoordinate = TRUE,
                    basisOfRecord = "PRESERVED_SPECIMEN",
                    hasGeospatialIssue = F,
                    return = 'data',
                     fields = c("modified", "institutionCode", "collectionCode", "catalogNumber", 				"species", "identificationQualifier", "family", "genus", "specificEpithet",
                               "infraspecificEpithet", "identifiedBy",   "dateIdentified", "typeStatus", 
                               "recordNumber", "fieldNumber", "recordedBy",
                               "year", "month", "day", "country", "stateProvince", "municipality", "locality",
                               "decimalLatitude", "decimalLongitude", "occurrenceRemarks",
                               "acceptedNameUsage", "occurrenceID", "comment", "bibliographicCitation")   
                )
            }
            print(lapply(occs,dim))
            if (any(!is.null(lapply(occs,dim)))) {
                dim.null <- lapply(occs, function(x) {!is.null(dim(x))})
                occs.f <- subset(occs, dim.null == T)
                occs.f <- dplyr::bind_rows(occs.f)
                print(dim(occs.f))
                write.csv(occs.f, nome_arquivo)
            }
        } else {
            warning(paste("No key found for", especies[i], "\n"))
        }
    }
       #as colunas que criam os comentários nem sempre existem:
    
}

**Comment by sckott** [comment]
thanks for that. 

GBIF doesn't allow the user to say which fields they want returned. We do it internally in rgbif, but i think you just get different fields returned with different queries to GBIF, ending up with the different number of columns you see. 

so we can work with a quick to run reprod. example:

```r
library(rgbif)
especies <- c("Nasa carnea", "Pleopeltis leiopteris", "Vitis corinthiaca",
  "Polygala decidua", "Chrysosplenium giraldianum")
occs <- list()
for (i in seq_along(especies)) {
  print(paste("Processando", especies[i], i, "de", length(especies), sep = " "))    
  key <- name_backbone(name = especies[i])$speciesKey
  occs[[i]] <- occ_search(
    taxonKey = key,
    limit = 100,
    hasCoordinate = TRUE,
    basisOfRecord = "PRESERVED_SPECIMEN",
    hasGeospatialIssue = FALSE,
    return = 'data'
  )
}
```

you're already using `dplyr::bind_rows`, then writing to disk. so that takes care of filling in columns for those data.frame's 

But maybe you mean you write many files to disk, and each file can have different columns?
if so, then before you write files to disk, or when you read them back in, just filter columns to the set you want, e.g., 

```r
columns_you_want <- c("species", "key")
dplyr::select(some_data_frame, columns_you_want)
```

**Comment by Xuletajr** [comment]
Hi scotte, 

thank you very much for your help and collaboration.
