### ISSUE TITLE
Cannot coerce "gbif" to a data.frame

### ISSUE THREAD

**Issue by Octoberweather** [ropensci/rgbif#377]
Hi, this is my first time posting in git-hub, please forgive errors.
I am working on trying to get occ_search data and creating a loop for every species in my species vector list. The rest of the code will write an individual csv file to a directory on my computer.

allpts <- vector('list', length(sps1))
names(allpts) = sps1

for (sp in sps1) { 
cat(sp, "\n")
allpts[[sp]] <- occ_search(scientificName = sp, return = 'data')
write.csv(allpts[[sp]], 
          paste("/Users/user/Desktop/DATA Bats/allpts_30sept/", 
                gsub(" ", "_", sp), ".csv", sep = ""))
}

When it comes across a species that does not have any occurrence data, I get the following error message:

Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""gbif"" to a data.frame

and the loop stops.
-I've tried adding an if and next capability to continue with the loop without terminating it, but that has not worked.
-I also tried installing as.gbif, but I get another error saying that it is not available for R 3.3.3

I would like to continue the loop without it terminating. Any ideas would be greatly appreciated, thank you!

**Comment by sckott** [comment]
👋 welcome and thanks for asking a question here. 

First, i'd strongly recommend upgrading your R version. R 3.3.3 is from March 2017, and you'll likely run into many problems updating any package you use. 

Second, if you just want the data.frame of occurrence results, `occ_data` should be faster. e.g., 

```r
z <- occ_data(scientificName = "Helianthus annuus", limit = 10)
z$data
```

Third, about searches with no data: there is a `NULL` value returned when there's no matching results. You can do a simple `if()` check on that, e.g. only write the csv file if the `data` slot is not `NULL`: 

```r
z <- occ_data(scientificName = "Helianthus annuus", limit = 10)
if (!is.null(z$data)) {
    write.csv(...)
}
```

**Comment by Octoberweather** [comment]
Hi Scott,
Thanks so much for your message, and nice to be part of github! I upgraded to R 3.6.1 and also input steps 2 and 3:

for (sp in sps1) {
cat(sp, "\n")
allpts[[sp]] <- occ_data(scientificName = sp, limit = 10)
allpts[[sp]]$data
if  (!is.null(allpts[[sp]]$data)) {
write.csv(allpts[[sp]], 
          paste("/Users/user/Desktop/DATA Bats/allpts_30sept/", 
                gsub(" ", "_", sp), ".csv", sep = ""))
}}

However, I'm still getting the same error message
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"gbif_data"’ to a data.frame

I really appreciate your help!

**Comment by sckott** [comment]
you need to include `$data` in `write.csv(allpts[[sp]]$data, ...)`, for the failure in write.csv, there are sometimes columns in the output from rgbif that are empty lists, to remove those you can do e.g., :

```r
allpts <- list()
for (sp in sps1) {
    cat(sp, "\n")
    allpts[[sp]] <- occ_data(scientificName = sp, limit = 10)
    df <- allpts[[sp]]$data
    if (!is.null(df)) {
        df <- df[, !apply(df, 2, function(z) is.null(unlist(z)))]
        write.csv(df, paste(gsub(" ", "_", sp), ".csv", sep = ""))
    }
}
```

**Comment by Octoberweather** [comment]
Thank you so much!!! This worked beautifully, but I got another error message:

Error in write.table(df, paste("/Users/user/Desktop/DATA Bats/allpts_30sept/",  : 
  unimplemented type 'list' in 'EncodeElement'

Here is my code. Thanks again for your help, so very appreciated!

for (sp in sps1)  {
cat(sp, "\n")
allpts[[sp]] <- occ_data(scientificName = sp, limit = 10)
df <- allpts[[sp]]$data
if  (!is.null(df)) {
  df <- df [!apply(df,2,function(df) is.null(unlist(df)))]
          write.csv(df, paste("/Users/user/Desktop/DATA Bats/allpts_30sept/", 
                              gsub(" ", "_", sp), ".csv", sep = ""))
  }
}

**Comment by sckott** [comment]
you should be able to see which name it failed on. i'd run that name manually through your code and see where the error is happening

**Comment by Octoberweather** [comment]
Thank you! I'll work on that :)

**Comment by Octoberweather** [comment]
Hello! we figured out a way to get this code working by adding a `df$networkKeys = NULL`:

`for (sp in sps1)  {
cat(sp, "\n")
allpts[[sp]] <- occ_data(scientificName = sp)
df <- allpts[[sp]]$data
df$networkKeys = NULL
if  (!is.null(df)) {
  df <- df[, !apply(df, 2, function(z) is.null(unlist(z)))]
  write.csv(df, paste("/Users/user/Desktop/DATA Bats/allpts_30sept/", 
                              gsub(" ", "_", sp), ".csv", sep = ""))
  }
}`

Thanks!

**Comment by sckott** [comment]
nice work!
