### ISSUE TITLE
Searching for an individual species error

### ISSUE THREAD

**Issue by Octoberweather** [ropensci/rgbif#380]
Hello, pretty new to github, so please excuse any errors.
I am writing code to pull `occ_data` from rgbif and using a loop search for every line.
Sometimes there is an error with one species, and the loop stops.

How can I search for which species gave the error in the console? Thank you.

**Comment by sckott** [comment]
thanks for your question. a for loop is best for that, e.g., 

```r
library(rgbif)
library(taxize)
nms <- taxize::names_list(rank = "species")
out <- vector(mode = "list", length = length(nms))
for (i in seq_along(nms)) {
  cat(nms[i], sep = "\n")
  out[[nms[i]]] <- occ_data(scientificName = nms[i], limit = 10)
}
```

then if an error happens you can tell that the last name that was printed had the problem and then you can run that name through `occ_data` by itself to see what might be wrong.

**Comment by Octoberweather** [comment]
thanks again Scott! Much appreciated, I'll try it and report back.
