### ISSUE TITLE
Examine dataset activity from rgbif

### ISSUE THREAD

**Issue by jtgiermakowski** [ropensci/rgbif#382]
Hello,

I'm trying to use the rgbif package to examine dataset activity. I can see plenty of activity via web and modify offset and limit to find hundreds of dataset uses at different points in time, e.g. 

[https://www.gbif.org/dataset/fb639e31-52eb-4998-afb1-984ee12aca0f/activity?offset=100&limit=200](https://www.gbif.org/dataset/fb639e31-52eb-4998-afb1-984ee12aca0f/activity?offset=100&limit=200)

I've tried using rgbif for the same purpose to no avail, it only returns the first 20 records: 

```
res <- occ_download_dataset_activity("fb639e31-52eb-4998-afb1-984ee12aca0f")
summary(res)
             Length Class  Mode   
offset        1     -none- numeric
limit         1     -none- numeric
endOfRecords  1     -none- logical
count         1     -none- numeric
results      20     -none- list   

```

I assume i need to pass some curlopts onto the command but don't know where to start...

Thanks in advance!

**Comment by sckott** [comment]
thanks for the issue - however, include the R session info [as requested](https://github.com/ropensci/rgbif/issues/new)

**Comment by jtgiermakowski** [comment]
Thank you for answering and sorry about that! Here's the info:



<details> <summary><strong>Session Info</strong></summary>

```r

sessionInfo() 

R version 3.4.3 (2017-11-30) 
Platform: x86_64-w64-mingw32/x64 (64-bit) 
Running under: Windows 7 x64 (build 7601) Service Pack 1  

Matrix products: default  
locale: 
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United States.1252      

attached base packages: 
[1] stats     graphics  grDevices utils     datasets  methods   base       

other attached packages: 
[1] rgbif_1.3.0  

loaded via a namespace (and not attached):  

[1] Rcpp_1.0.1        whisker_0.4       xml2_1.2.0        magrittr_1.5      munsell_0.5.0      
[6] colorspace_1.4-1  lattice_0.20-35   R6_2.4.0          rlang_0.3.4       stringr_1.4.0     
[11] httr_1.4.1        plyr_1.8.4        tools_3.4.3       grid_3.4.3        geoaxe_0.1.0      
[16] data.table_1.12.2 gtable_0.3.0      rgeos_0.4-3       lazyeval_0.2.2    httpcode_0.2.0    
[21] tibble_2.1.1      crayon_1.3.4      ggplot2_2.2.1     triebeard_0.3.0   curl_3.3          
[26] crul_0.8.4        sp_1.3-1          stringi_1.4.3     oai_0.2.2         compiler_3.4.3    
[31] pillar_1.4.2      urltools_1.7.3    scales_1.0.0      jsonlite_1.6      pkgconfig_2.0.3
--
 

```
</details>

**Comment by sckott** [comment]
thanks for that. 

i didn't have any parameters in that function for pagination - i'm adding those now, will push it up soon

**Comment by sckott** [comment]
@jtgiermakowski if you reinstall `remotes::install_github("ropensci/rgbif")`, restart R, and try it again, you should see that the fxn has limit and start params for doing paginatino.

**Comment by sckott** [comment]
oh, and the returned data is a list, with metadata and results each as a data.frame

**Comment by jtgiermakowski** [comment]
¡Fantastic! Thank you so much @sckott ! This will greatly enhance my ability to report on data use for our collection. The only thing I'd say is to up the limit a little bit. In order to get annual stats I had to create 4 iterative downloads. Downloads for each 1000 records sets range between 1.9 and 7.1 Mb... not too bad.
![Rplot](https://user-images.githubusercontent.com/2381228/67966663-e9bd3400-fbc9-11e9-9236-d322ce74e91a.jpeg)

Thanks again!

**Comment by sckott** [comment]
glad it worked. the pagination limits are on GBIF's side, so we can't change those. We could do looping internally for users of the pkg, as we do in `occ_search` but that makes its more complicated for us and more error prone

**Comment by jtgiermakowski** [comment]
No worries! Thanks again! This is great for the data provider community!
