### ISSUE TITLE
Is there a way to obtain GBIF occurence related multimedia.txt file ? 

### ISSUE THREAD

**Issue by yvanlebras** [ropensci/rgbif#383]
Is there a way to obtain GBIF occurence related multimedia.txt file from the rgbig package ?  It seems to me the answer is no but I prefer to ask.

Best,

**Comment by sckott** [comment]
yes there is. 

if you have the key for the download, you can do for example `occ_download_get("0000066-140928181241064")` and that downloads a zip file containing that file you want

if you want to construct a download query first, use `occ_download`, check when its ready `occ_download_meta`, then use `occ_download_get` to fetch it
