### ISSUE TITLE
occ_search: decimalLatitude and decimalLongitude gives ERROR

### ISSUE THREAD

**Issue by no-la-ngo** [ropensci/rgbif#388]
Following Code:
occ_search(taxonKey = 2481127,    
           hasCoordinate = TRUE,  
           year = 2010:2019       
           decimalLatitude = 65:80)

Gives this ERROR:
Error: unexpected symbol in:
"           year = 2010:2019       
           decimalLatitude"

But works fine without decimalLatitude.

<details> <summary><strong>> devtools::session_info()
- Session info -----------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Europe/Berlin               
 date     2019-12-19                  

- Packages ---------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.1)
 backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
 broom         0.5.2   2019-04-07 [1] CRAN (R 3.6.1)
 callr         3.3.2   2019-09-22 [1] CRAN (R 3.6.1)
 cellranger    1.1.0   2016-07-27 [1] CRAN (R 3.6.1)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.1)
 codetools     0.2-16  2018-12-24 [2] CRAN (R 3.6.1)
 colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.6.1)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.1)
 crul          0.9.0   2019-11-06 [1] CRAN (R 3.6.1)
 curl          4.3     2019-12-02 [1] CRAN (R 3.6.1)
 data.table    1.12.6  2019-10-18 [1] CRAN (R 3.6.1)
 DBI           1.0.0   2018-05-02 [1] CRAN (R 3.6.1)
 dbplyr        1.4.2   2019-06-17 [1] CRAN (R 3.6.1)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
 devtools      2.2.1   2019-09-24 [1] CRAN (R 3.6.1)
 digest        0.6.23  2019-11-23 [1] CRAN (R 3.6.1)
 dismo       * 1.1-4   2017-01-09 [1] CRAN (R 3.6.1)
 dplyr       * 0.8.3   2019-07-04 [1] CRAN (R 3.6.1)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
 fansi         0.4.0   2018-10-05 [1] CRAN (R 3.6.1)
 forcats     * 0.4.0   2019-02-17 [1] CRAN (R 3.6.1)
 fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.1)
 generics      0.0.2   2018-11-29 [1] CRAN (R 3.6.1)
 geoaxe        0.1.0   2016-02-19 [1] CRAN (R 3.6.1)
 ggplot2     * 3.2.1   2019-08-10 [1] CRAN (R 3.6.1)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.1)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 3.6.1)
 haven         2.2.0   2019-11-08 [1] CRAN (R 3.6.1)
 hms           0.5.2   2019-10-30 [1] CRAN (R 3.6.1)
 httpcode      0.2.0   2016-11-14 [1] CRAN (R 3.6.0)
 httr          1.4.1   2019-08-05 [1] CRAN (R 3.6.1)
 jsonlite      1.6     2018-12-07 [1] CRAN (R 3.6.1)
 lattice       0.20-38 2018-11-04 [2] CRAN (R 3.6.1)
 lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.6.1)
 lifecycle     0.1.0   2019-08-01 [1] CRAN (R 3.6.1)
 lubridate   * 1.7.4   2018-04-11 [1] CRAN (R 3.6.1)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.1)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
 modelr        0.1.5   2019-08-08 [1] CRAN (R 3.6.1)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 3.6.1)
 nlme          3.1-140 2019-05-12 [2] CRAN (R 3.6.1)
 oai           0.3.0   2019-09-07 [1] CRAN (R 3.6.1)
 pillar        1.4.2   2019-06-29 [1] CRAN (R 3.6.1)
 pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
 plyr          1.8.4   2016-06-08 [1] CRAN (R 3.6.1)
 png           0.1-7   2013-12-03 [1] CRAN (R 3.6.0)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.1)
 processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.1)
 purrr       * 0.3.3   2019-10-18 [1] CRAN (R 3.6.1)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
 raster      * 3.0-7   2019-09-24 [1] CRAN (R 3.6.1)
 Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.1)
 readr       * 1.3.1   2018-12-21 [1] CRAN (R 3.6.1)
 readxl        1.3.1   2019-03-13 [1] CRAN (R 3.6.1)
 remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.1)
 reprex        0.3.0   2019-05-16 [1] CRAN (R 3.6.1)
 rgbif       * 1.4.0   2019-10-30 [1] CRAN (R 3.6.1)
 rgdal         1.4-8   2019-11-27 [1] CRAN (R 3.6.1)
 rgeos         0.5-2   2019-10-03 [1] CRAN (R 3.6.1)
 rlang         0.4.2   2019-11-23 [1] CRAN (R 3.6.1)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.1)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.6.1)
 rvest         0.3.5   2019-11-08 [1] CRAN (R 3.6.1)
 scales        1.1.0   2019-11-18 [1] CRAN (R 3.6.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
 sp          * 1.3-2   2019-11-07 [1] CRAN (R 3.6.1)
 stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
 stringr     * 1.4.0   2019-02-10 [1] CRAN (R 3.6.1)
 testthat      2.3.1   2019-12-01 [1] CRAN (R 3.6.1)
 tibble      * 2.1.3   2019-06-06 [1] CRAN (R 3.6.1)
 tidyr       * 1.0.0   2019-09-11 [1] CRAN (R 3.6.1)
 tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.6.1)
 tidyverse   * 1.3.0   2019-11-21 [1] CRAN (R 3.6.1)
 triebeard     0.3.0   2016-08-04 [1] CRAN (R 3.6.1)
 urltools      1.7.3   2019-04-14 [1] CRAN (R 3.6.1)
 usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
 utf8          1.1.4   2018-05-24 [1] CRAN (R 3.6.1)
 vctrs         0.2.0   2019-07-05 [1] CRAN (R 3.6.1)
 whisker       0.4     2019-08-28 [1] CRAN (R 3.6.1)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.1)
 xml2          1.2.2   2019-08-09 [1] CRAN (R 3.6.1)
 zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.6.1)

[1] D:/R_Library
[2] C:/Program Files/R/R-3.6.1/library</strong></summary>

```r

```
Following Code:
occ_search(taxonKey = 2481127,    
           hasCoordinate = TRUE,  
           year = 2010:2019       
           decimalLatitude = 65:80)

Gives this ERROR:
Error: unexpected symbol in:
"           year = 2010:2019       
           decimalLatitude"

But works fine without decimalLatitude.

**Comment by sckott** [comment]
@no-la-ngo is this still a problem?

**Comment by no-la-ngo** [comment]
> 
> 
> @no-la-ngo is this still a problem?

No, I was just stupid.

**Comment by sckott** [comment]
ok
