### ISSUE TITLE
occ_download tests

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#395]
once we fix this vcr issue https://github.com/ropensci/vcr/issues/143 we should be able to test `occ_download`

**Comment by sckott** [comment]
see https://discourse.gbif.org/t/test-download-predicate-parsing/1701 for discussion of how to run download tests

**Comment by teuzindahuz** [comment]
Hi sckott,

are you currently working on the _occ_download_ function? Because I get an error that the _pred_ function do not exist.

**Comment by sckott** [comment]
@teuzindahuz  install the latest version from CRAN

**Comment by teuzindahuz** [comment]
@sckott , it is the version that I'm using. I also cannot find any documentation about "pred".

**Comment by sckott** [comment]
share the output of `sessionInfo()` or `sessioninfo::session_info()` after loading rgbif
