### ISSUE TITLE
Support recordedByID and identifiedByID

### ISSUE THREAD

**Issue by timrobertson100** [ropensci/rgbif#403]
Two new search terms `recordedByID` and `identifiedByID` have been added to the occurrence search API. These fields also appear in the DwC-A format of download in the `https://rs.gbif.org/terms/1.0/` namespace.

[This example](https://www.gbif.org/occurrence/taxonomy?recorded_by_id=https:~2F~2Forcid.org~2F0000-0003-1691-239X&identified_by_id=https:~2F~2Forcid.org~2F0000-0003-4710-2648&taxon_key=186&advanced=1) illustrates their use in the website and the API will operate as per other multivalue String fields.

@sckott, it would be wonderful if `rGBIF` could support these.

**Comment by sckott** [comment]
@timrobertson100 thanks for this. happy to
