### ISSUE TITLE
data.table::fread() and occ_download_import() crashes R for certain downloads

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#404]
A user on GBIF made the following download. 

```
occ_download(pred("basisOfRecord", "Literature"), user = user, pwd = password, email = email)
test.data.all.Literature <- occ_download_get("0032441-200221144449610", overwrite = TRUE) %>% 
occ_download_import() # R crashed when tried to run this
```
I was able to determine that the issue is related to `data.table::fread()`
https://github.com/ropensci/rgbif/blob/master/R/occ_download_import.R#L69

I manually unzip the downloaded folder and put it on my desktop
 
```
data.table::fread("C:/Users/ftw712/Desktop/0032441-200221144449610/occurrence.txt") # R crashes
readr::read_tsv("C:/Users/ftw712/Desktop/0032441-200221144449610/occurrence.txt") # import successful
```

**Comment by sckott** [comment]
thanks @jhnwllr for the report. We've had [a few issues with fread](https://github.com/ropensci/rgbif/issues?q=is%3Aissue+fread+is%3Aclosed). i went with data.table as I though it was the fastest option. i'll have another look and see if there's a one off bug here, or something else

**Comment by jhnwllr** [comment]
I noticed there were 239 tabs in the rows of that download, but 240 in the header row. So this could still be a GBIF issue...

**Comment by sckott** [comment]
that could very well be it, will report bac[](url)

**Comment by jhnwllr** [comment]
The tabs issue on the GBIF-side has now been fixed.
https://github.com/gbif/occurrence/issues/158

However, this download still causes rgbif to crash. Not sure why...

```
library(rgbif)
library(dplyr)
occ_download(pred("basisOfRecord", "Literature"), user = user, pwd = password, email = email)

occ_download_get("0034282-200221144449610", overwrite = TRUE) %>% 
occ_download_import() # R crashes 
```
Manually unzipping the file and reading it with `data.table::fread` does not cause a crash...
```
library(dplyr)
data.table::fread("C:/Users/ftw712/Desktop/0034282-200221144449610/occurrence.txt") %>% 
glimpse() # does not crash R 
```

**Comment by sckott** [comment]
it was caused by the `fill` parameter. it was default `fill=TRUE` - passed down to `data.table::fread`. If you set `fill=FALSE`  it should work just fine. 

I pushed a change so that `fill=FALSE` by default now - I think we'll still see problems now and then depending on the occurrence.txt file. I also updated the docs for `occ_download_import()` to make it clear that you can pass arguments on to `data.table::fread` in case of problems
