### ISSUE TITLE
gbif tibbles are not correctly constructed

### ISSUE THREAD

**Issue by lionel-** [ropensci/rgbif#412]
This is regarding https://github.com/tidyverse/dplyr/issues/5301.

We generally consider the manual construction of foreign classes to be undefined behaviour. Ideally you'd create the gdif tibbles using the tibble constructor like this:

```r
new_gbif <- function(x) {
  stopifnot(is.data.frame(x))
  tibble::new_tibble(
    out,
    nrow = nrow(out),
    class = "gbif"
  )
}

out <- tibble::as_tibble(name_usage_parse(out, data))

# Undefined behaviour
class(out) <- c('tbl_df', 'tbl', 'data.frame', 'gbif')

# Correct behaviour
out <- new_gbif(out)
```

However I see you're also creating a completely different sort of class with the same class name:

```r
out <- list(meta = get_meta_nu(out),
            data =  tibble::as_tibble(name_usage_parse(out, data)))
class(out) <- "gbif"
```

So I'm not sure what to do. Probably the tibble subclass needs a different class name, which may be a breaking change for your downstream dependencies.

**Comment by sckott** [comment]
Thanks much for this @lionel-
