### ISSUE TITLE
maybe drop `return` parameter across all functions

### ISSUE THREAD

**Issue by sckott** [ropensci/rgbif#413]
would greatly simplify the function. the majority use case is probably for getting just data, in which case they can use `occ_data()`. if they want hierarchies, facets, etc., they can just access that data from the output of `occ_search()`

**Comment by damianooldoni** [comment]
Hi @sckott . Well, it's not a bad idea to make things easy. I remember the problems I had to understand the first time the code behind it and the time spent to make my changes "return"-compatible. So, I agree with it. And stopping the function is way better than deprecating the use of `return`. 
Yes, it is a major change for sure. v3 is unavoidable.

**Comment by sckott** [comment]
> And stopping the function is way better than deprecating the use of return.

What do you mean by stopping?

**Comment by damianooldoni** [comment]
Well, terminating the execution of the function. Stopping as you wrote 'stop()` in the code :smile:

**Comment by sckott** [comment]
Ah okay. Thanks for the feedback.

**Comment by sckott** [comment]
all done, i think
