### ISSUE TITLE
occ_download_import with encoding UTF-8

### ISSUE THREAD

**Issue by bienflorencia** [ropensci/rgbif#414]
<details> <summary><strong>Session Info</strong></summary>

```r
- Session info -----------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Windows >= 8 x64     
...
rgbif       * 2.3      2020-05-28 [1] CRAN (R 3.6.3)       
```
</details>

This is not a bug, but I would just like to point out that the default encoding when importing DWCA data with 'occ_download_import' is not UTF-8, and in some cases it would fail to read strings with characters such as á, é, í, ñ. Therefore, the encoding option needs to be included in the call.

```r
# Works fine, but reads some names wrong
data_GBIF_DWCA  <- occ_download_import(key = "0082704-200221144449610") 

# For example, see the names in term recordedBy
occ_download_import(key = "0082704-200221144449610") %>% select(recordedBy)

# # A tibble: 5,138 x 1
# recordedBy      
# * <chr>           
# 1 MatÃ­as Zarucki  
# 2 Roderick Cameron
# 3 Santiago        
# 4 Santiago 

# When addding encoding, it works fine
occ_download_import(key = "0082704-200221144449610", encoding='UTF-8') %>% select(recordedBy)

# # A tibble: 5,138 x 1
# recordedBy      
# * <chr>           
# 1 Matías Zarucki  
# 2 Roderick Cameron
# 3 Santiago        
# 4 Santiago  
```

**Comment by sckott** [comment]
Thanks for the issue @bienflorencia 

`encoding` is passed on to `data.table::fread`. What do you mean by "needs to be included in the call"? Do you mean add `encoding` parameter to `occ_download_import`  as a parameter so its more obvious to the user?  Or do we instead document it better in the manual file for this function?

**Comment by bienflorencia** [comment]
Thanks for your reply @sckott. Sorry, I meant that for the `occ_download_import` to read and import the data without errors of this type the parameter `encoding` needs to be added (I'm not sure what's the default encoding, 'unknown' maybe). Therefore, it could be useful to mention this option in the documentation as you suggested. Perhaps giving some examples in [Problems reading data](https://docs.ropensci.org/rgbif/reference/occ_download_import.html#problems-reading-data) with `data.table::fread()` ? Maybe it is not that necessary anyway. It just seems like an error that most people would not stop at because the data is imported anyway although some terms such as people and locality names can get corrupted

**Comment by sckott** [comment]
yes, default encoding set by `fread` is "unknown". 

Does UTF-8 encoding work for your use cases?

I could add encoding as a parameter to make it very obvious that users can adjust that. and make the default UTF-8

**Comment by bienflorencia** [comment]
Yes, UTF-8 works for me and I believe it may also do for most cases. So, adding the parameters with UTF-8 as default sounds ok. Thanks !
