### ISSUE TITLE
Error in occ_download_get(GBIF_download)?

### ISSUE THREAD

**Issue by cihluk** [ropensci/rgbif#422]
Lately when trying to use occ_download_get I'm having this error:
Error in occ_download_get(GBIF_download) :    res$response_headers$`content-type` == "application/octet-stream; qs=0.5" is not TRUE

But just a few days before it was working normally. Sorry if this question shouldn't be here.

**Comment by jhnwllr** [comment]
I think the issue is due to...
https://github.com/ropensci/rgbif/blob/master/R/occ_download_get.r#L40-L41

I think it should be 

**Should Be** : "application/octet-stream; **q**=0.5"
**Not** : " application/octet-stream; **qs**=0.5"

```
library(rgbif)

r = httr::GET("http://api.gbif.org/v1/occurrence/download/request/0082560-200221144449610")

httr::headers(r)$`content-type` == "application/octet-stream; q=0.5"
httr::headers(r)$`content-type` == "application/octet-stream; qs=0.5"
```

**Comment by sckott** [comment]
thanks both. fixing now
