### ISSUE TITLE
occ_get function is not working

### ISSUE THREAD

**Issue by clagfontes** [ropensci/rgbif#426]
Hello, I"ve just started using this function.

I would like to get the Lat and Log data for 20 Oak species.

When I search in the GBIF database I find that the taxon key for one of the species (Quercus agrifolia)  is 2878213.
When I use the function 
> occ_search(scientificName = "Quercus agrifolia", limit = 300)
or
> occ_count(taxonKey=2880791, georeferenced=TRUE)

It works. However when I try to get the coordinates with:

> occ_get(key=2878213)

 I receive an error message: "Error: Entity not found for uri: /"

Any ideas of what may be the problem?

Thank you!

**Comment by sckott** [comment]
session info please, as requested

**Comment by sckott** [comment]
that's a taxon key. `occ_get` wants an occurrence key
