### ISSUE TITLE
"Cleaning data" is misleading

### ISSUE THREAD

**Issue by Mesibov** [ropensci/rgbif#432]
"Cleaning data using GBIF issues"

"rgbif now has the ability to clean data retrieved from GBIF based on GBIF issues. These issues are returned in data retrieved from GBIF, e.g., through the occ_search() function. Inspired by magrittr, we've setup a workflow for cleaning data based on using the operator %>%. You don't have to use it, but as we show below, it can make the process quite easy."

This confuses filtering with cleaning. While it's possible for a GBIF data user to find records with issues and then fix the issues, the "cleaning" examples only filter the record set, i.e. delete records with issues. The quality of the dataset isn't improved by deletion, as it is by cleaning. Instead, a new, smaller dataset is generated with less information than was present in the original, larger dataset.

How would you re-title and re-word your usage guide to make it less misleading?

**Comment by sckott** [comment]
I'll consider changing wording

**Comment by jhnwllr** [comment]
Everyone's level of dirty is different there is no reason not to use the term "cleaning". Is not misleading in my opinion.

**Comment by Mesibov** [comment]
The Atlas of Living Australia does exactly what rgbif does: allow the user to remove from view/access those records that have ALA-detected issues. ALA calls this "filtering", not "cleaning":

[https://www.ala.org.au/blogs-news/helping-you-search-and-filter-data-in-the-ala/](https://www.ala.org.au/blogs-news/helping-you-search-and-filter-data-in-the-ala/)

This is not a matter of semantics or hair-splitting. If you discard records from a dataset, you lose information. If you clean records in a dataset, you gain information.

**Comment by Mesibov** [comment]
You're a businessman with a customer database. You take the database to a data cleaning service like this one:

[https://www.experian.com.au/data-cleaning-services
](https://www.experian.com.au/data-cleaning-services
)
You get the database back, but it has many fewer customer records.
"What happened to my customer records?" you ask.
"We threw out the ones with misspellings, incomplete data, out-of-date data and data items not in the right order", says the service operator.
"But I thought you did data cleaning?" you ask.
"That's what we mean by cleaning", replies the operator.
"I thought _data cleaning is the process of modifying data to ensure that it is free of irrelevances and incorrect information. Also known as data cleansing, it entails identifying incorrect, irrelevant, incomplete, and the "dirty" parts of a dataset and then replacing or cleaning the dirty parts of the data_". [See link below]
"No, we don't modify data. We just remove the dirty bits. That's what we call cleaning."

 [https://www.formpl.us/blog/data-cleaning](https://www.formpl.us/blog/data-cleaning)
