### ISSUE TITLE
count_facet() `key` and `basisOfRecord`

### ISSUE THREAD

**Issue by andzandz11** [ropensci/rgbif#436]
I am using the function `count_facet()` to supply a plant family key and I want to see all countries that plant can be found in (as in: biologically meaningful).
Unfortunately there are a lot of non-natural "occurences" in the database with "Localitiy" like:
`Missouri Botanical Garden`
or:
`City of Santa Monica. Wild Oats Community Market`

So I tried to exclude all `basisOfRecord = c("FOSSIL_SPECIMEN", "LITERATURE",  "PRESERVED_SPECIMEN",  "UNKNOWN")`

But it seems I cannot set `key` and `basisOfRecord` at the same time. Any idea of any other way to get rid of all that nonsense data? I am checking 200 plant families world-wide, so I would like to avoid to download the whole occurence dataset and filter it.

Here is an example of hits I want to exclude: 
https://www.gbif.org/occurrence/search?geometry=POLYGON((-125.23856%2029.52960,-69.04453%2029.52960,-69.04453%2052.02960,-125.23856%2052.02960,-125.23856%2029.52960))&has_coordinate=true&has_geospatial_issue=false&occurrence_status=present&taxon_key=2439

**Comment by sckott** [comment]
Previously, it wasn't allowed to submit basisofrecord and a taxonkey together in the samee query for this GBIF api service. It does appear to be allowed now. I'll push an update soon

**Comment by sckott** [comment]
if you reinstall you should be able to set key and basisofrecord together now

**Comment by andzandz11** [comment]
That really helps my project a lot!
