### ISSUE TITLE
download redirect

### ISSUE THREAD

**Issue by dnoesgaard** [ropensci/rgbif#439]
Hey, just wanted to make sure you saw this:

> We've made a small change to the way files are downloaded from 
> GBIF.org.  People retrieving GBIF downloads using a web browser will not 
> notice any difference.  There will also be no difference for many 
> command line download programs, like "wget".
> 
> API clients will notice that download links like 
> https://api.gbif.org/v1/occurrence/download/request/0001649-180925134338326.zip 
> now return an HTTP 302 redirect to a different location.  The client 
> will need to follow the redirect to retrieve the file. Users of "curl" 
> on the command line can add the "-L" argument to follow redirects 
> automatically.
> 
> The change was necessary to improve stability and performance of 
> api.gbif.org, following the change by Google Chrome to block non-HTTPS 
> downloads.  The default for download links is now HTTPS, but files (and 
> all of api.gbif.org) can still be accessed using only HTTP if preferred.

Not sure if occ_download is affected...

**Comment by sckott** [comment]
Thanks, i saw the mailing list email. Seems to be working already without any changes
