### ISSUE TITLE
occ_data returned values shuffled

### ISSUE THREAD

**Issue by andzandz11** [ropensci/rgbif#441]
I am using `occ_data` to download occurrence data for a couple of plant families. Unfortunately the output is a little bit inconsistent.

For example: Sometimes the "countryCode" value is listed before "locality" and sometimes it is listed after. This makes it very difficult to handle the data. 

Some of the column names are missing and some are repositioned.

Here is an example of matching the colnames of 2 queries:

```

cocc[[63]] <- occ_data( taxonKey = 2398, hasCoordinate= TRUE,  limit = 100000)
cocc[[83]] <-  occ_data( taxonKey = 7709, hasCoordinate= TRUE,  limit = 100000)

> match(cocc[[63]]$data %>% as.data.frame %>% colnames, cocc[[83]]$data %>% as.data.frame %>% colnames)
  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
 [29]  29  30  31  32  33  34  35  36  37  39  40  41  42  44  46  47  48  62  61  64  76  56  57  68  49  50  38  43
 [57]  45  51  52  53  54  55  58  59  60  63  65  66  69  67  NA 118 121  NA 126 133  94  95  NA  75 122 109 111 112
 [85]  NA  91  92 123 108 113 140  70 117 119  71  98 130 107 110 129  NA 128  93  74  72  73 100  NA  NA 125 127 132
[113]  77  78  84  85  NA  90 137  NA  NA  96 105 136 139  NA  NA  NA  NA  NA 135 124 101 102 103 131  NA  97  NA  79
[141]  80  82  87  NA  89  86 138  NA  NA  99 114  NA  NA  NA  NA  NA  NA  NA  NA  NA 115 116  NA  NA  88
```

Any idea? Not sure where the problem is.

**Comment by sckott** [comment]
Some background: GBIF (correctly; to make returning data faster b/c the "payload" is smaller) returns only fields (columns of the response data.frame here) for which they have data - that is, they remove empty fields before returning data to us.  That leads to variable data.frame columns in R. We could try just fill in NA's for entire columns or cells that are missing/empty, but GBIF can remove/add new fields at any point and break rgbif. 

What is the exact problem? I assume you want to combine data.frame's from different queries. If so, that can be done e..g, like

```r
library(rgbif)
x <- occ_data(taxonKey = 2398, hasCoordinate = TRUE, limit = 10)
y <- occ_data(taxonKey = 7709, hasCoordinate = TRUE, limit = 10)
dplyr::bind_rows(list(x$data, y$data))
data.table::rbindlist(list(x$data, y$data), fill=TRUE)
```

**Comment by andzandz11** [comment]
Yes I understand they remove NA fields. I was wondering why the order of the fields not consistent between queries.

I acutally was trying to cut off some of the fields, and only keep the fields up to the "locality" `grepl("localiy", rownames(cocc[[63]])` , because I don't need all of them. But that didn't work becuase they flip around and then I was missing something I needed.

On the other hand I would rather try to avoid putting the names of all the fields I want in my script, because if just one name is changing, the script will break.

**Comment by sckott** [comment]
I would not recommend referencing columns/fields by their number position in general. Referencing by name is much safer.

> I agree, and for that reason I would like to try to avoid putting the actual names of all the fields I want to keep/discard in my script 

You can still reference columns by name even if they are not found if you do it in a safe way, e.g., 

```r
# doesn't work, columns not found
mtcars[,c("foo", "bar")] 

# select columns that exist first, then select columns from df
cols <- names(mtcars)[names(mtcars) %in% c("cyl", "vs", "foo", "bar")]
mtcars[,cols]

# a dplyr solution
library(dplyr)
mtcars %>% select_if(names(.) %in% c('cyl', 'vs', 'foo'))
```

**Comment by andzandz11** [comment]
Thank you for your help. I know how to solve that problem in my specific case, that was not why I made this issue. In general, I  think it is weird behaviour for a function to return data structures where the order of the cols is shuffled around depending on the parameter you feed into the function. Just imagine SQL queries would return data cols in a random order every time. It is not expected behaviour, I did not expect it for sure because everything else in this package is so fantastically coded.

**Comment by sckott** [comment]
There's at least 3 reasons the columns are not ordered:

- It just hasn't come up before, at least that I can remember
- I don't think it's a good idea to reference columns by number, and I'm not alone here
- GBIF can change order of the fields - that becomes order of the columns

Note that I do push some columns to the far left of the data.frame so they are more easily visible, so a few "important" columns are in the same order

The SQL analogy isn't quite right since SQL isn't pulling data from a source (here, GBIF) that can change the underlying data

Having said that I may try to order them if easy enough/unlikely to cause bugs
