### ISSUE TITLE
occ_search function returning error randomly with various taxa and limits after update

### ISSUE THREAD

**Issue by RussellGrayxd** [ropensci/rgbif#443]
Random issues after update with occ_search function errors.

**reprex:**
taxa <- name_suggest(q = "Trigonobalanus", rank = "genus")
key = taxa$data$key    
occ_search(taxonKey = key, hasCoordinate = TRUE)

**Error produced**
"Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0"

**Also.... This works**
taxa <- name_suggest(q = "Trigonobalanus", rank = "genus")
key <- taxa$data$key   
dat <- occ_search(taxonKey = key, limit=8)

**This doesn't**
taxa <- name_suggest(q = "Trigonobalanus", rank = "genus")
key <- taxa$data$key   
dat <- occ_search(taxonKey = key, limit=10)

**Comment by sckott** [comment]
Thanks for the issue. In the future please share your R session info, and terms like "after update" without context don't help me much. Update from what to what?

**Comment by RussellGrayxd** [comment]
Sorry, there was an update to the package on 2020-12-03 according to CRAN. Around that date is when these issues started occurring. I figured saying after the update would have been sufficient. I was wrong. 
Best,
-RG
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 

0934581341 |  rjgrayecology@gmail.comhttps://www.rjgrayecology.com/
705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168

 |
| 
 |
|  |

 

    On Monday, December 7, 2020, 11:36:36 p.m. GMT+7, Scott Chamberlain <notifications@github.com> wrote:  
 
 


Thanks for the issue. In the future please share your R session info, and terms like "after update" without context don't help me much. Update from what to what?

**Comment by sckott** [comment]
should work now. `remotes::install_github("ropensci/rgbif")`

**Comment by RussellGrayxd** [comment]
Thanks! Works perfectly again!
