### ISSUE TITLE
occ_download with coordinateUncertaintyInMeters

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#449]
Hello I am back with another `occ_download` question. 

GBIF now has a download filter for **coordinateUncertaintyInMeters**.  Wondering if there is a way to do it with rgbif.

```R
library(rgbif)

occ_download(
pred_lt("coordinateUncertaintyInMeters",10000),
format = "SIMPLE_CSV",
user=user,pwd=pwd,email=email
)
```
> Error: 'key' not in acceptable set of keys; see ?occ_download
Execution halted

I am guessing it is related to not being in the key lookup: 
https://github.com/ropensci/rgbif/blob/master/R/download_predicate_dsl.R#L248

**Comment by sckott** [comment]
Thanks for this. Looking

**Comment by sckott** [comment]
Please try again after reinstalling like `remotes::install_github("ropensci/rgbif")` and it should work now
