### ISSUE TITLE
Inquiry about the argument issue in occ_search function

### ISSUE THREAD

**Issue by YaquanChang** [ropensci/rgbif#451]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by YaquanChang** [comment]
Hi, when I tried occ_sesarch function to check species occurrence data, I found some species get the error: Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : arguments imply differing number of rows: 1, 0. Could you help me to fix it? Here is my code for example: occ_search(scientificName = "Abrus pulchellus").
Thanks in advance ,
Yaquan

**Comment by sckott** [comment]
In the future, always share your `sessionInfo()` (or `sessioninfo::session_info()`)

Most likely you have an older version of the package. reinstall from CRAN and it should be fixed

**Comment by YaquanChang** [comment]
Many thanks for the suggestion. I just realized that problem and download the package again from GitHub and it worked!
