### ISSUE TITLE
occ_search error with different limits values

### ISSUE THREAD

**Issue by jresasco** [ropensci/rgbif#456]
Hello! 

I'm getting an error with the occ_search function that seems to be associated with the limit value. It happens for some species but not others. For example, for the species "Oxytropis deflexa", the function executes when the limit is set at 2 but not 20. See below. 

Thank you!

Julian

occ_search(scientificName= "Oxytropis deflexa", 
           geometry='POLYGON((-106 38.4,-106 41,-104.7 41,-104.7 38.4,-106 38.4))', 
            hasCoordinate = T, limit = 20)

Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0

occ_search(scientificName= "Oxytropis deflexa", 
            geometry='POLYGON((-106 38.4,-106 41,-104.7 41,-104.7 38.4,-106 38.4))', 
            hasCoordinate = T, limit = 2)
Records found [52] 
Records returned [2] 

##########
##Session Info
##########
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgbif_3.3.0   maps_3.3.0    dismo_1.1-4   elevatr_0.3.4 raster_3.3-13
[6] sp_1.4-5

**Comment by sckott** [comment]
Thanks for opening an issue! 

Can you install the latest version of rgbif from CRAN?  `install.packages("rgbif")` After installing, then restarting R you should have rgbif version `3.5.2`. Then try again, it should be fixed in that version

**Comment by jresasco** [comment]
Ah! Thanks for the quick response Scott. That did the trick.

**Comment by sckott** [comment]
great, glad it worked!
