### ISSUE TITLE
occ_search and occ_data don't return establishmentMeans

### ISSUE THREAD

**Issue by SarahSW155** [ropensci/rgbif#457]
Hello,

In the doc of the functions occ_search and occ_data is an argument called "establishmentMeans". But when I use the functions, no column with that name is returned. When using the argument "fields = c("species", "establishmentMeans"), only the "species" column is returned without warning or error.

When googling I found this post: https://discuss.ropensci.org/t/rgbif-occ-download-argument-establishmentmeans/2174
and it seems like the argument works for occ_download.

Do you know what's going on?

Just an example for species Anolis cristatellus:
data <- occ_search(taxonKey =  2467091,
                                 fields = c("species", "establishmentMeans", "decimalLatitude"),
                             hasCoordinate = T,
                             limit = 3000)
returns a list in which there is a 2 column "data" dataframe containing only "species", and "decimalLatitude".

Best,

Sarah

<details> <summary><strong>Session Info</strong></summary>

```r

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

other attached packages:
[1] rgbif_3.5.2.93

```
</details>

**Comment by SarahSW155** [comment]
Hi,

Sorry, I was just wondering if you think that there's a 'quick' solution to this problem? If there isn't, no worries, just please let me know and I'll continue my analysis without waiting for a solution to this problem.

Best regards,

Sarah

**Comment by sckott** [comment]
sorry, i'm on leave right now. i'll get back to you in a couple of weeks

**Comment by SarahSW155** [comment]
Thank you very much for letting me know!

**Comment by sckott** [comment]
If an occurrence record (a row of the results from `occ_search`/`occ_data`) does not have an entry for a column then that data is not returned from GBIF. So `establishmentMeans` must not be available or filled in for records you are getting back. You may want to ask GBIF about that. I don't know why they'd be missing for that taxon specifically

**Comment by dnoesgaard** [comment]
establishmentMeans is only available for a small fraction of records (<20M), the majority of which are birds.

**Comment by SarahSW155** [comment]
Ah, okay that makes sense! Thanks for looking into that.

**Comment by sckott** [comment]
Thanks @dnoesgaard !
