### ISSUE TITLE
missing `stateProvince` predicate key?

### ISSUE THREAD

**Issue by mikeroswell** [ropensci/rgbif#458]
Package is cool, thanks for figuring out all the tricks to get downloads of different sizes without making GBIF too angry!

I'm wondering if there is a missing predicate key for "stateProvince." 

I can filter by state/province in `occ_search()`: `andrenaOcc<-occ_search(scientificName ="Andrena", stateProvince ="Maryland", limit = 1e4)`

but teeing up an `occ_download()`, `pred("stateProvince", "Maryland")` returns "Error: 'stateProvince' not in acceptable set of keys; see ?download_predicate_dsl"

**Comment by sckott** [comment]
@jhnwllr do you know if there's a stateprovince key?

**Comment by dnoesgaard** [comment]
There is: `STATE_PROVINCE`

**Comment by sckott** [comment]
thanks @dnoesgaard for that

@mikeroswell sorry for the delay on this - was on family leave. 

try again after reinstalling from github `remotes::install_github("ropensci/rgbif")` - should be up to cran next week
