### ISSUE TITLE
typo in a grepl() statement

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rgbif#460]
Hi @sckott! 

I found a little typo which could lead to a broken functionality if multipoints are passed. 
Should it not be `multipoint` instead of `mulitpoint` at the end of https://github.com/ropensci/rgbif/blob/master/R/download_predicate_dsl.R#L294?

**Comment by sckott** [comment]
Thanks! Yes, that is a typo that could lead to problems. I'll fix
