### ISSUE TITLE
for occ_download add GADM_GID as download predicate key

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#462]
Support needed for `GADM_GID` download predicate key. 

Not found in `key_lkup`
https://github.com/ropensci/rgbif/blob/master/R/download_predicate_dsl.R#L261

example download using GADM_GID
https://www.gbif.org/occurrence/download/0261011-200613084148143

gadm reference: 
https://gadm.org/index.html

**Comment by sckott** [comment]
Thanks, will do

**Comment by sckott** [comment]
@jhnwllr reinstall - and let me know if it works now as expected

**Comment by jhnwllr** [comment]
@sckott yes this works for me now thanks!!

```r
library(rgbif)

user="jwaller"
pwd=""
email="jwaller@gbif.org"


occ_download(
pred("gadm", "VAT"),
format = "SIMPLE_CSV",
user=user,pwd=pwd,email=email
)
```

https://www.gbif.org/occurrence/download/0280707-200613084148143
