### ISSUE TITLE
predicate key missing for OCCURRENCE_STATUS

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#465]
`occ_download` is missing a predicate key for **OCCURRENCE_STATUS** which allows users to only select "present records" (not absent records). 

"OCCURRENCE_STATUS = present" is the default option for downloads from the gbif web portal. 

https://www.gbif.org/occurrence/search?occurrence_status=present&q=

download example: 

```json
    {
      "type": "equals",
      "key": "OCCURRENCE_STATUS",
      "value": "present",
      "matchCase": false
    },
```

https://github.com/ropensci/rgbif/blob/master/R/download_predicate_dsl.R#L264-L278

**Comment by sckott** [comment]
doing now
