### ISSUE TITLE
occ_download_get() issue

### ISSUE THREAD

**Issue by DavidAClarke** [ropensci/rgbif#468]
I am trying to download the results of an `occ_download` using `occ_download_get`, however, I am getting the following error:
`Error in occ_download_get("0299151-200613084148143") :
    response content-type != application/octet-stream; q=0.5`

Do you know why such an error is occurring? FYI I used `format = "SIMPLE_CSV"` when creating my download in `occ_download` if that is relevant. 

I have attached my session information.
[sessionInfo.txt](https://github.com/ropensci/rgbif/files/6684806/sessionInfo.txt)

Thanks

**Comment by jhnwllr** [comment]
Hello. You might need to use the latest version of `rgbif.` 

```r 
library(rgbif)
occ_download_get("0299151-200613084148143")

sessionInfo()
`rgbif_3.6.0`

```
works for me on the latest CRAN version of rgbif.

**Comment by DavidAClarke** [comment]
Hi John. Thanks very much for that, updating the rgbif package did the trick.
