### ISSUE TITLE
Possible bug in occ_download_get()

### ISSUE THREAD

**Issue by aeiche01** [ropensci/rgbif#469]
I'm getting an error when I run the occ_download_get() function. This same code (with absolutely no changes) worked before with no problems until about a week ago, and the error makes it seem like the issue is on the servers somewhere?

The error looks like this:

`Error in occ_download_get(res, overwrite = TRUE) : 
  response content-type != application/octet-stream; q=0.5`

I'm running 
`res<-occ_download("bunch of stuff selecting particular species")`
just fine, and coming out with a success. It just seems that when I run occ_download_get() the computer runs into problems. I've attempted this on two different computers (mac and PC) and I get the same error for both of them.

Best
Adam

**Comment by jhnwllr** [comment]
You might want to try updating to the new version of `rgbif`, if you have not already. 

Could you paste in your `sessionInfo()`?
