### ISSUE TITLE
occ_download_import with 'select'

### ISSUE THREAD

**Issue by PLREY** [ropensci/rgbif#479]
Dear Scott, I would like to select few columns with the occ_download_import function using the 'select' argument of fread (see below)
`sp.gbif<-occ_download_import(res2,select=c("species","infraspecificEpithet","year","decimalLongitude","decimalLatitude"),quote="")`

but I don't know why, I have this error report:
```
Error in `$<-.data.frame`(`*tmp*`, "countryCode", value = character(0)) : 
  replacement has 0 rows, data has 258319
```
However it's work when I use this function without 'select' argument.

The rgbif package used is the last version

```
- Session info --------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.5 (2021-03-31)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  French_Switzerland.1252     
 ctype    French_Switzerland.1252     
 tz       Europe/Berlin               
 date     2021-09-18                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 rgbif       * 3.6.0   2021-06-02 [1] CRAN (R 4.0.5)
```

and when I test to import a data directly with 'fread' function I have any problem to use the argument 'select'. 

Can you help me to understand (and correct) the issue please?
Sincerly, 
Pierre-Louis Rey, 
PhD student.

**Comment by jhnwllr** [comment]
Hello I am the new **rgbif maintainer**. 

This was a bug. It is now **fixed in the development version**. 

If you install the development version,

```R
pak::pkg_install("ropensci/rgbif")
# OR
install.packages("rgbif", repos="https://dev.ropensci.org")
```

then this should work...

```R
library(rgbif)

res = occ_download_get(key="0004145-210914110416597", overwrite=TRUE) 
occ_download_import(res, select=c("species","infraspecificEpithet","year","decimalLongitude","decimalLatitude"),quote="")
```
