### ISSUE TITLE
Download multiple species 

### ISSUE THREAD

**Issue by KevinLopezReyes** [ropensci/rgbif#480]
Hi everyone, my name is Kevin,

I am trying to download multiple species records from a family key. However, I have almost 800,000 records of approximately 750 species and the code limits it to 500 records. I have thought of various options to fix it, but none have worked. I would also like to be able to save the species in individual csv files with their respective records, but instead, I save it in a single file with all the species together, I would appreciate your help since I am new to programming languages,

Thank you very much, this is my script 
```r


name_backbone(name = "Hylidae", rank = "family", kingdom = "animalia")


records <- occ_search(familyKey = 6735, hasCoordinate = TRUE, limit = 1000000)
View(records$data)
dat <- records$data
setwd("C:/Users/IGNITER/Desktop/prueba")
write.csv(dat,file="Hyl.csv", row.names = FALSE)
```
</details>

**Comment by dnoesgaard** [comment]
Hi Kevin.

I would strongly suggest taking the asynchronous download route and using occ_download(). It has no limits on number of records. Query syntax is bit different and you'll need to specify a GBIF.org username and password for this function, so start by creating an account first, if you don't have one.

Once the download is ready, you can use occ_download_get() and occ_download_import() to load the records into R. 

```
> my_query<-pred_and(pred("taxonKey", 6735),pred("hasCoordinate","TRUE"))
> my_dl<-occ_download(my_query,user="yourusername",pwd="yourpassword",email="youremail")
> dl<-occ_download_get(my_dl)
> records<-occ_download_import(dl)
```

**Comment by KevinLopezReyes** [comment]
Hello, thank you very much for your prompt response. I already tried the code and it worked perfect for me, I thank you very much, greetings!
