### ISSUE TITLE
Add continent field to iNaturalist?

### ISSUE THREAD

**Issue by bhanberry** [ropensci/rgbif#482]
Hello, 

Is it possible to add a continent field to iNaturalist data? These are filtered out currently with a continent query.

Thanks, Brice

```r

```
</details>

**Comment by dnoesgaard** [comment]
You would need to ask iNaturalist about this as this is a publisher-controlled field.

Be aware that only around 15% of occurrences in GBIF have the continent field filled out, so probably better to find another solution. You may also consider suggesting that GBIF add this value during interpretation: https://github.com/gbif/portal-feedback

**Comment by bhanberry** [comment]
Thanks! I added 18 countries but it took some time to become aware of the continent problem.
