### ISSUE TITLE
gbif_citation()

### ISSUE THREAD

**Issue by dnoesgaard** [ropensci/rgbif#494]
While I appreciate the idea of gbif_citation(), creating a derived dataset is—from a GBIF point of view—a better solution to citing data retrieved using the synchronous functions.

Let's figure out a way of making this clear(er) to users. Thoughts?

**Comment by jhnwllr** [comment]
As far as I am concerned, we can do whatever you want with `gbif_citation()`. To be honest, I have never used it before, so I would have to look into how it is even functioning.

**Comment by dnoesgaard** [comment]
Ok, we can use this issue for collecting specific ideas.

**Comment by jhnwllr** [comment]
We could deprecate the part that is connected to generating citations from `occ_data` and `occ_search`. Pointing users to derived datasets instead.

**Comment by jhnwllr** [comment]
We can also write a vignette on how to cite GBIF data from rgbif. After we make the changes.

**Comment by jhnwllr** [comment]
What do you think about this? 

```r
gbif_citation(occ_search(taxonKey=9206251, limit=2))
gbif_citation(occ_data(taxonKey=9206251, limit=2))
```

> gbif_citation() for occ_search() and occ_data() is deprecated.
Use rgbif::derived_dataset() instead.

The other `gbif_citation` methods will return the same as they always have.

**Comment by dnoesgaard** [comment]
I think that's a good idea, but I would like to make sure we have good enough documentation for derived_dataset() before we deprecate the functionality.

**Comment by dnoesgaard** [comment]
Great work on the [Citing GBIF-mediated data](https://docs.ropensci.org/rgbif/articles/gbif_citations.html) article. This will be a great resource to direct people to. I wonder if we should link to this from our general [citations guidelines](https://www.gbif.org/citation-guidelines)?

**Comment by jhnwllr** [comment]
I agree it could be linked from the main citation guidelines article.
