### ISSUE TITLE
Update documentation for Basis of Record values

### ISSUE THREAD

**Issue by MattBlissett** [ropensci/rgbif#499]
We're updating the basis of record values to align with the latest version of Darwin Core.

https://rs.gbif.org/sandbox/vocabulary/dwc/basis_of_record_2022-01-24.xml

MaterialCitation essentially replaces Literature, and Occurrence replaces Unknown.

I would edit this myself, but https://github.com/ropensci/rgbif/blob/dev/man/occ_data.Rd#L1-L2 warns me not to, and I don't see the relevant lines in https://github.com/ropensci/rgbif/blob/dev/R/occ_data.R

**Comment by jhnwllr** [comment]
Documentation is inline so you can edit on the actual function file: 
https://github.com/ropensci/rgbif/blob/dev/R/occ_data.R

**Comment by jhnwllr** [comment]
template appears to be in here somewhere
https://github.com/ropensci/rgbif/tree/8cf2f937eca5933869ce2a0bc47cc349ebcce241/man-roxygen
