### ISSUE TITLE
Setting record limits in occ_download

### ISSUE THREAD

**Issue by meaghanregina** [ropensci/rgbif#508]
Is there a way to set a limit to the number of records to download for multiple species when using occ_download? For smaller queries, I have used occ_data and can set 'limit'. Now with a bigger query (~750 species), I want to similarly limit the records, but can't figure out the best way to do so. Thanks in advance!

**Comment by jhnwllr** [comment]
Unfortunately there is no way to do this with `occ_download()`. Can I ask why you only want a limited amount of records?
