### ISSUE TITLE
name_backbone_checklist() ideas 

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#515]
I think there should be a way to input constant values instead of having a data.frame with repeated values in a similar way that name_backbone works now. Also would be nice if you could keep your verbatim data somehow.

**Comment by damianooldoni** [comment]
Yes, definitely.

My two cents about the second idea:
> Also would be nice if you could keep your verbatim data somehow.

Yes, it would be nice. Here below how I see the output in my mind:

- a list of two: `.$data` and `.$verbatim`, where the verbatim data are in slot `verbatim` of course 

I would also remove the argument `verbatim` from the args.
