### ISSUE TITLE
occ_search(fields="minimal"...) should include datasetKey

### ISSUE THREAD

**Issue by dnoesgaard** [ropensci/rgbif#517]
Users can request "minimal" fields using

`> occ_search(taxonKey=x, fields="minimal")`

but this also means they won't get datasetKey and thus can't cite properly.

- [ ] Consider including datasetKey for `fields="minimal"` queries

**Comment by jhnwllr** [comment]
Thanks @dnoesgaard. 

Include datasetKey in minimal fields.

**Comment by jhnwllr** [comment]
https://github.com/ropensci/rgbif/commit/8d6e37cf14bdf90faa1bc6654ea18e67fca3fbb4
