### ISSUE TITLE
Documentation question: what is `confidence` in `name_` search return?

### ISSUE THREAD

**Issue by mikeroswell** [ropensci/rgbif#538]
Hi! This is fundamentally a question about the GBIF API but perhaps implies a feature request for your package documentation anyways: What is going on with the `confidence` field in the object returned by the `name_*` searches? 

Based on [this link](https://api.gbif.org/v1/species/match?verbose=true&kingdom=Plantae&name=Oenante), I can see that it adds the scores for matching across different aspects of the taxonomy, but I'm not clear yet what a score >100 might indicate (if anything).  I suspect it may be associated with having multiple exact matches.

For example, here the first result is an exact genus match, and then the next two are the more helpful (to me) synonymy results at the species level 

`rgbif::name_backbone("Viburnum cassinoides", verbose = TRUE)`

Something similar happens even when we have multiple `EXACT` species matches but from different kingdoms:

`rgbif::name_backbone("Sagittaria australis", verbose = TRUE)`  

Thanks so much!

**Comment by jhnwllr** [comment]
Apparently confidence over 100 has no specific meaning. It was just hard to program it so that it always ended up below 100. I wouldn't take the number too literally.

**Comment by mdoering** [comment]
we capped it at some point, but I found it interesting to know the confident spread above 100. Guess we can cap it again to at least not confuse people.

**Comment by mikeroswell** [comment]
@mdoering, n =1 feedback here, but I think leaving it uncapped, but making how the score is computed transparent would be more satisfying than just re-jiggering the numbers to stop at 100. Thanks for taking a look at this!

**Comment by mdoering** [comment]
It is a score that combines various individual similarity scores. Fuzzy, strict and higher matches are scored slightly differently:

https://github.com/gbif/checklistbank/blob/master/checklistbank-nub/src/main/java/org/gbif/nub/lookup/fuzzy/NubMatchingServiceImpl.java#L406
