### ISSUE TITLE
supporting kingdomKey for downloading of data

### ISSUE THREAD

**Issue by vsjansen** [ropensci/rgbif#552]
It would be great to be able to download data by kindgom from gbif. It doesn't seem to be supported at this time. When I try I get "Error: 'kingdomKey' not in acceptable set of keys; see ?download_predicate_dsl"

Thanks!

**Comment by jhnwllr** [comment]
You should be able to still use taxonKey to get to kingdomKey

```
occ_download(pred("taxonKey", 1),format = "SIMPLE_CSV")
```

But I will make a note to add kindomKey to the accepted keys.

**Comment by jhnwllr** [comment]
I think just using taxonkey is a better option than adding all of the kingdomkeys, phylumkeys, ect.. so I will close.
