### ISSUE TITLE
Add support for `occurrenceRemarks` endpoint

### ISSUE THREAD

**Issue by Br-Johnson** [ropensci/rgbif#556]
The barcode of life database (BOLD) is crawled by GBIF annualy and they use the `occurrenceRemarks` field to identify contributing hosting institutions consistently. See https://www.gbif.org/occurrence/3441406435 for example.

I would like to be able to download all the occurrences from our Institute that are on GBIF in this particular dataset, but currently there is no consistent way to do that because `occurrenceRemarks` is not available as an endpoint. 

So, I'm hoping someone could add support for that!

Thanks, 
Brett

**Comment by jhnwllr** [comment]
@Br-Johnson @CecSve

I believe what you would need is to have is `occurrenceRemarks` as a search filter, but unfortunately that is not currently a search filter in the GBIF api. 
https://www.gbif.org/developer/occurrence#Searching

I noticed that the **International Barcode of Life project (iBOL)** is filling in `recordedBy` for **Hakai Institute**.  

`recordedBy` **is** a search filter in the API. 

I can suggest two solutions: 

1. download all of the records with `recordedBy` = "Hakai Instutute" (although that might not be as consistent as `occurrenceRemarks`)
https://www.gbif.org/occurrence/search?dataset_key=040c5662-da76-4782-a48e-cdea1892d14c&recorded_by=Hakai&recorded_by=Hakai%20Institute&recorded_by=Hakai%20Institute%20Nearshore%20Technicians&recorded_by=Hakai%20Insititute%20Terrestrial&advanced=1

```R
occ_download(pred("datasetKey","040c5662-da76-4782-a48e-cdea1892d14c"),
pred_in("recordedBy",
 c(
"Hakai Insititute",
"Hakai Insititute Terrestrial",
"Hakai Institute Nearshore Technicians")
),
format = "DWCA") 
```

2. download all of the records from **International Barcode of Life project (iBOL)** and filter the `occurrenceRemarks` column in `occurrence.txt`. 

```R 
occ_download(pred("datasetKey","040c5662-da76-4782-a48e-cdea1892d14c"),format = "DWCA")
```

Here is a related issue about the topic on the GBIF side
https://github.com/gbif/portal-feedback/issues/4422

**Comment by Br-Johnson** [comment]
Thanks for looking into this. Your suggestions make sense, though currently I can't get all the occurrences using `recordedBy`, likely because we were inconsistent in using that field in BOLD. 

I will follow up on this in the linked GBIF issue, and perhaps I need to review our process and records in BOLD to start with and make sure we are being consistent.

Cheers!
Brett
