### ISSUE TITLE
Add strict arg to name_backbone_checklist

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#565]
https://github.com/ropensci/rgbif/issues/564

**Comment by damianooldoni** [comment]
Thanks @jhnwllr to take into account this improvement. Indeed, we use `strict=TRUE` quite a lot as it is important to have only exact mathes in many situations.

Maybe you can consider the option to not only expose the `strict` arg but any other argument of `name_backbone` via ellipsis (`...`)? We did it in our wrapper function [inborutils::gbif_species_name_match](https://inbo.github.io/inborutils/reference/gbif_species_name_match.html) as it provides the user the maximum flexibility possible and makes what a wrapper function should do: exposing the very same set of functionalities as the central function, `name_backbone` in this case.

Notice that we are going to supersede our function and promoting the use of yours in the documentation: see PR https://github.com/inbo/inborutils/pull/121
