### ISSUE TITLE
How to get list of datasets published by an organisation?

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rgbif#577]
I was trying to retrieve all datasets published by [INBO](https://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b), but I didn't find any valuable solution, but maybe it's just me being very tired.

Via web or API is straightforward:
https://www.gbif.org/dataset/search?publishing_org=1cd669d0-80ea-11de-a9d0-f1765f95f18b
https://api.gbif.org/v1/dataset/search?publishing_org=1cd669d0-80ea-11de-a9d0-f1765f95f18b

Via rgbif? I wonder if you consider the idea to have next to `occurrence_*()` and `name_*` related functions also `dataset_*()` functions?

Thanks in advance.

**Comment by jhnwllr** [comment]
Hi @damianooldoni 

You can do this to get a list of datasets. 

```R 
rgbif::dataset_search(publishingOrg = "1cd669d0-80ea-11de-a9d0-f1765f95f18b")$data
```

I like the idea of more convenience wrappers. Getting a list of datasets from a publishers key is a very common task, so would be nice to have something like `dataset_list()` or `publisher_datasets()`.
