### ISSUE TITLE
consider adding support for datasetName

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#589]
https://api.gbif.org/v1/occurrence/search?datasetName=GBIF-2020_p06

**Comment by jhnwllr** [comment]
I haven't added this yet because I think it will cause confusion with users, since it **doesn't** mean **dataset title**.

For example, the official datasettitle for eBird returns nothing.

https://api.gbif.org/v1/occurrence/search?datasetName=EOD%20%E2%80%93%20eBird%20Observation%20Dataset

I plan to add it as an undocumented accepted key, so people who know what they are doing can still use it.

**Comment by jeroencreuwels** [comment]
datasetName might be confusing, but at the moment it is a great way to make (sub)selections across datasets. When datasets are grouped in standard taxonomic groups, as is the case in many museum collections, then important (sub)collections cannot be retrieved, for example from certain collectors, particular historic surveys, etc.   
An undocumented accepted key is fine by me, it makes a (sub)selection of users of this term as you mentioned above.
