### ISSUE TITLE
Error: #: required key [sendNotification] not found

### ISSUE THREAD

**Issue by ZhisenLuo** [ropensci/rgbif#593]
Thank you for offering so useful package. I encountered some error when use it today, but It worked fine the last few days.

Error: #: required key [sendNotification] not found

**Comment by hlhimes** [comment]
I also started seeing this error yesterday when trying to use occ_download(), which had been working fine all week. Here's the code I'm using that's producing the error:

> down1=occ_download(pred("taxonKey",key),
+                    pred("country","US"),
+                    pred("stateProvince",state_prov_name),
+                    pred("hasGeospatialIssue",FALSE),
+                    format="SPECIES_LIST")
Error: #: required key [sendNotification] not found

**Comment by dnoesgaard** [comment]
@hlhimes don't know what's causing the error but can I recommend using the gadm filters instead of `stateProvince`?

Example:
`pred("gadm","USA.2_1")` # for Alaska

This will ensure you only get geo-referenced records within the state. The subdivision codes for US states are available here: https://api.gbif.org/v1/geocode/gadm/USA/subdivisions

**Comment by mikeroswell** [comment]
I'm getting the same error, with additional confusion... the "not in acceptable set of keys" bit seems to contradict previous error. 

```{r}
MD_vasc_and_lep_doi <- occ_download(
+   user = "USER"
+   , pwd = "PASS"
+   , email = "EMAIL@EMAIL.COM"
+   , pred_in("taxonKey", c(7707728, 797))
+   , pred_in("basisOfRecord", c("OBSERVATION", "HUMAN_OBSERVATION", "PRESERVED_SPECIMEN"))
+   , pred_in("stateProvince", "Maryland")
+   , pred("hasCoordinate", TRUE)
+   , pred_and(pred_gte("year", 1989), pred_lte("year", 2021))
+   )
Error: #: required key [sendNotification] not found
> MD_vasc_and_lep_doi <- occ_download(
+   user = "USER"
+   , pwd = "PASS"
+   , email = "EMAIL@EMAIL.COM"
+   , pred_in("taxonKey", c(7707728, 797))
+   , pred_in("basisOfRecord", c("OBSERVATION", "HUMAN_OBSERVATION", "PRESERVED_SPECIMEN"))
+   , pred_in("stateProvince", "Maryland")
+   , pred("hasCoordinate", TRUE)
+   , pred("sendNotification", TRUE)
+   , pred_and(pred_gte("year", 1989), pred_lte("year", 2021))
+   )
Error: 'sendNotification' not in acceptable set of keys; see ?download_predicate_dsl
```

**Comment by jrhillae** [comment]
I am also getting the same error when running occ_download(pred("taxonKey", 5290026))

**Comment by jhnwllr** [comment]
@MattBlissett 

There hasn't been any changes to `rgbif::occ_download()` recently, so I believe this is a GBIF-server side error.

I ran the downloads API example (not rgbif) and got the same error . 
https://www.gbif.org/developer/occurrence

```shell
curl --include --user jwaller:<password> --header "Content-Type: application/json" --data '{"creator": "userName","notificationAddresses": ["jwaller@gbif.org"],"format": "SIMPLE_CSV","predicate": {"type": "in","key": "COUNTRY","values": ["FJ","TO"]}}' https://api.gbif.org/v1/occurrence/download/request
```

> HTTP/2 400
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
pragma: no-cache
expires: 0
x-frame-options: DENY
content-length: 44
date: Fri, 13 Jan 2023 20:40:43 GMT
cache-control: no-cache, no-store, must-revalidate
x-varnish: 852426860
age: 0
via: 1.1 varnish (Varnish/6.0)
#: required key [sendNotification] not foundj

**Comment by bhanberry** [comment]
I am experiencing the same error, if more reports may help prioritize issue resolution.

**Comment by MattBlissett** [comment]
> (Example from our documentation.)
> …
> #: required key [sendNotification] not found

That's the problem; we've (unintentionally, I believe) started requiring the `sendNotification` field.  The default would have been false, although a default of `isSet(notificationAddress)` might make more sense.

But if I read the R error above, `sendNotification` is not yet supported by rGBIF.

I think we'll be able to fix it on Monday morning (in Europe), apologies for the inconvenience.

**Comment by jhnwllr** [comment]
Yes seems to work now. Thanks @fmendezh 

```R
occ_download(pred("taxonKey", 5290026))
```
https://www.gbif.org/occurrence/download/0248733-220831081235567
