### ISSUE TITLE
 Run integration tests against live GBIF APIs

### ISSUE THREAD

**Issue by MattBlissett** [ropensci/rgbif#599]
It would be useful to run regular integration tests against the live UAT/Dev APIs, to detect any potential incompatible changes.

**Comment by jhnwllr** [comment]
This already happens: 
https://github.com/ropensci/rgbif/actions/runs/4001970657/jobs/6868748682

The latest run failed because of the change in the downloads api.

**Comment by MattBlissett** [comment]
Thanks John, that's useful. Did you get an email about the failed run?

I see it's scheduled to run every 3 days, and is presumably using the production API as the line to use the UAT API is commented out: https://github.com/ropensci/rgbif/blob/master/.github/workflows/check-cron.yml

@fmendez and I want to notice any problems before deploying any change to production, so we'll either need to have this (or an additional job) run against UAT and notify us, or run it on our own Jenkins in response to deployments to UAT.
