### ISSUE TITLE
improve organisations

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#606]
As far as I can tell. There is no support for publisher search

https://www.gbif.org/api/publisher/search?

**Comment by PietrH** [comment]
@jhnwllr Have you started on this? I'd like to give it a go.

**Comment by jhnwllr** [comment]
@PietrH sure go for it!

**Comment by PietrH** [comment]
Great! I'll get started

**Comment by jhnwllr** [comment]
hmmm ... it might already be supported...
https://docs.ropensci.org/rgbif/reference/organizations.html

**Comment by jhnwllr** [comment]
It's definitely confusing that it's called **publisher** everywhere on GBIF except for in the API. 

I think these two are equivalent: 


All of these should be the same : 

https://api.gbif.org/v1/organization?q=f
https://www.gbif.org/api/publisher/search?q=f

```r 
organizations(q="f") 
```

But you can't do a search for country with `rgbif::organizations()`. 

https://api.gbif.org/v1/organization?country=FR&q=f
https://www.gbif.org/api/publisher/search?country=FR&q=f


```r 
organizations(q="f",country="FR")
```

> Error in organizations(q = "f", country = "FR") : 
  unused argument (country = "FR")

**Comment by jhnwllr** [comment]
@PietrH if you want to add the country arg to `rgbif::organizations` that would still be helpful!

**Comment by PietrH** [comment]
Good we caught that early on! 

`rgbif::organizations()` seems to cover most of it.

I've noticed `rgbif::organizations()` doesn't support paging, or different searching by identifiers other than uuid, such as for example [URI](https://www.gbif.org/api/publisher/search?identifier=http://www.wikidata.org/entity/Q1543126&identifierType=URI) : `https://www.gbif.org/api/publisher/search?identifier=http://www.wikidata.org/entity/Q1543126&identifierType=URI`

We could also possibly add an argument for [endorsement status](https://www.gbif.org/developer/registry#p_isEndorsed), but I don't know if there is any user demand for any of the above. What do you think?

For now I'll just focus on adding country.

**Comment by jhnwllr** [comment]
**Obviously** I am not very familiar with what's in `rgbif::organizations()` 🤣, so ... 

If you have the time and energy to add paging or whatever you feel is missing, I support.

**Comment by jhnwllr** [comment]
We could even consider soft deprecating `rgbif::organizations` and calling the new interface `publishers`, but we can think about it...

**Comment by PietrH** [comment]
I'm in favor of calling the new interface `publishers`, but not sure how to proceed. Do you want me to put in a **PR for `rgbif::publishers` or for `rgbif::organizations`?**

I'd prefer to do it step by step, for now I'm adding country and some more tests. Next I'll probably have a look at the identifiers.  

I'm not sure how to deprecate functions without `lifecycle::deprecate_soft()` ([docs](https://lifecycle.r-lib.org/reference/deprecate_soft.html)). Is there an **example** I could have a look at? 

Thanks!

**Comment by jhnwllr** [comment]
Let's stay with `rgbif::organizations` for now. I need to think if the rename is a good idea.

**Comment by PietrH** [comment]
I've also made a few changes to the documentation of `rgbif::organizations()`, and opened a PR: #615 

Any feedback is highly appreciated!

**Comment by jhnwllr** [comment]
I made some comments, but I will give a full review in a few days. Thanks!

**Comment by PietrH** [comment]
Thank you for the quick response, I'll address your feedback today.
