### ISSUE TITLE
`occ_count` ignores input arguments

### ISSUE THREAD

**Issue by IvanPalm** [ropensci/rgbif#613]
<details> <summary><strong>Session Info</strong></summary>

R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS/LAPACK: /home/ivan/miniconda3/envs/biodiv/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.1.0 rgbif_3.7.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10       pillar_1.8.1      compiler_4.1.3    plyr_1.8.8        tools_4.1.3       uuid_1.1-0       
 [7] jsonlite_1.8.4    lifecycle_1.0.3   tibble_3.1.8      gtable_0.3.1      pkgconfig_2.0.3   rlang_1.0.6      
[13] cli_3.6.0         rstudioapi_0.14   crul_1.3          curl_4.3.3        httr_1.4.4        stringr_1.5.0    
[19] xml2_1.3.3        generics_0.1.3    vctrs_0.5.2       triebeard_0.3.0   grid_4.1.3        tidyselect_1.2.0 
[25] httpcode_0.3.0    glue_1.6.2        data.table_1.14.6 R6_2.5.1          oai_0.4.0         fansi_1.0.4      
[31] conditionz_0.1.0  ggplot2_3.4.1     magrittr_2.0.3    whisker_0.4.1     urltools_1.7.3    scales_1.2.1     
[37] colorspace_2.1-0  utf8_1.2.3        stringi_1.7.12    lazyeval_0.2.2    munsell_0.5.0  

</details>

I am attempting to retrieve the number of records collected for a few classes over time. I am now using `occ_count` for this purpose. In my understanding of the function, the code below should return the number of records collected for the given taxon (e.g., the class Insecta in the reprex below) between 1970 and 2022.   

```r
records = c(
    'OBSERVATION',
    'HUMAN_OBSERVATION', 
    'MACHINE_OBSERVATION',
    'LIVING_SPECIMEN'
    )

occ_count <- occ_count(
    taxonKey = 5051321,
    basisOfRecord = records,
    type = 'year',
    from = 1970,
    to = 2022
)

length(occ_count)
names(occ_count)

```
There are 424 items in the list and the names reveal that data from 1622 on are retrieved.  

Besides this, I have tried to set the arguments `country` and `publishingCountry` as displayed below. Also in this case I am observing an unexpected behavior because the number of records does not change regardless the value I set to those arguments. I tried 'IT', 'UK' and a character vector with all the 249 ISO2 codes of the world. The function call returned the same results.

```r
occ_count <- occ_count(
    taxonKey = class_key,
    basisOfRecord = records,
    type = 'year',
    from = 1970,
    to = 2022,
    country = 'IT',
    publishingCountry = 'IT'
)
``` 
I'm new to this package so I'm probably doing something wrong (and I'm now suspecting that the results are unchanged because retrieved from cache). Can you please clarify these aspects, and/or point out the most suitable function to retrieve the data described above?

**Comment by jhnwllr** [comment]
@IvanPalm 

The `occ_count()` interface is a bit limited, so I usually just work with `occ_search()` when I need counts. 

I believe this is the count you are trying to get

```r
occ_search(
taxonKey = 5051321,
basisOfRecord ="OBSERVATION;HUMAN_OBSERVATION;MACHINE_OBSERVATION;LIVING_SPECIMEN",
year="1970,2022",
limit=0)$meta$count
```
> 16792

https://www.gbif.org/occurrence/search?basis_of_record=OBSERVATION&basis_of_record=HUMAN_OBSERVATION&basis_of_record=LIVING_SPECIMEN&basis_of_record=MACHINE_OBSERVATION&taxon_key=5051321&year=1970,2022

**Comment by IvanPalm** [comment]
Thank you for the feedback @jhnwllr

Yes, I have read about the possibility to get counts by setting `limit=0` in `occ_search`. In fact I also attempted a function call very similar to the one you have kindly suggested. The problem is that the function call returns a single value for all years, while I was hoping to get a time series of count values. Is there any chance to get that with `occ_search`?

**Comment by jhnwllr** [comment]
@IvanPalm 

I think you are looking for the "facets" interface, which isn't very pretty but it works: 

```r 
rgbif::occ_search(taxonKey=5051321,
year="1970,2022",
basisOfRecord="OBSERVATION;HUMAN_OBSERVATION;MACHINE_OBSERVATION;LIVING_SPECIMEN",
facet = c("year"),
limit=0,
year.facetLimit = 100000)$facets$year %>% 
mutate(name = as.numeric(name)) %>%
arrange(-name) %>% 
knitr::kable()
```

| name| count|
|----:|-----:|
| 2022|  3439|
| 2021|  3595|
| 2020|  2286|
| 2019|  1971|
| 2018|  1335|
| 2017|  1057|
| 2016|   669|
| 2015|   472|
| 2014|   248|
| 2013|   278|
| 2012|   162|
| 2011|   159|
| 2010|   261|
| 2009|   147|
| 2008|   168|
| 2007|   119|
| 2006|    76|
| 2005|    69|
| 2004|   107|
| 2003|    46|
| 2002|    15|
| 2001|    18|
| 2000|    15|
| 1999|     1|
| 1998|     7|
| 1997|     8|
| 1996|     8|
| 1995|    17|
| 1994|     5|
| 1993|     3|
| 1992|     2|
| 1991|     4|
| 1990|     1|
| 1989|     1|
| 1988|     1|
| 1987|     1|
| 1985|     1|
| 1983|     1|
| 1981|     2|
| 1975|     2|
| 1973|     3|
| 1972|     7|
| 1971|     4|
| 1970|     1|

**Comment by IvanPalm** [comment]
Brilliant, I was unaware of the "facets" interface. It seems to return the data I was after. Thank you!
I will close the issue as my doubts have been cleared.
