### ISSUE TITLE
could rgbif do without {conditionz}?

### ISSUE THREAD

**Issue by maelle** [ropensci/rgbif#624]
:wave: @jhnwllr! {conditionz} has been archived on GitHub (not archived on CRAN yet) because it is no longer maintained. Do you think rgbif could do without it? Would you need help, for instance a PR keeping the same kind of functionality?

**Comment by maelle** [comment]
If I am reading the conditionz usage correctly, it could be replaced with https://lifecycle.r-lib.org/ functions

**Comment by maelle** [comment]
Thanks so much @jhnwllr

**Comment by maelle** [comment]
@jhnwllr with {lifecycle} the deprecation warning would appear once per session for info.

**Comment by jhnwllr** [comment]
@maelle I am sort of between two minds if I think a deprecation warning should appear more than once.

**Comment by maelle** [comment]
btw I recently re-read for another project: https://twitter.com/hadleywickham/status/1582788323206012928 :sweat_smile:
