### ISSUE TITLE
Remove dependency on randgeo?

### ISSUE THREAD

**Issue by maelle** [ropensci/rgbif#625]
:wave: @jhnwllr! Similarly to #624, randgeo is no longer maintained and has been archived on GitHub (not on CRAN yet).

Could it be removed from rgbif? Do you need any help with this (I could make a PR)?

**Comment by jhnwllr** [comment]
Thanks @maelle 

Appears to be only used for some tests. I will try to remove in the next version.

**Comment by maelle** [comment]
Thanks so much @jhnwllr!
