### ISSUE TITLE
Transformation of long WKT in order to download occurence data

### ISSUE THREAD

**Issue by harpogophytum** [ropensci/rgbif#644]
Hi

I am trying and failing to download a data set of all plant specimens ever collected for a specific wkt footprint. The footprint is clockwise and I see that it needs to be counter clockwise and potentially even simplified. Through the API using R, I have had no success with this utilizing occ_download function and pre-loading in my wtk to my r session. I have read a few blogs and such, but it is still not working. Is there any way to simplify the wkt footprint or transform it if it is not working in rgbif or in gbif online as the character length is too long.

**Comment by jhnwllr** [comment]
Hi @harpogophytum, 

Getting the geometries right can be hard. 

Can you paste WKT text/polygon you are trying to use here?


Also check the web portal simplifier: 

https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-75.5248%2039.73138,-75.52235%2039.73557,-75.52361%2039.73964,-75.53319%2039.74288,-75.53734%2039.7515,-75.54663%2039.75502,-75.55017%2039.7491,-75.54401%2039.74711,-75.54096%2039.73908,-75.5464%2039.73687,-75.55252%2039.73926,-75.5592%2039.73888,-75.57831%2039.72183,-75.59402%2039.72296,-75.60006%2039.71878,-75.59546%2039.7136,-75.59784%2039.7121,-75.60225%2039.71422,-75.60887%2039.71379,-75.60744%2039.70776,-75.60141%2039.69606,-75.59233%2039.69635,-75.58434%2039.6986,-75.5809%2039.70055,-75.57806%2039.71355,-75.55916%2039.71543,-75.55721%2039.71803,-75.55067%2039.72014,-75.55233%2039.72503,-75.54357%2039.72625,-75.53506%2039.7178,-75.53245%2039.71679,-75.53091%2039.71841,-75.51064%2039.71203,-75.50621%2039.72049,-75.52604%2039.72532,-75.5282%2039.72926,-75.5248%2039.73138))&occurrence_status=present
![image](https://user-images.githubusercontent.com/4245213/228183461-e4b8a44d-58f8-4e64-8cf4-18d06000a80f.png)

**Comment by MattBlissett** [comment]
There's an example using the ogr2ogr tool for simplification here: 

https://github.com/gbif/occurrence/blob/468e9b88b47f6f5133c42c9d098c5596d925920c/occurrence-download/example-jobs/download-from-openstreetmap-polygon.sh#L23-L24

But otherwise I'd look at something like https://rgeos.r-forge.r-project.org/reference/topo-unary-gSimplify.html

**Comment by jhnwllr** [comment]
Looking at the polygon. 

I am going to guess that it isn't projected in WGS84. 

That is just a guess but it doesn't look like the polygon would make a meaningful download since most of the points seem to be along a line...

**Comment by jhnwllr** [comment]
The polygon appears to be mostly in a line. 

Is this really what you want? 

Can you send a screen shot of how it looks in Arc GIS ? 

I guess that it isn't projected in WGS84.

**Comment by MattBlissett** [comment]
Note each pair of coordinates is also swapped. WKT must be `POLYGON((longitude1 latitude1, longitude2 latitude2, ..., longitude1, latitude1))` but -106 is less than the minimum latitude of -90°.
