### ISSUE TITLE
rgbif:name_backbone() requests coming up blank when genus is available on GBIF

### ISSUE THREAD

**Issue by flyingratchet** [ropensci/rgbif#649]
I have a group of around 100 taxa that I'm trying to query in R and for some reason about 10% of them don't work. They either turn up blank or they return only the genus—but when I got to the website, those taxa are there part of the backbone taxonomy. Here's one example:

rgbif:name_backbone("Acrotylus")

...returns no results, even though the taxon does exist on GBIF:
https://www.gbif.org/species/1711256

Any thoughts?

**Comment by jhnwllr** [comment]
I don't know for sure what is happening with the other 10% of the names that do not match to the GBIF backbone, but for the example you give, it what I call the "**too many choices problem**". There exists more than one entry in the backbone with that name. Using **authorship** usually fixes the problem. 

https://docs.ropensci.org/rgbif/articles/taxonomic_names.html#too-many-choices-problem

Using the author results in a match. 

`rgbif::name_backbone("Acrotylus Fieber, 1853")`

If you do not know the authorship, you might need to use `rgbif::name_backbone("Acrotylus",verbose=TRUE)`, which will return more choices for you to manually review.

**Comment by flyingratchet** [comment]
Oh thank you!! I That makes sense. I was very puzzled by that. Coincidentally, I was trying to glean the author names themselves from gbif—so the "verbose=TRUE" seems like the way to go in instances of ambiguity.
