### ISSUE TITLE
elevation() returns "Error: Unauthorized (HTTP 401)" 

### ISSUE THREAD

**Issue by MaxCarabus** [ropensci/rgbif#655]
elevation(latitude = c(47.4436), longitude = c(74.81753), elevation_model = 'srtm1')

locality = data.frame(decimalLongitude = 74.81753, decimalLatitude = 47.4436)
elevation(input = locality, elevation_model = 'srtm3')

both codes return: "Error: Unauthorized (HTTP 401)"

**Comment by jhnwllr** [comment]
You need to have a GeoNames account to make the `elevation()` work. 

To get a GeoNames user name, register for an account at http://www.geonames.org/login - then you can enable your account for the GeoNames webservice on your account page (http://www.geonames.org/manageaccount). Once you are enabled to use the webservice, you can pass in your username to the username parameter. Better yet, store your username in your .Renviron file, or similar (e.g., .zshrc or .bash_profile files) and read it in via [Sys.getenv()](https://rdrr.io/r/base/Sys.getenv.html) as in the examples below. By default we do Sys.getenv("GEONAMES_USER") for the username parameter.

**Comment by jhnwllr** [comment]
This article should give you a good idea how to save your GEONAMES_USER information so you don't have to enter it each time you run the function.  
https://docs.ropensci.org/rgbif/articles/gbif_credentials.html

**Comment by MaxCarabus** [comment]
I saved in .Renviron:
GEONAMES_EMAIL                     user@gmail.com
GEONAMES_PWD                       pass
GEONAMES_USER                     user
and got the same: "Error: Unauthorized (HTTP 401)"

**Comment by jhnwllr** [comment]
There is another setting somewhere on geonames that you have to check. It's like "allow api usage" something like that.
