### ISSUE TITLE
search datasets metadata based on dwc-a endpoint

### ISSUE THREAD

**Issue by rubenpp7** [ropensci/rgbif#658]
Hi,

I would like to search datasets metadata in GBIF based on their IPT resource url (or DWC_ARCHIVE endpoint), is there a function in this R package that allows that?

for example, I would like to get the UUIDs of the datasets with IPT resource URL in ("https://ipt.inbo.be/resource?r=hg_oostende", "https://ipt.vliz.be/eurobis/resource?r=monicet")

Thank you!

**Comment by jhnwllr** [comment]
@rubenpp7 

I don't think there is a way to do this in rgbif.

You could try 

```R 
jsonlite::fromJSON("http://api.gbif.org/v1/dataset?identifier=https://ipt.inbo.be/resource?r=hg_oostende")$results$key
```  
https://www.gbif.org/dataset/6c860eb3-83ba-48c3-9328-a

**Comment by rubenpp7** [comment]
Alright, I'm happy with your alternative solution though :)

Cheers!!
