### ISSUE TITLE
Add a checklist function

### ISSUE THREAD

**Issue by silasprincipe** [ropensci/rgbif#660]
Hi all! I would like to suggest an addition to `rgbif`, a checklist function as there is on the `robis` package: https://iobis.github.io/robis/reference/checklist.html. It would probably involve adding something to the API as well. Maybe, a starting point could be using the "count" structure, but instead of just counting all records, it would get all unique names.

If there is a functionality already and I was unable to find it on the reference, then I apologize for my mistake.

## Justification

There are many applications that require nothing more than the list of the species occurring on a certain area. Suppose that you need ONLY the name of all mammals occurring in a reserve. You would originally need to pass a search with a WKT string, retrieve all occurrence records (what may take some time of "download waiting") and then get only the unique names.

**Comment by jhnwllr** [comment]
Hi @silasprincipe 

https://docs.ropensci.org/rgbif/articles/occ_counts.html

This is largely already possible using `occ_count(facet="x")`

For example, this will give you a list all of the mammal species in Sweden. 

```R
occ_count(facet="speciesKey", taxonKey = 359,facetLimit=200000,country="SE")
```

Or by some polygon... 

```R 
occ_count(facet="speciesKey", geometry="POLYGON((24.70938 48.9221,24.71056 48.92175,24.71107 48.92296,24.71002 48.92318,24.70938 48.9221))",facetLimit=200000) 
```



There is also `occ_download(format="SPECIES_LIST")`

**Comment by silasprincipe** [comment]
Thanks @jhnwllr , and sorry for missing those possibilities! Nice to be aware now, it will be super useful. Thanks for keeping `rgbif`.
