### ISSUE TITLE
Feature request: add gbifID as predicate to occ_download()

### ISSUE THREAD

**Issue by olehprylutskyi** [ropensci/rgbif#665]
Adding 'gbifID' (unique global identifier of an occurrence) to the predicate list would be much more of use that current predicate 'occurrenceId', which searches across internal dataset's identifiers that might be non-unique within GBIF and therefore ambiguous.

**Comment by jhnwllr** [comment]
I don't think the `gbifID` is part of downloads API.  @MattBlissett

**Comment by MattBlissett** [comment]
That's correct, the list of supported parameters is here: https://gbif.github.io/gbif-api/apidocs/org/gbif/api/model/occurrence/search/OccurrenceSearchParameter.html
