### ISSUE TITLE
xxxKey predicates

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/rgbif#668]
This is extending #661, to other keys. I think all fields with `xxxKey` should be supported:
- [x] taxonKey
- [x] acceptedTaxonKey
- [x] kingdomKey
- [x] phylumKey
- [x] classKey
- [x] orderKey
- [x] familyKey
- [x] genusKey
- [x] subgenusKey
- [x] speciesKey

Usecase: I want to limit my search to birds and I could not do it today. The new system would allow me to specify `classKey` equal to 212.

**Comment by jhnwllr** [comment]
I have not seen "acceptedTaxonKey" as a search filter. Can you point to me where you found it?

**Comment by MattBlissett** [comment]
It does exist: https://gbif.github.io/gbif-api/apidocs/org/gbif/api/model/occurrence/search/OccurrenceSearchParameter.html though it is missing from the public documentation.

**Comment by dmi3kno** [comment]
I added it to the PR. Please review and merge
