### ISSUE TITLE
Retrieving a species list from a taxon for a specific country.

### ISSUE THREAD

**Issue by mgdlg** [ropensci/rgbif#683]
Hello! Very basic question and I know it is something very simple. For a school project I would like to automate in RStudio a way to retrieve the list of species of a taxonomic group for my country.

**Let's say I need registered species of Marsupials in Mexico and the citation of the resources where the data was obtained from. Is it possible?**

**Comment by mgdlg** [comment]
I understand there's a way to doo this https://github.com/ropensci/rgbif/issues/660#issuecomment-1623760457

Is there a way to retrieve the citations for the species record used?

**Comment by jhnwllr** [comment]
Hello @mgdlg 

Here is example of downloading a species list from a country with citation. 

```R 
library(rgbif)

occ_download(pred("country","SE"),format="SPECIES_LIST")
```

The print out should give you the citation. 

```
<<gbif download>>
  Your download is being processed by GBIF:
  https://www.gbif.org/occurrence/download/0011268-230828120925497
  Most downloads finish within 15 min.
  Check status with
  occ_download_wait('0011268-230828120925497')
  After it finishes, use
  d <- occ_download_get('0011268-230828120925497') %>%
    occ_download_import()
  to retrieve your download.
Download Info:
  Username: jwaller
  E-mail: jwaller@gbif.org
  Format: SPECIES_LIST
  Download key: 0011268-230828120925497
  Created: 2023-09-11T06:59:57.917+00:00
Citation Info:  
  Please always cite the download DOI when using this data.
  https://www.gbif.org/citation-guidelines
  DOI: 10.15468/dl.87p7bm
  Citation:
  GBIF Occurrence Download https://doi.org/10.15468/dl.87p7bm Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2023-09-11
```
Namely this

>  GBIF Occurrence Download https://doi.org/10.15468/dl.87p7bm Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2023-09-11

You can see it on your user page too
https://www.gbif.org/occurrence/download/0011268-230828120925497
