### ISSUE TITLE
[suggestion]enable offline workflows

### ISSUE THREAD

**Issue by andzandz11** [ropensci/rgbif#685]
I am a fan of the idea behind the package taxizedb, which is to download a copy of the taxonomic database and enable offline work with it.
I was wondering if GBIF would be willing in assist to develop this because it will take a lot of load off their servers.
I have to check 113000 species names every odd week with name_backbone_checklist() and I am just one user.
I am wondering what is "better", one thousand small queries or one big download.
Of course that probably won't work with occurence data.

Please close after you have read this. Just wanted to mention some alternatives as the rgbif package becomes more and more popular.

**Comment by jhnwllr** [comment]
@andzandz11 thanks for the suggestion. I am not sure if anything like that will be available in the near future. 

However, you might be interested in full GBIF backbone downloads available here: 
https://hosted-datasets.gbif.org/datasets/backbone/
