### ISSUE TITLE
isocodes spelling

### ISSUE THREAD

**Issue by andzandz11** [ropensci/rgbif#688]
Hi, can you please check the spelling?
The "name" seems to be incorrect. At least according to Wikipedia.
The "gbif_name" is correct.

```
isocodes[53,]
 code  name gbif_name
53   CW Curao   CURACAO

```

edit1: Saint Barthalemy   (should be written with "e" no?)

edit2: One country is missing: https://en.wikipedia.org/wiki/Kosovo

edit3: Haha this is a funny one. I thought my code had an error. But "NA" is indeed Namibia (also missing from isocodes).

**Comment by MattBlissett** [comment]
Thanks for letting us know. 

Ideally this file should be derived from https://api.gbif.org/v1/enumeration/country at compile or pre-compile time.

**Comment by jhnwllr** [comment]
@andzandz11 
`isocodes` is an old static data file. I think we should probably get rid of it. `enumeration_country()` is probably going to be better or at least up to date with GBIF.

**Comment by andzandz11** [comment]
Didn't know that using the API or enumeration_country() is the recommended course of action! Thanks for letting me know.
