### ISSUE TITLE
Why occ_download return a CSV file contains only one column and diferent rows?

### ISSUE THREAD

**Issue by WDragon101** [ropensci/rgbif#708]
occ_download repored total records: 1202857, but it downloaded a file with Rows: 1140846 Columns: 1?

`occ_download(pred_in("kingdomKey", plantae_key),
             pred_in("hasCoordinate", TRUE),
             pred_in("hasGeospatialIssue", FALSE),
             pred_within(himalaya_polygon_wkt),
             format = "SIMPLE_CSV",
             user = "whitedrogan",
             pwd = "mypassword",
             email = "bailongzhao@163.com")`

<<gbif download>>
  Your download is being processed by GBIF:
  https://www.gbif.org/occurrence/download/0058037-240229165702484
  Most downloads finish within 15 min.
  Check status with
  occ_download_wait('0058037-240229165702484')
  After it finishes, use
  d <- occ_download_get('0058037-240229165702484') %>%
    occ_download_import()
  to retrieve your download.
Download Info:
  Username: whitedrogan
  E-mail: bailongzhao@163.com
  Format: SIMPLE_CSV
  Download key: 0058037-240229165702484
  Created: 2024-03-11T00:53:59.342+00:00
Citation Info:  
  Please always cite the download DOI when using this data.
  https://www.gbif.org/citation-guidelines
  DOI: 10.15468/dl.dtnt75
  Citation:
  GBIF Occurrence Download https://doi.org/10.15468/dl.dtnt75 Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2024-03-11

`occ_download_wait('0058037-240229165702484')`

status: succeeded
download is done, status: succeeded
<<gbif download metadata>>
  Status: SUCCEEDED
  DOI: 10.15468/dl.dtnt75
  Format: SIMPLE_CSV
  Download key: 0058037-240229165702484
  Created: 2024-03-11T00:53:59.342+00:00
  Modified: 2024-03-11T00:58:14.355+00:00
  Download link: https://api.gbif.org/v1/occurrence/download/request/0058037-240229165702484.zip
  Total records: 1202857

`d <- occ_download_get('0058037-240229165702484') %>%
    occ_download_import()`

Download file size: 109.88 MB
On disk at D:\Work_Space\Pan-Himalaya\0058037-240229165702484.zip
|--------------------------------------------------|
|==================================================|

`unzip("D:/Work_Space/Pan-Himalaya/0058037-240229165702484.zip")
occs <- read_csv("0058037-240229165702484.csv")`

Rows: 1140846 Columns: 1                                                                  
── Column specification ───────────────────────────────
Delimiter: ","
chr (1): gbifID	datasetKey	occurrenceID	kingdom	phy...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning message:
One or more parsing issues, call `problems()` on your
data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat)

**Comment by jhnwllr** [comment]
@WDragon101 

Can I ask what you get using this? 

```R
occ_download_get("0058037-240229165702484") |> occ_download_import() |> nrow()
```

**Comment by jhnwllr** [comment]
```R
d <- occ_download_get("0058037-240229165702484") |> 
        occ_download_import()

nrow(d)
```

1202857


![image](https://github.com/ropensci/rgbif/assets/4245213/ee6f8c47-c42e-4fab-9d69-ea594fb2f94d)


please use occ_download_import()

**Comment by jhnwllr** [comment]
Read.table has a hard time reading in complex tsv files.

**Comment by WDragon101** [comment]
Thanks a lot, that's helpful!
