### ISSUE TITLE
add guidance for reversing WKT winding order

### ISSUE THREAD

**Issue by sformel-usgs** [ropensci/rgbif#724]
Per the documentation and as discussed via #361 a WKT polygon needs to be anti-clockwise to be considered an outline, not a hole.  This issue explains why these are rejected: https://github.com/gbif/occurrence/issues/340 but I couldn't easily find guidance on reversing the winding order. As noted in https://github.com/gbif/portal-feedback/issues/2032, the popular R package `sf` returns WKT polygons clockwise by default, so I think it's important to give users a helping hand when they run into this situation.

The solution I eventually figured out was from the `wk` package:

```
PR_EEZ <- mregions2::gaz_geometry(x = 33179) %>% 
  st_convex_hull() %>% 
  st_as_text() %>% 
  wk::wkt() %>% 
  wk::wk_orient()
```

If I didn't overlook already existing guidance, I suggest guidance, or example code be described in the rgbif manual and/or the API error message.

**Comment by jhnwllr** [comment]
Thanks for this issue @sformel-usgs. I think we could add it to the article about getting occurrence data. 

This solution might be able to save this feature that I didn't have the energy to support. 
https://github.com/ropensci/rgbif/issues/718
