### ISSUE TITLE
lastInterpreted argument of `occ_search()` does not appear to be functioning

### ISSUE THREAD

**Issue by mccrea-cobb** [ropensci/rgbif#739]
occ_search(limit = 0, lastInterpreted = '2023') finds zero records.
Records found [0] 
Records returned [0] 
No. unique hierarchies [0] 
No. media records [0] 
No. facets [0] 
Args [occurrenceStatus=PRESENT, limit=10, offset=0, lastInterpreted=2023, fields=all] 

occ_search(limit = 0, lastInterpreted = '1776,2023') finds zero records
Records found [0] 
Records returned [0] 
No. unique hierarchies [0] 
No. media records [0] 
No. facets [0] 
Args [occurrenceStatus=PRESENT, limit=10, offset=0, lastInterpreted=1776,2023, fields=all]

**Comment by jhnwllr** [comment]
I am not very familiar with that field, but it appears to work if you use the current year. 

`occ_search(lastInterpreted = '2024')`

Maybe all GBIF records have been "last interpreted" in 2024? @MattBlissett

**Comment by mccrea-cobb** [comment]
Yes, it finds all records when lastInterpreted is defined as 2024 and none otherwise.

**Comment by MattBlissett** [comment]
This is correct, as all records are reinterpreted when we make changes to the taxonomic backbone, map layers and other sources used for quality checks.
