### ISSUE TITLE
`occ_download_cached()` finds nothing

### ISSUE THREAD

**Issue by UlvHare** [ropensci/rgbif#748]
Hello!
In rmarkdown document I want to check if I have recent (less then month) download and if yes get it else make a new query.

The query (credentials are not shown):
``` r
occ_download(
   pred("classKey", 359),
    pred("hasGeospatialIssue", FALSE),
    pred("hasCoordinate", TRUE),
    pred_lte("coordinateUncertaintyInMeters", 5000),
    pred_within(my_wkt)
)
```

Everything OK, I can get it. But when I try to check:

``` r
occ_download_cached(
   pred("classKey", 359),
    pred("hasGeospatialIssue", FALSE),
    pred("hasCoordinate", TRUE),
    pred_lte("coordinateUncertaintyInMeters", 5000),
    pred_within(my_wkt)
)
```

I get only 

``` r
no match found
[1] NA
```

Even minimal request

``` r
occ_download_cached(
    pred("hasCoordinate", TRUE),
)
```
gives the same result, nothing

**Comment by UlvHare** [comment]
``` r
occ_download_cached(
    pred("hasCoordinate", TRUE),
)
```

still doesn't work :-(

**Comment by jhnwllr** [comment]
@UlvHare there was some boilerplate that was in the GBIF version that was not in the rgbif generated version, that I am filtering out. Fix is coming soon.

**Comment by UlvHare** [comment]
@jhnwllr, thank you very much! Now it works!
