### ISSUE TITLE
Search MeasurementOrFact

### ISSUE THREAD

**Issue by kguidonimartins** [ropensci/rgbif#761]
Hi folks, thanks for this package!

I'm trying to search dataset with `MeasurementOrFact`, as informed [here](https://docs.ropensci.org/rgbif/articles/effectively_using_occ_search.html#dwca-extensions). But does not work.

Is there another way?

``` r
rgbif::occ_search("http://rs.tdwg.org/dwc/terms/MeasurementOrFact")
#> Error: some param names not allowed: dwcaExtension
```

Thanks in advance.

<sup>Created on 2024-12-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jhnwllr** [comment]
@kguidonimartins 
Thanks for getting in contact. 

This works for me with the **latest version of rgbif**. 
```R 
rgbif::occ_search(dwcaExtension="http://rs.tdwg.org/dwc/terms/MeasurementOrFact")
```

Please check that you have the latest version installed from CRAN. 

`sessionInfo()` should be give **rgbif_3.8.1** or higher.

**Comment by kguidonimartins** [comment]
Hi @jhnwllr! Wow, I didn't even notice the package version! Sorry for that. Everything works perfectly now. Thanks
